netbirdio/netbird

.github/workflows/release.yml, .goreleaser.yaml, Dockerfile, README.md
Resolves issue #4 by building and sending docker images to Github registry.
=> Building docker images for signal service

README.md, infrastructe_files/docker-compose.yml, infrastructe_files/turnserver.conf
* A simple example to run Signal server and Coturn to help the community get started.
* Added MACOS guide
=> Adding example infrastructure files and MACOS guide

cmd/addpeer.go, cmd/up.go
Handle errors when failing to read config files.
Closes #50
=> Handle read config file errors

.goreleaser.yaml
Builds management binaries, but don't archive them as tars, only as docker images
=> build Wiretrustee management binaries

management/server/account.go, management/server/http/handler/setupkeys.go, management/server/setupkey.go
=> increase key used times after successful peer registration

.goreleaser.yaml
Docker image generation is being done using the wrong platform parameter.
closes #103
=> fix: management amd64 docker image generation

.github/workflows/release.yml
This change means that we will be building the binary files for windows, and a private repository action will be handling signing, installer generation and updating the release with the Signed versions of the client and its installer.
The reason for that is that we need a  Self-hosted runner with a Windows server in order to sign the packages using the certificate from Certum. This will allow us to safely run the signing workflow without disabling all incoming PRs.
We should consider in the near future a replacement for the certificate provider.
=> Removed installer and add workflow dispatch

.goreleaser.yaml
There is a behavior or bug in goreleaser where it appends the file name in the target URL and that was causing issues and misconfigured properties
=> set IF arm6 and empty attribute for package

client/internal/connection.go, client/internal/engine.go, signal/client/client.go, signal/client/client_test.go
Too many open files are caused by the agent not being closed after unsuccessful attempts to start a peer connection.
Open FDs are growing if clients can't connect to Signal. Happens due to numerous retries without closing agent on failure.
=> fix: too many open files caused by agent not being closed

client/installer.nsis
Ensure the service is stopped before uninstalling.
Closes #157
=> Fix: Stop service before uninstall

client/cmd/up.go, client/internal/engine.go, client/internal/engine_test.go
Rollback's previous change was causing issues with agent stop logic.
=> Rollback stopping management client within engine stop

.goreleaser.yaml, client/cmd/version.go, client/main.go, client/system/info.go, client/system/info_darwin.go, client/system/info_freebsd.go, client/system/info_linux.go, client/system/info_test.go, client/system/info_windows.go, management/client/grpc.go
Changes: 
* sends the client version now to management server instead of empty string
* moved the version information to the system package
=> Add client version to the client app and send it to the management service

client/cmd/login.go, management/client/grpc.go, signal/client/grpc.go
On initial run (`wiretrustee up`) client makes a login request to management service.
If for some reason this command fails, client won't start anymore.
Fix: retry logic when running login command
=> Login exits on a single attempt to connect to management

client/internal/peer/conn.go, go.sum, util/file.go
In the event of a full disk, we may encounter the case where the destination file gets replaced by an empty file as the ioutil.WriteFile truncates the destination before writing.
Closes #237
=> Write to temp file before saving data

management/server/account.go, management/server/account_test.go, management/server/grpcserver.go, management/server/http/handler/peers.go, management/server/http/handler/setupkeys.go, management/server/http/server.go, management/server/peer.go, management/server/user.go
Accountmanager has been extracted to an interface, and the previous implementation renamed to DefaultAccountManager
=> extracted accountmanager to interface

client/internal/proxy/noproxy.go
When connection is closed the wireguard peer should be gone.
It wasn't happening until this fix.
=> Remove Wireguard peer in no-proxy mode on Close

management/server/account.go, management/server/account_test.go
When an account id supplied via a claim, we should handle the change of the domain classification.
If the category of domain changes to private, we should re-evaluate the private account
=> Handle category change with provided Acc Id

management/server/idp/auth0.go, management/server/idp/auth0_test.go, management/server/idp/idp.go, management/server/testdata/management.json
When loading the configuration from file we will use the Auth0ClientConfig and when sending the post to retrieve a token
we use the auth0JWTRequest with proper tags.
Also, removed the idle timeout as it was closing all idle connections
=> Fix IDP Manager config structs with correct tags

client/cmd/login_test.go, client/cmd/testutil.go, client/cmd/up_daemon_test.go, client/cmd/up_test.go
when testing CMDs we were using some global variables which got replaced by parallel tests.
Now we will call a single function independently for each test.
=> Call start services function for tests

util/log.go
Enabling report caller when log level equals debug. Also added a Caller prettyfier to avoid full file path
=> Enable Report Caller when log level Debug

client/cmd/down.go, client/cmd/login.go, client/cmd/status.go, client/cmd/up.go
Logger has not been initialized in cmd.
Every client cmd now initializes logger
=> Init logger for every cmd

client/internal/engine.go, client/internal/peer/conn.go
When stopping engine, all peer conns have to be closed
and for each peer WireGuard iface is called
to remove WireGuard peer.
This operation happens in a goroutine causing
Engine to remove the whole WireGuard interface before.
Therefore consequent calls to RemovePeer are unsuccessful.
This fix just adds a small delay before removing interface.
=> Fix error when stopping Engine

README.md, client/internal/config.go, client/internal/config_test.go
If ManagementURL is present in the config file
and cmd (e.g. up or login) specifies a new one,
then update the config file with a new ManagementURL
=> Update ManagementURL in Config

.github/workflows/release.yml, .goreleaser.yaml, README.md, client/cmd/status.go, release_files/post_install.sh, release_files/pre_remove.sh
Since goreleaser v1.6.0 binaries are installed to
/usr/bin/ instead of /usr/local/bin/ .
This fix changes binaries path of wiretrustee
See for details:
https://github.com/goreleaser/goreleaser/releases/tag/v1.6.0
=> Fix goreleaser version to 1.6.3

client/cmd/status.go
This:
```
Run UP command to log in with SSO (interactive login):
netbird up 
If you are running a self-hosted version and no SSO provider has been configured in your Management Server,
you can use a setup-key:
netbird up --management-url <YOUR_MANAGEMENT_URL> --setup-key <YOUR_SETUP_KEY>
More info: https://www.netbird.io/docs/overview/setup-keys
```
Instead of this:
```
run the command "netbird up" to login. If no SSO provider has been set in your management serveryou can use a setup-key, see more at https://www.netbird.io/docs/overview/setup-keys for more info
```
=> Improve output of a status command

management/cmd/management.go, management/cmd/root.go
When we move the files to the new path(docker-compose deployment), there was no Management Data Dir being set, causing an issue with the configuration file
This allows for mgmtDataDir and mgmtConfig to be initialized properly
use handleMigration function for copying files
=> Move flags declaration to root

client/internal/oauth.go, client/server/server.go, client/ui/client_ui.go
Reuse existing authentication flow if is not expired
Created a new struct to hold additional info about the flow
If there is a waiting SSO running, we cancel its context 
Run menuUpClick() as goroutine
Deal with slow_down messages from provider
=> Unblock menu when login

client/internal/config.go, client/internal/peer/conn.go, client/internal/peer/conn_test.go
See https://github.com/netbirdio/netbird/issues/349
=> Add more interfaces to ignore

client/internal/connect.go, client/internal/engine.go, client/internal/peer/conn.go
For some reason when reading a list of interfaces to ignore
from the config property `IFaceBlackList`, Engine was taking
only every other interface. Therefore, not all the interfaces
were ignored.
=> Fix interface ignore list

client/server/server.go
We should expire the device flow
info soon as we get a token with success.
=> Expire device flow info on success

management/server/account.go, management/server/account_test.go, management/server/file_store_test.go, management/server/mock_server/account_mock.go, management/server/peer_test.go, management/server/user.go
There are a few places where account is created.
When we create a new account, there should be 
some defaults set. E.g. created by and group ALL.
It makes sense to add it in one place to avoid inconsistencies.
=> Create account in 1 place

management/server/account.go, management/server/grpcserver.go, management/server/management_test.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer_test.go
Added the GetPeerNetwork method to account manager
Pass a copy of the network to the toPeerConfig function
to retrieve the netmask from the network instead of constant
updated methods and added test
=> Send netmask from account network

client/internal/connect.go, client/main.go, management/client/grpc.go, signal/client/grpc.go
The Management client will try reconnecting in case
of network issues or non-permanent errors.
If the device was offboarded, then the client will stop retrying.
=> Introduce larger retries for the agent

client/cmd/status.go, client/server/server.go
Always initialize the status recorder and utilize proto methods to get pbFullStatus values.
=> Always initialize status recorder

client/Dockerfile
Useful when SSH to client containers
=> Add PATH to client Dockerfile

client/internal/engine.go, client/internal/peer/conn.go, signal/client/grpc.go
Whenever a peer connection is restarted a new TURN
and STUN configs won't be applied. 
This leads to connection drops and agents won't 
reestablish a connection if TURN was the only
way.  The PR fixes this.
=> Fix TURN credentials renewal

encryption/letsencrypt.go, go.mod, go.sum, infrastructure_files/docker-compose.yml.tmpl, management/cmd/management.go, signal/client/grpc.go, signal/cmd/run.go
Right now Signal Service runs the Let'sEncrypt manager on port 80
and a gRPC server on port 10000. There are two separate listeners.
This PR combines these listeners into one with a cmux lib.
The gRPC server runs on either 443 with TLS or 80 without TLS.
Let's Encrypt manager always runs on port 80.
=> Make Signal Service listen on a standard 443/80 port instead of 10000

client/system/info_darwin.go
This prevents the client from needing to use command line tools
relates to #403
=> Use unix.Uname to get Darwin system info

.github/workflows/release.yml, .goreleaser.yaml, .goreleaser_ui.yaml
decouple goreleaser ui might help us
parallelize workflow and run local tests
dividing the release workflow for each goreleaser
and making trigger sign a different job them
when small issues with sign happen
=> Split goreleaser for UI and parallelized workflow

client/cmd/login.go, client/cmd/up.go, client/internal/config.go, client/internal/connect.go, client/internal/login.go, client/server/server.go
Relates to https://github.com/netbirdio/netbird/pull/400
All the existing agents by default connect to port 33073 of the
Management service. This value is also stored in the local config.
All the agents won't switch to the new port 443 
unless explicitly specified in the config.
We want the transition to be smooth for our users, therefore
this PR adds logic to check whether the old port 33073 can be 
changed to 443 and updates the config automatically.
=> Check and update Agent's Management URL if is legacy

management/cmd/management.go
When creating TLSConfig from provided certificate file, the HTTP/2 support is not enabled.
It works with Certmanager because it adds h2 support.
We can enable it the same way when creating TLSConfig from files:
```
NextProtos: []string{
"h2", "http/1.1", // enable HTTP/2
acme.ALPNProto, // enable tls-alpn ACME challenges
},
```  
Thanks to @kid-alan for pointing out the issue in https://github.com/netbirdio/netbird/issues/422
=> Enable HTTP/2 when loading TLS config from file

client/internal/engine.go, signal/client/grpc.go, signal/peer/peer.go, signal/peer/peer_test.go, signal/server/signal.go
This PR fixes a race condition that happens
when agents connect to a Signal stream, multiple 
times within a short amount of time. Common on 
slow and unstable internet connections.
Every time an agent establishes a new connection
to Signal, Signal creates a Stream and writes an entry 
to the registry of connected peers storing the stream.
Every time an agent disconnects, Signal removes the
stream from the registry. 
Due to unstable connections, the agent could detect 
a broken connection, and attempt to reconnect to Signal.
Signal will override the stream, but it might detect
the old broken connection later, causing peer deregistration.
It will deregister the peer leaving the client thinking 
it is still connected, rejecting any messages.
=> Fix Register/Deregister race on Signal

management/server/file_store.go, management/server/route.go
When checking for existing prefix routes
Return nil if peer is empty
=> Don't create index if peer is empty

client/internal/connect.go
Avoid management code import for the legacy port value, hardcoding it instead (it's literally spelled out in a comment below as well).
Fixes #436, saving around 9% disk space (go build -ldflags="-s -w" client/main.go: old: 16838656 bytes, new: 15253504 bytes, go 1.18.4 x86-86). This doesn't look much but it counts in embedded devices.
=> Avoid pulling in management code in client

go.mod, go.sum
when checking for rcS in the service lib, we should make sure that the service bin is not present, which indicates that sysV is the init system to be used
=> Fix service install when sysV service bin exists

.github/workflows/golang-test-linux.yml, client/internal/connect.go, client/internal/routemanager/nftables_linux.go, iface/iface_darwin.go, iface/iface_linux.go, iface/iface_windows.go, iface/mod_linux.go, iface/module_linux.go, iface/module_linux_test.go
Check if Wireguard and Tun modules are loaded
If modules are loaded return true, otherwise attempt to load them
Run client packages tests on docker containters
=> Improve module load

client/internal/routemanager/firewall_linux.go, client/internal/routemanager/iptables_linux.go, client/internal/routemanager/iptables_linux_test.go, client/internal/routemanager/nftables_linux.go, client/internal/routemanager/nftables_linux_test.go
add an income firewall rule for each routing pair the pair for the income rule has inverted source and destination
check if nftables rule exist before adding a new one
resolves #481
=> Add incoming routing rules

client/system/info_windows.go
Avoid problems with localization by retrieving
version information from registry
Return a default 0.0.0.0 if operation fails
=> Get windows version from registry

client/internal/routemanager/systemops.go, client/internal/routemanager/systemops_test.go
If the gateway address would be nil which is the case of macOS, we return the preferredSrc
added tests for getExistingRIBRouteGateway function
=> Return gateway address if not nil

client/ui/client_ui.go
the icon format is not really supported, so this uses a png instead.
this closes https://github.com/netbirdio/netbird/issues/534.
=> correctly set the windows application icon on windows

client/cmd/testutil.go, client/internal/engine_test.go, management/client/client_test.go, management/cmd/management.go, management/server/account_test.go, management/server/file_store.go, management/server/file_store_test.go, management/server/management_proto_test.go, management/server/management_test.go, management/server/nameserver_test.go, management/server/peer.go, management/server/route_test.go, management/server/store.go
Due to peer reconnects when restarting the Management service,
there are lots of SaveStore operations to update peer status.
Store.SavePeerStatus stores peer status separately and the
FileStore implementation stores it in memory.
=> Save Peer Status separately in the FileStore

client/internal/config.go
docker network address are assigned on interfaces with name `br-${NETWORK_ID[:12]}`, docker also creates interfaces that start with `veth` but does not assign IPv4 address to them.
I didn't find any docker documentation backing this but this should be easy to verify.
=> Fix docker network interface filter

management/server/peer.go
If a user has a non-admin role, display all peers
that user's peers have access to when calling
/peers endpoint of the HTTP API.
=> Display peers of a user that it has access to

client/internal/config.go, client/internal/connect.go, client/internal/engine.go, client/internal/peer/conn.go
- Enabled IPv6 address discovery, this allows clients to establish connection directly via IPv6 when available.
- Added a new config option `DisableIPv6Discovery` to revert the behavior back to IPv4 only. Default value is `false`, so existing config will default to using IPv6 when possible without user manually changing the config file.
Tested between my Windows 10 PC and a Raspberry Pi, using the hosted management and signal server (https://app.netbird.io/)
Closes #577
-----
Some notes:
Link-local IPv6 addresses (e.g. `fe80:*`) are filtered out, unlike IPv4 address (e.g. `10.0.4.3` is not filtered out).
I don't have a Unique local address so I don't know if that's also being filtered out. 
`ice.Candidate` with IPv6 host are formatted similar to `fe80::1:51820`, this only affects the log …
=> Enable IPv6 address discovery

client/internal/dns/server.go, client/internal/dns/server_test.go, client/internal/engine_test.go
We will probe a set of addresses and ports to define the one available for our DNS service
if none is available, we return an error
=> User custom loopback address

client/internal/connect.go, client/server/server.go
If peer is deleted in the console,
we set its state as needs login
On Down command, we clean any previous state errors. This prevents the need for a daemon restart
Removed state error wrapping when engine exits. The log is enough for this case.
Relates to #462
=> Handle peer deletion and state update

.goreleaser.yaml
These checks were part of our rebranding, and since then almost all peers got updated to newer netbird versions. So we are good to remove these and deal with any conflicts individually. 
Relates to #613
=> Remove wiretrustee conflict checks

management/server/http/middleware/handler.go
When there is no `X5c` we will use `N` and `E` fields of a JWK to generate the public RSA and a Pem certificate
Relates to #573 #427 #452
- [x ] Is it a bug fix
=> Generate validation certificate from mandatory JWK fields

client/internal/routemanager/client.go, client/internal/routemanager/manager.go, client/internal/routemanager/manager_test.go
It prevents Server from adding rules to route directly accessible/own networks through VPN when the route is in HA mode (has more than 1 entry):
1. the code was checking membership against a single Network Route entry with equality operator on `Peer` attribute:
1. there is 1 Route per Peer
2. second (HA) Route entry did not pass the check because it was not the server
3. rule for routing the traffic through VPN interface is created
4. host X is routing through host Y
5. host Y is routing through host X
6. (i assume) we have a routing loop passing packets back and forth between HA hosts instead of going to the real network
2. The code fixes above issue by checking `NetID` instead of `Peer` values
see the linked issue for more details
fixes: https://github.com/netbirdio/netbird/issues/598
=> HA Network Routes: prevent routing directly-accessible networks through VPN interface

infrastructure_files/docker-compose.yml.tmpl
Using the latest tag will align with the dashboard's new release cycle that relies on tags
=> Use latest tag for dashboard

client/internal/routemanager/client.go, client/internal/routemanager/manager.go, management/server/account.go, management/server/account_test.go, route/route.go
An additional check and filter for routes that are part of the same HA group where the peer is a routing peer
This relates to #612
=> Filter routes to sync from same HA group

client/internal/dns/network_manager_linux.go, client/internal/dns/server_test.go, client/internal/dns/systemd_linux.go
Prevent panic when the address is empty. Common with older managers, where the resolver is disabled by default as we receive an empty DNS config
=> Properly parse dns resolver address

management/cmd/root.go, management/server/account.go
Fix a single account mode issue with invalid domains. 
Where retrieving an account with invalid domains caused users to join separate accounts
=> Validate single account domain input

infrastructure_files/docker-compose.yml.tmpl
I added a `-c /etc/turnserver.conf` to the coturn command to specify the non-default config location, fixing #630
https://github.com/netbirdio/netbird/issues/630
=>  Coturn doesn't read the turnserver.conf when selfhosting netbird

.github/workflows/release.yml
This allows us to run clients on older macOS versions
=> Use macOS v11 to build UI release

management/Dockerfile
=> Install ca-certs in the Management docker image build

client/cmd/up.go
Add new --foreground-mode command line parameter
for 'up' cmd instead of existing log-file workaround
During debug the service, I am interested in output of the service. With this option it is easily configurable.
I tried to follow the current code style pattern, nevertheless I recommend to organize the content of the up.go into a new struct and register the upCmd into the cobra via a new function like this ```func registerUpCmd(rootCmd *cobra.Command)```. With it you can avoid global variables and ```init()``` functions.
=> Involve foreground mode switch for up cmd

management/server/activity/codes.go, management/server/dns.go
We should allow passing empty group slice for DisabledManagementGroups to reset any setting.
=> Allow empty groups for DNS setting

management/server/peer.go
Before, we assumed that the name should be changed and tried to generate another peer label without considering if there was a change to the name actually made.
=> Check if peer name change before update labels

.github/pull_request_template.md, management/server/account.go, management/server/account_test.go, management/server/dns.go, management/server/event.go, management/server/group.go, management/server/peer.go, management/server/rule.go, management/server/setupkey.go, management/server/setupkey_test.go, management/server/user.go
Use the generic `storeEvent()` funcion to store all activity events.
=> Simplify event storing with one generic method

management/server/account.go, management/server/account_test.go, management/server/dns_test.go, management/server/file_store.go, management/server/file_store_test.go, management/server/group.go, management/server/grpcserver.go, management/server/http/groups.go, management/server/http/groups_test.go, management/server/http/peers.go, management/server/http/routes.go, management/server/http/routes_test.go, management/server/metrics/selfhosted.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer_test.go, management/server/route.go, management/server/route_test.go, management/server/store.go, management/server/turncredentials.go, management/server/updatechannel.go, route/route.go
Replace Peer.Key as internal identifier with a randomly generated Peer.ID in the Management service.
Every group now references peers by ID instead of a public key.
Every route now references peers by ID instead of a public key.
FileStore does store.json file migration on startup by generating Peer.ID and replacing
all Peer.Key identifier references .
=> Use Peer.ID instead of Peer.Key as peer identifier

client/cmd/login.go, client/cmd/root.go, client/cmd/service_controller.go, client/cmd/testutil.go, client/cmd/up.go, client/internal/config.go, client/internal/config_test.go, client/internal/connect.go, client/server/server.go
We had an issue where the daemon service was overwriting the admin URL every time it was restarted. With the changes, we are making the default admin URL a concern of the config logic.
I've also reduced the number of input parameters for the New function in the daemon logic as it is only called after the service is installed, which kind brake the need for it to receive such inputs. 
Other changes:
- Avoid sending admin or management URLs on service start as it doesn't have an input
- Parse management and admin URL when needed
- Pass empty admin URL on commands to prevent default overwrite
=> Refactor Management and Admin URL config

management/server/account.go, management/server/file_store.go, management/server/grpcserver.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer_test.go
This PR adds a peer login expiration logic that requires 
peers created by a user to re-authenticate (re-login) after
a certain threshold of time (24h by default). 
The Account object now has a PeerLoginExpiration
property that indicates the duration after which a peer's
login will expire and a login will be required. Defaults to 24h.
There are two new properties added to the Peer object:
LastLogin that indicates the last time peer successfully used
the Login gRPC endpoint and LoginExpirationEnabled that 
enables/disables peer login expiration.
The login expiration logic applies only to peers that were created
by a user and not those that were added with a setup key.
_P.S. The expiration is disabled always for now. Will be enabled in the future versions.
Next PRs:
HTTP Peer API will have …
=> Add peer login expiration

client/internal/dns/file_linux.go, client/internal/dns/host.go, client/internal/dns/host_darwin.go, client/internal/dns/host_windows.go, client/internal/dns/mock_test.go, client/internal/dns/network_manager_linux.go, client/internal/dns/resolvconf_linux.go, client/internal/dns/server.go, client/internal/dns/server_test.go, client/internal/dns/systemd_linux.go, client/internal/dns/upstream.go, client/internal/dns/upstream_test.go
This change adds fallback to the host DNS default resolver when the upstream resolver fails several times.
It also reactivates the upstream resolver in 1 min and tries to use it again.
https://github.com/netbirdio/netbird/issues/620
=> Fix nameserver peer conn check

management/server/account.go, management/server/grpcserver.go, management/server/http/peers.go, management/server/mock_server/account_mock.go, management/server/peer.go
Extend [PeerStatus](https://github.com/netbirdio/netbird/blob/756ce96da96149c0c470993074997561fe8f3b9f/management/server/peer.go#L30) with an extra field LoginExpired that can be stored in the database.
=> Update peer status when login expires

management/server/account.go, management/server/account_test.go, management/server/activity/codes.go, management/server/http/accounts.go, management/server/http/accounts_test.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handler.go, management/server/mock_server/account_mock.go
Extend HTTP API with Account endpoints to configure global peer login expiration.
GET /api/accounts
PUT /api/account/{id}/ 
The GET endpoint returns an array of accounts with 
always one account in the list. No exceptions.
The PUT endpoint updates account settings:
PeerLoginExpiration and PeerLoginExpirationEnabled.
PeerLoginExpiration is a duration in seconds after which peers' logins will expire.
=> Add Account HTTP API

client/internal/peer/conn.go
In case if the wgctrl.New() return with err, should not close the 
resource.
=> Fix nil pointer exception in error handling

client/internal/config.go, client/internal/config_test.go
In config reader if the **input.PreSharedKey** is nil then the **GetConfig** 
throw nil pointer exception
=> Fix nil pointer exception in config parser

formatter/formatter.go, formatter/formatter_test.go, formatter/hook.go, formatter/hook_test.go, formatter/set.go, util/log.go
Add human readable log output. It print out the exact source code line information.
=> Log formatter

management/server/account.go, management/server/account_test.go, management/server/grpcserver.go, management/server/peer.go, management/server/peer_test.go, management/server/scheduler.go, management/server/scheduler_test.go, management/server/turncredentials.go, management/server/updatechannel.go
Goals:
- Enable peer login expiration when adding new peer
- Expire peer's login when the time comes
The account manager triggers peer expiration routine in future if the 
following conditions are true:
- peer expiration is enabled for the account
- there is at least one peer that has expiration enabled and is connected
The time of the next expiration check is based on the nearest peer expiration.
Account manager finds a peer with the oldest last login (auth) timestamp and
calculates the time when it has to run the routine as a sum of the configured
peer login expiration duration and the peer's last login time. 
When triggered, the expiration routine checks whether there are expired peers.
The management server closes the update channel of these peers and updates
network map of other …
=> Proactively expire peers' login per account 

management/server/file_store.go, management/server/file_store_test.go
When we delete a peer from an account, we save the account in the file store.
The file store maintains peerID -> accountID and peerKey -> accountID indices.
Those can't be updated when we delete a peer because the store saves the whole account
without a peer already and has no access to the removed peer.
In this PR, we dynamically check if there are stale indices when GetAccountByPeerPubKey 
and GetAccountByPeerID.
=> Remove stale peer indices when getting peer by key after removing

client/cmd/login.go, client/cmd/ssh.go, client/cmd/up.go, client/internal/config.go, client/internal/config_test.go, client/internal/connect.go, client/internal/device_auth.go, client/server/server.go
Code cleaning in the config.go of the client. This change keep the 
logic in original state. The name of the exported function was not 
covered well the internal workflow. Without read the comment was not 
understandable what is the difference between the GetConfig and 
ReadConfig. By the way both of them doing write operation.
=> Config cleaning

management/server/account.go, management/server/account_test.go, management/server/file_store.go, management/server/management_proto_test.go, management/server/testdata/store_with_expired_peers.json
Peers were considered expired and not sent to remote peers
when global expiration was disabled.
=> Use global login expiration setting when sending network map

management/server/file_store.go, management/server/file_store_test.go
Rego policy migration clears the rules property of the file storage, but it does not allow rollback management upgrade, so this changes pre-saves rules in the file store and updates it from the policies.
=> Don't drop Rules from file storage after migration to Policies

.goreleaser.yaml, .goreleaser_ui.yaml, .goreleaser_ui_darwin.yaml, client/cmd/status.go, client/cmd/status_test.go, client/cmd/version.go, client/internal/peer/conn.go, client/internal/routemanager/manager.go, client/server/server.go, client/system/info.go, client/system/info_darwin.go, client/system/info_freebsd.go, client/system/info_linux.go, client/system/info_windows.go, client/ui/client_ui.go, management/cmd/root.go, management/server/metrics/selfhosted.go, signal/client/client.go, signal/cmd/root.go, version/version.go
Add version command to signal and management servers.
The version information will be filled during build time.
=> Add version info command to signal server

client/cmd/up.go, client/internal/connect.go, client/internal/engine_test.go, client/internal/peer/conn_test.go, client/internal/peer/status.go, client/internal/peer/status_test.go, client/internal/routemanager/manager_test.go, client/server/server.go, management/client/grpc.go, signal/client/grpc.go
Fix the status indication in the client service. The status of the 
management server and the signal server was incorrect if the network 
connection was broken. Basically the status update was not used by 
the management and signal library.
=> Fix connstate indication

client/android/login.go, client/system/info_android.go, management/server/grpcserver.go
* Check SSO support by calling the internal.GetDeviceAuthorizationFlowInfo
* Rename LoginSaveConfigIfSSOSupported to SaveConfigIfSSOSupported
* Receive device name as input for setup-key login
* have a default android name when no context value is provided
* log non parsed errors from management registration calls
=> Adjustments for the change server flow

client/internal/peer/listener.go, client/internal/peer/notifier.go, client/internal/peer/status.go
Extend the status notification listeners with FQDN and address 
changes. It is required for mobile services.
=> Add fqdn and address for notification listener

iface/ipc_parser_android.go
update the query name to fix setting preshared key request
=> Fix pre-shared key query name for android wg configuration

.github/workflows/install-test-darwin.yml, .github/workflows/install-test-linux.yml, release_files/install.sh
This is a shell script that installs the Netbird applications (CLI and UI) on a Linux or macOS system.
The shell script is designed to work with various Linux operating systems, including but not limited to Ubuntu, Fedora, Debian, CentOS, Raspberry Pi OS, Arch Linux, Alpine Linux, etc. The supported architectures include amd64, arm64, and 386. It can also be used on Mac OS, both on Intel and Apple Silicon architectures.
- Detects for officially supported package managers (apt, dnf, yum, brew) and installs via the respective package manager.
- Installs appropriate binaries based on the system's architecture and operating system type if package manager is not supported.
- Skip netbird-ui installation for Linux systems that lack a desktop environment or for systems that have an unsupported …
=> Add single line installer

client/internal/connect.go
Nil pointer exception fix because handle error in wrong order
=> Fix nil pointer exception

client/internal/connect.go, client/internal/peer/notifier.go, client/internal/peer/notifier_test.go, management/client/grpc.go, signal/client/grpc.go
Refactored updateServerStates and calculateState
added some checks to ensure we are not sending connecting on context canceled
removed some state updates from the RunClient function
=> Update calculate server state

management/server/account.go, management/server/file_store.go, management/server/peer.go, management/server/peer_test.go
Rollback getPeersByACL usage in getNetworkMaps instead Rego queries.
=> Rollback simple ACL rules.

client/internal/stdnet/discover_mobile.go, client/internal/stdnet/discover_mobile_test.go
Ignore ipv6 labeled address.
Make no sense shows warning messages in log
=> Ignore ipv6 labeled address

management/server/user.go, management/server/user_test.go
The created_by filed for PATs was storing the the target user ID instead of the execution user ID. This way UI was always showing the owner as the creator.
=> Fix created_by field

management/cmd/management.go, management/cmd/root.go, management/server/config.go, management/server/grpcserver.go, management/server/jwtclaims/jwtValidator.go
Introduces a new flag `--idp-sign-key-refresh-enabled` that enables the Cache-Control header to be checked when fetching signing keys to determine the rotation period for signing keys. This feature will automatically refresh the signing key upon its expiry.
* Add support for rotating signing keys on expiry  ([#806][i806])
[i806]: https://github.com/netbirdio/netbird/issues/806
=> Add support for refreshing signing keys on expiry

management/server/account.go, management/server/http/middleware/access_control.go, management/server/mock_server/account_mock.go, management/server/user.go, management/server/user_test.go
The isAdmin function created accounts if a user does not belong to any account. THis logic was skipped during the auth refactor. Reverted the changes to the old isAdmin logic.
=> FIx account creation issue after auth refactor

client/cmd/login.go, client/cmd/up.go, client/internal/oauth.go
adds functionality to support Identity Provider (IdP) managers that do not support a complete verification URI in the device authentication flow. In cases where the `verification_uri_complete` field is empty, the user will be prompted with their `user_code`, and the `verification_uri ` field will be used as a fallback
* Azure application device flow not supported - ([#673](https://github.com/netbirdio/netbird/issues/673))
=> Fix incomplete verification URI issue in device auth flow

management/server/account.go
When checking cache, the list of users was not filtered for service user properly.
=> Fix cache lookup filter for service user

client/cmd/login.go, client/cmd/up.go
Fix preshared key command line arg handling
The cmd line arg processing does not differentiate the sting from the 
string pointer. So if the user does not set a preshared-key the code 
will overwrite it with empty string.
=> Fix preshared key command line arg handling

management/server/account.go, management/server/account_test.go, management/server/activity/codes.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handler.go, management/server/http/middleware/access_control.go, management/server/http/pat_handler_test.go, management/server/http/users_handler.go, management/server/http/users_handler_test.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/user.go, management/server/user_test.go
The new functionality allows to block a user in the Management service .
Blocked users loose access to the Dashboard, aren't able to modify network map,
and all of their connected devices disconnect and set to "login expired" state.
Technically all above achieved with the updated PUT /api/users endpoint,
that was extended with is_blocked field.
=> Block user through HTTP API

.goreleaser.yaml
MIPSLE 
This enables running netbird on edgerouter x devices, which have mipsle processors.
- new build target for netbird client
- Tested on edgerouter x
=> Add mipsle build to enable netbird for devices such as EdgeRouter X

client/internal/dns/file_linux.go, client/internal/dns/host.go, client/internal/dns/host_darwin.go, client/internal/dns/host_windows.go, client/internal/dns/network_manager_linux.go, client/internal/dns/resolvconf_linux.go, client/internal/dns/server_nonandroid.go, client/internal/dns/systemd_linux.go
Most host managers doesn't support using custom DNS ports. We are now disabling setting it up to avoid unwanted results
=> Prevent setting primary resolver if using custom DNS port

management/server/file_store.go, management/server/peer.go
We were saving the account even when there was no update to a peer's meta or expiration information
=> Avoid storing account if no peer meta or expiration change

client/main.go, iface/bind/udp_mux_universal.go
=> Clarify XORMapped panic case

client/server/server.go
in some cases an IDP device flow expiration time might be shorter than 90s we should check if the cancel context was set before using it
We will need a follow-up to identify and document the IDP with lower defaults.
fixes #890
=> Check if the cancel function was set before using it

go.mod, go.sum, iface/tun_windows.go
- wireguard/windows version update to 0.5.3
- follow up forked wireguard-go MTU related changes
- fix MTU settings on Windows
=> Windows MTU fix and wg/win version update

client/internal/dns/local.go, client/internal/dns/server_nonandroid.go, client/internal/dns/server_test.go, client/internal/dns/upstream.go, client/internal/dns/upstream_test.go
Retry, in an exponential interval, querying the upstream servers until it gets a positive response
=> Use backoff.retry to check if upstreams are responsive

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/groups_handler.go, management/server/http/peers_handler.go
During the development of api definition there needed to be a second version of the openapi document to parse into the docs. While we kept both versions there was a slight drift in their content. Merged both versions to only keep here and remove the duplicate from docs.
=> Remove drift between docs and openapi

client/cmd/down.go, client/cmd/login.go, client/cmd/root.go, client/cmd/service.go, client/cmd/service_controller.go, client/cmd/service_installer.go, client/cmd/ssh.go, client/cmd/status.go, client/cmd/up.go
The flags in the cli do not match the functionality of the different commands. We have flags set as global flags even tho they are disregarded completly e.g. 
```
service run -h
runs Netbird as service
Usage:
netbird service run [flags]
Flags:
-h, --help   help for run
Global Flags:
--admin-url string        Admin Panel URL [http|https]://[host]:[port] (default "https://app.netbird.io:443")
-c, --config string           Netbird config file location (default "/etc/netbird/config.json")
--daemon-addr string      Daemon service address to serve CLI requests [unix|tcp]://[path|host:port] (default "unix:///var/run/netbird.sock")
-n, --hostname string         Sets a custom hostname for the device
--log-file string         sets Netbird log path. If console is specified the the log will be output …
```
=> Configure CLI flags properly

management/server/network.go, management/server/network_test.go
Exclude the second last IP from allocation to use it in the Fake DNS
=> Exclude second last IP from allocation to use it in the Fake DNS

client/internal/acl/manager_create_linux.go
Use nftables by default on the Linux
=> Use by default nftables on the linux systems

client/internal/acl/manager.go, client/internal/acl/manager_test.go, client/internal/engine.go
Squash firewall "accept policy" rules by protocol type if they affect all peers in the network, and the network map doesn't contain any other rules for the same protocol with port definitions or drop policy.
=> Squash firewall rules by protocol if they affects all peers

client/internal/engine.go
Struct Engine has methods on both value and pointer receivers. 
Such usage is not recommended by the Go Documentation.
=> Struct Engine has methods on both value

release_files/darwin-ui-installer.sh, release_files/darwin_pkg/postinstall, release_files/darwin_pkg/preinstall
The pkg is able to upgrade to the newest version but the currently running instance of netbird-ui app is not closed. So to have a clean state adding pkill before upgrade.
Additionally adding service stop/uninstall to the brew installer to not show errors in case of upgrading.
=> Stop macOS app and service on update with pkg and brew

client/firewall/uspfilter/rule.go, client/firewall/uspfilter/uspfilter.go, client/firewall/uspfilter/uspfilter_test.go, client/internal/acl/manager.go, client/internal/acl/manager_test.go, client/internal/acl/mocks/iface_mapper.go, client/internal/dns/response_writer.go, client/internal/dns/response_writer_test.go, client/internal/dns/server_nonandroid.go, client/internal/dns/server_nonandroid_test.go, client/internal/dns/server_test.go, iface/device_wrapper.go, iface/device_wrapper_test.go, iface/iface.go, iface/mocks/README.md, iface/mocks/filter.go, iface/mocks/iface/mocks/filter.go
Add DNS packet catch hook.
Rename SetFiltering to SetFilter.
Add DNS response writer.
Handle userspace network in fake DNS server.
=> Feat fake dns address

client/internal/peer/status.go
Only send notifications when disconnected once, at peer's IP update.
=> Remove the number of status notifications on disconnected peers

client/internal/peer/status.go
This was affecting the behavior of the route manager, causing issues with HA and with cases of flaky connections.
=> Fix: Skip state notification should use a copy of the previous peer state

client/internal/engine.go, client/internal/peer/status.go, client/internal/peer/status_test.go
Reduce the peer status notifications
When receive new network map invoked multiple notifications for 
every single peers. It cause high cpu usage We handle the in a batch 
the peer notification in update network map.
- Remove the unnecessary **UpdatePeerFQDN** calls in **addNewPeer**
- Fix notification in **RemovePeer** function
- Involve **FinishPeerListModifications** logic
NB-284
=> Reduce the peer status notifications

client/firewall/port.go, client/internal/acl/manager.go, client/internal/acl/manager_test.go
Fix the issue with rule squashing, it contained an issue when calculating the total amount of IPs in the Peer map (doesn't include offline peers). That is why squashing did not work.
Also, this commit changes the rules apply behavior. Instead policy:
1. Apply all rules from the network map
2. Remove all previously applied rules.
We do:
1. Apply only new rules
2. Remove outdated rules
Why the first variant was implemented: when you have a drop policy it is important in which order your rules are and you need a totally clean previous state to apply the new. But in the release, we didn't include a drop policy so we can do this improvement.
=> ACL firewall manager fix/improvement

client/internal/dns/server.go, client/internal/dns/server_test.go
When DNS server runs in a fake resolver, there is an issue with incorrect handling disable state because we still receive updates from the management. Add extra checking and fix panic.
=> Fix disabled DNS resolver fail

iface/tun_windows.go
In Windows, instead, wrapped device (required by userspace filter and fake DNS) used raw device.
This fixes the DNS issue in Windows.
=> Fix use wrapped device in windows

client/cmd/ssh.go, client/ssh/server.go
The ssh connection was freezing when accessing amazon linux to nodes or if the username did not exist.
Changes:
- wait for terminal session to be ready to avoid freeze
- sending proper error codes to cli if failure
- sending log message on ssh session attempt
- ssh connections between Linux <-> Mac, Mac <-> Mac, Linux <-> Linux **(Either one or all cases)**
- test ssh connection to an Amazon Linux 2 machine
- test connection to offline peer
- test connection to non existing peer
- test connection to online peer but non existing user
https://github.com/netbirdio/netbird/issues/514
=> Fix ssh connection freeze

client/firewall/uspfilter/uspfilter.go, client/firewall/uspfilter/uspfilter_test.go
Switched rule set from array to map (as lookup table grouped by IP) to reduce number of rules checked for each packet when filtering) this way increasing throughput.
To test:
- throughput when thousands of rules active
- startup time when thousands of rules active
- memory consumption between old and new impl.
- functionality
=> Improve userspace filter performance

client/firewall/iptables/manager_linux.go, client/internal/routemanager/firewall_linux.go, client/internal/routemanager/iptables_linux.go
On machines where ip6tables was not available we would fail and throw an error without adding ip v4 routes. Whit this change the client can continue even though ip6tables is not available. 
https://github.com/netbirdio/netbird/issues/917
=> FIx error on ip6tables not available

client/firewall/firewall.go, client/firewall/iptables/manager_linux.go, client/firewall/iptables/manager_linux_test.go, client/firewall/nftables/manager_linux.go, client/firewall/nftables/manager_linux_test.go, client/firewall/nftables/rule_linux.go, client/firewall/nftables/ruleset_linux.go, client/firewall/nftables/ruleset_linux_test.go, client/firewall/uspfilter/uspfilter.go, client/firewall/uspfilter/uspfilter_test.go, client/internal/acl/manager.go, client/internal/acl/manager_create.go, client/internal/acl/manager_create_linux.go, management/server/policy.go, management/server/policy_test.go
Reduce rules count generated on the management side. Use sets on the client side for firewalls in kernel implementation
=> Optimize ACL performance

management/server/file_store.go
Both `TokenID2UserID` and `HashedPAT2TokenID` are in-memory indices and not stored in the file(`json:"-"` tag is being used).
This change should improve the performance of `DeletePAT` method in `DefaultAccountManager`.
=> Do not persist filestore when deleting indices

management/server/idp/okta.go
Addresses the following issues with the Okta IDP:
- Hiding Okta netbird attribute fields to ensure Okta doesn't enforce user input for these fields, as they are solely used by Netbird.
- Resolving the failing device authorization.
=> Fix Okta IDP device authorization

management/server/account_test.go, management/server/file_store.go
This pull request addresses an issue discovered while working on an alternative implementation of the Store module. The issue relates to the current behavior of the SaveAccount functionality, which allows creating an account with an empty ID and fails to validate if the indices are being repointed to another account.
To provide more context, the problem manifests in the following test cases:
1. The `newAccountWithId("", userId, domain)` function is called, resulting in an account with an admin user but an empty account ID.
2. Subsequently, `manager.GetAccountByUserOrAccountID(userId, initAccount.Id, domain)` is executed, which creates an account using the same function from the previous step, but this time providing an ID. This account is stored in FileStore.
3. Within the test cases, …
=> Fix DefaultAccountManager GetGroupsFromTheToken false positive tests

client/internal/dns/file_linux.go, client/internal/dns/host_darwin.go, client/internal/dns/resolvconf_linux.go, client/internal/dns/systemd_linux.go
Sometimes if the client is stopped forcefully the old DNS configuration was not restored. This was casuing nameresolution to fail because the netbird resolver was down. At the same time the netbird resolver could not start because it could not connect to management due to failing name resolution.
In this PR the netbird resolver was chnaged to keep the previous configured nameserver as fallback in case the netbird resolver is not resopnding.
=> Keep confiured nameservers as fallback

client/internal/dns/systemd_linux.go
The latest PR about adding the systems DNS as fallback is causing issues for systemd and needs to be reverted for the time beeing.
=> Revert changes for systemd

client/internal/peer/notifier.go, client/internal/peer/status.go
In case of alway-on start the peer list was invalid on Android UI.
=> After add listener automatically trigger peer list change event

management/server/http/api/openapi.yml, management/server/http/setupkeys_handler.go, management/server/http/setupkeys_handler_test.go
So far we accepted any value for setup keys, including negative values
Now we are checking if it is less than 1 day or greater than 365 days
https://github.com/netbirdio/dashboard/issues/251
=> Validate input of expiration time for setup-keys

infrastructure_files/getting-started-with-zitadel.sh
=> Fix input reading for NetBird domain in getting-started-with-zitadel.sh

client/internal/routemanager/firewall_linux.go, client/internal/routemanager/firewall_nonlinux.go, client/internal/routemanager/iptables_linux.go, client/internal/routemanager/iptables_linux_test.go, client/internal/routemanager/manager.go, client/internal/routemanager/manager_test.go, client/internal/routemanager/server.go, client/internal/routemanager/server_android.go, client/internal/routemanager/server_nonandroid.go, client/internal/stdnet/filter.go, go.mod, go.sum
In case the route management feature is not supported then do not create unnecessary firewall and manager instances. This can happen if the nftables nor iptables is not available on the host OS.
- Move the error handling to upper layer
- Remove fake, useless implementations of interfaces
- Update go-iptables because In Docker the old version can not determine well the path of executable file
=> Routemgr error handling

client/Dockerfile
Update client Dockerfile to use Alpine as base image and install necessary packages to run iptables firewall manager
=> Update client Dockerfile to use Alpine as base image

management/server/nameserver.go, management/server/nameserver_test.go
Add domain validation for nameserver groups.
* Validate match domains input  ([#245][i245])
[i245]: https://github.com/netbirdio/dashboard/issues/245
=> Add domain validation for nameserver groups

management/server/account.go, management/server/account_test.go, management/server/user.go
For peer propagation this commit triggers
network map update in two cases:
1) peer login
2) user AutoGroups update
Also it issues new activity message about new user group for peer login process.
=> Send network update when propagate user auto-groups

management/server/account.go, management/server/activity/codes.go, management/server/file_store.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/users_handler.go, management/server/jwtclaims/claims.go, management/server/jwtclaims/extractor.go, management/server/jwtclaims/extractor_test.go, management/server/store.go, management/server/updatechannel.go, management/server/user.go, management/server/user_test.go
For better auditing this PR adds a dashboard login event to the management service.
For that the user object was extended with a field for last login that is not actively saved to the database but kept in memory until next write. The information about the last login can be extracted from the JWT claims `nb_last_login`. This timestamp will be stored and compared on each API request. If the value changes we generate an event to inform about a login.
=> Adding dashboard login activity

client/firewall/iptables/manager_linux.go, client/firewall/uspfilter/allow_netbird.go, client/firewall/uspfilter/allow_netbird_linux.go, client/firewall/uspfilter/uspfilter.go, client/internal/acl/manager.go, client/internal/acl/manager_create.go, client/internal/acl/manager_create_linux.go, client/internal/acl/manager_test.go
Enable netbird traffic through uspfilter on Linux systems
Issue:
While every firewall manager has an AllowNetbird method,
uspfilter doesn't utilize it on Linux due to the need
for system firewall traffic control.
Solution:
On Linux, we now attempt to initialize either nftables
or iptables within the ACL manager. We then invoke the
AllowNetbird method for the chosen firewall. If userspace
implementation is being used, the firewall manager is
subsequently recreated as a uspfilter instance.
=> Enable netbird traffic through uspfilter on Linux systems

dns/nameserver.go, management/server/account_test.go, management/server/group.go, management/server/http/nameservers_handler_test.go, management/server/peer.go, management/server/personal_access_token.go, management/server/policy.go, management/server/rule.go, management/server/setupkey.go, management/server/user.go, route/route.go
With this fix, all nested slices and pointers will be copied by value. 
Also, this fixes tests to compare the original and copy account by their values by marshaling them to JSON strings.
Before that, they were copying the pointers that also passed the simple `=` compassion (as the addresses match).
=> Improve account copying

client/cmd/login.go, client/internal/auth/pkce_flow.go
Addresses the issue of an open listening port persisting after the PKCE authorization flow is completed.
=> Close PKCE Listening Port After Authorization

management/server/http/handler.go, management/server/http/middleware/auth_middleware.go, management/server/http/middleware/auth_middleware_test.go
The API authentication with PATs was not considering different userIDClaim that some of the IdPs are using. 
In this PR we read the userIDClaim from the config file instead of using the fixed default and only keep it as a fallback if none in defined.
https://github.com/netbirdio/netbird/issues/1119
=> Fix API auth using PATs with different userIDClaims

.github/workflows/release.yml, client/netbird.wxs, infrastructure_files/configure.sh
This adds a basic wxs file to build MSI installer
This file was created using docs from https://wixtoolset.org/docs/schema/wxs/ and examples from [gsudo](https://github.com/gerardog/gsudo/blob/eb6788844839558082bd7ebff4ea4e9cfbdb6bf6/src/gsudo.Installer/Product.wxs),  [qemu-shoggoth](https://github.com/cromulencellc/qemu-shoggoth/blob/16224789f559e98d6dc12f1b567af2f6ab29d68d/qga/installer/qemu-ga.wxs#), and many others.
=> Add Wix file for MSI builds

infrastructure_files/getting-started-with-zitadel.sh
This pull-request add/changes the HTTP headers to include safe defaults to Caddy and get the A+ score on the https://observatory.mozilla.org/ test
=> Add safe security headers to improve the security

infrastructure_files/docker-compose.yml.tmpl
Use NETBIRD_SIGNAL_PORT variable instead of the static port for signal container in the docker-compose template to make setting of custom signal port working
trying to use custom signal port I saw it was not working and signal container still use the default one.
after a fast look to commit that implement it and comparing with other variable for custom port working I found the missing in docker template that still have the static port to default.
This patch add the use of variable instead of the static port.
From a test seems now working correctly with custom port.
=> fix NETBIRD_SIGNAL_PORT not working with custom port

management/server/http/util/util.go, management/server/idp/zitadel.go
With previous release we broke the parameters' endpoint. This Pr reverses that
=> Revert zitadel update parameters endpoint

management/server/grpcserver.go, management/server/telemetry/grpc_metrics.go
This should help to find better value for `server.channelBufferSize`
=> Add management_grpc_updatechannel_queue_bucket histogram

management/cmd/management.go
This PR aims to avoid write operations of the config file if the datastore key is already present.
https://github.com/netbirdio/netbird/issues/1175
=> Avoid writing config if datastore key exists

management/server/account.go
As we do double-read of the account we don't global lock. Account lock should be enough here.
=> Remove unnecessary global lock

management/server/telemetry/store_metrics.go
As the current upper 10000 microseconds(10ms) bucket may be to low for `management.store.persistence.duration` metric
=> Expose store metrics with milliseconds bucketing

client/internal/auth/util.go
The use of reflection should generally be minimized in Go code because it can make the code less readable, less type-safe, and potentially slower.
In this particular case we can simply rely on type switch.
=> Reimplement isValidAccessToken without reflect package

management/server/account.go
If there is a difference between local and cached data, we trigger a cache refresh; as we remove users from the local store and potentially from the remote IDP, we need to switch the source of truth to the local store to prevent unwanted endless cache for cases where the removal from the IDP fails or for cases where the userDeleteFromIDPEnabled got enabled after the first user deletion.
This also aligns with the change in the warmup method in PR #1147
=> Prevent return extra userData

management/server/account.go, management/server/account_test.go, management/server/group.go, management/server/http/groups_handler_test.go, management/server/http/routes_handler_test.go, management/server/mock_server/account_mock.go, management/server/peer.go
- Remove unused am.AccountExists
- Remove unused am.GetPeerByKey
- Remove unused am.GetPeerByIP and account.GetPeerByIP
- Remove unused am.GroupListPeers
=> Account Manager code cleanup

client/ui/build-ui-linux.sh, client/ui/client_ui.go
On Linux desktops we need to pass a flag to daemon indicating 
that this is a Desktop environment.
Without it the Device flow always triggered instead of PCKE.
=> Always call Login from UI with the desktop flag

management/server/account.go, management/server/file_store.go, management/server/http/peers_handler.go, management/server/http/peers_handler_test.go, management/server/mock_server/account_mock.go
With this change, we don't need to update all peers on startup. We will check the existence of an update channel when returning a list or single peer on API. Then after restarting of server consumers of API will see the peer not connected status till the creation of an updated channel which indicates the peer's successful connection.
=> Rework peer connection status based on the update channel existence

management/server/account.go, management/server/account_test.go, management/server/dns.go, management/server/dns_test.go, management/server/http/dns_settings_handler_test.go
Fix group delete panic
In case if in the db the DNSSettings is null then can cause panic in delete group function 
because this field is pointer and it was not checked. Because of in the future implementation 
this variable will be filled in any case then make no sense to keep the pointer type.
Fix DNSSettings copy function
=> Fix nil pointer exception in group delete

CONTRIBUTING.md
=> Update contribution guide with go version and Windows driver

management/client/grpc.go, signal/client/grpc.go
Some reverse proxies might find 15s interval too short and respond with an enhance your-calm message:
```
2023/10/14 12:14:15 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
```
This change is setting the management and signal clients' keepalive interval to 30 seconds to minimize the number of reconnections
=> Update grpc clients' keepalive interval

release_files/install.sh
For installations using the binary release method (using the official installer script), it would be nice to be able to define a specific version to install.
A user/developer can choose to define the `NETBIRD_RELEASE` variable during installation, to pin a specific version during installation. 
If `NETBIRD_RELEASE` is not defined, we default to the current behavior of `latest`
```
export SKIP_UI_APP=true; export NETBIRD_RELEASE=v0.23.7; curl https://pkgs.netbird.io/install.sh | sh
```
=> Support pinning version during binary install

client/firewall/uspfilter/allow_netbird_windows.go, client/internal/acl/manager_create.go
The no rules matched message is operating system language specific, and can cause errors
Now we check if firewall is reachable by the app and then if the rule is returned or not in two different calls:
isWindowsFirewallReachable
isFirewallRuleActive
Fixes # 1249
=> Fix Windows firewall message check

management/server/group.go
=> Add integration reference field to group

.codespellignore, .github/workflows/golangci-lint.yml, client/internal/acl/manager_test.go, client/internal/dns/server_test.go, client/internal/ebpf/ebpf/manager_linux_test.go, client/internal/peer/conn.go, client/ssh/util.go, dns/dns.go, iface/tun_adapter.go, infrastructure_files/configure.sh, infrastructure_files/getting-started-with-zitadel.sh, infrastructure_files/turnserver.conf.tmpl, management/server/account_test.go, management/server/jwtclaims/extractor_test.go, sharedsock/sock_linux.go, signal/client/grpc.go
=> Add codespell job

management/server/account.go, management/server/dns.go, management/server/event.go, management/server/group.go, management/server/mock_server/account_mock.go, management/server/nameserver.go, management/server/peer.go, management/server/policy.go, management/server/route.go, management/server/setupkey.go, management/server/user.go
Enhancing the accessibility of the Account Manager events store by making it available for other packages.
=> Export account manager events store

management/server/account.go, management/server/mock_server/account_mock.go, management/server/user.go, management/server/user_test.go
=> Extend AccountManager with external cache and group/user management methods

management/server/user.go
This should not happen via an API but be possible when calling the method directly.
=> Allow to update IntegrationReference for user

management/server/peer.go
Starting from iOS 16, it is not possible, to get the hostname from the device and only returns "iPhone". Therefore all devices will have the same name and the dns will be counted upwards (e.g. iphone-3.netbird.cloud). This PR adds a lookup on peer registration to get the email address of a user registering that device and adds it to the device name to allow easier differentiation. If the lookup fails or the device was added via setup key it will fall back to the default "iPhone" name.
=> Use email address for iphone name generation

client/cmd/testutil.go, client/internal/engine_test.go, management/client/client_test.go, management/cmd/management.go, management/server/account_test.go, management/server/dns_test.go, management/server/management_proto_test.go, management/server/management_test.go, management/server/nameserver_test.go, management/server/route_test.go, management/server/telemetry/app_metrics.go, management/server/telemetry/store_metrics.go, management/server/telemetry/updatechannel_metrics.go, management/server/turncredentials_test.go, management/server/updatechannel.go, management/server/updatechannel_test.go
With this change we should be able to collect and expose the following histograms:
* `management.updatechannel.create.duration.ms`  with `closed` boolean label
* `management.updatechannel.create.duration.micro` with `closed` boolean label
* `management.updatechannel.close.one.duration.ms`
* `management.updatechannel.close.one.duration.micro`
* `management.updatechannel.close.multiple.duration.ms`
* `management.updatechannel.close.multiple.duration.micro`
* `management.updatechannel.close.multiple.channels`
* `management.updatechannel.send.duration.ms` with `found` and `dropped` boolean labels
* `management.updatechannel.send.duration.micro` with `found` and `dropped` boolean labels
* `management.updatechannel.get.all.duration.ms`
* `management.updatechannel.get.all.duration.micro`
* …
=> Add metrics for PeersUpdateManager

management/server/user.go
The change ensures that the deletion operation is skipped when the user does not exist in the Identity Provider. This is particularly beneficial in scenarios where a user account was provisioned but the user did not sign in, preventing unnecessary deletions from the IdP.
=> Optimize IdP user deletion

.golangci.yaml, client/internal/dns/server_test.go
Tenv is analyzer that detects using `os.Setenv` instead of `t.Setenv` since Go 1.17.
=> Add tenv linter

release_files/systemd/env, release_files/systemd/netbird-management.service, release_files/systemd/netbird-signal.service, release_files/systemd/netbird@.service
---
Continuing from #1316.
I did not change `install.sh` yet as this PR uses a templated systemd unit for the client, and thus `install.sh` will need a bit of work to make it safely migrate old clients. I'd like to know first if you want this at all.
Logs get written to the console where they get picked up by journald, since this is where you would typically expect to see them on a systemd-based Linux distribution. Users get automatic compression and log rotation for free.
It's trivial to make each client use a separate log file if you'd rather keep using text logs, though.
Sandbox flags are quite conservative: they mostly deny access to home directories and things netbird shouldn't have to worry about (like changing mount points).
It isn't difficult to make all daemons *appear* to work …
=> systemd units for the client, management & signal services

client/internal/routemanager/client.go, client/internal/routemanager/manager.go, client/internal/routemanager/systemops_bsd.go, client/internal/routemanager/systemops_linux.go, client/internal/routemanager/systemops_nonandroid.go, client/internal/routemanager/systemops_nonandroid_test.go, client/internal/routemanager/systemops_nonlinux.go, client/internal/routemanager/systemops_windows.go
Most operating systems add a /32 route for the default gateway address to its routing table
This will allow routes to be configured into the system even when the incoming range contains the default gateway.
In case a range is a sub-range of an existing route and this range happens to contain the default gateway it attempts to create a default gateway route to prevent loop issues
#840
=> Remove the gateway check for routes

management/server/http/peers_handler.go
Building a group minimum response was using the wrong operator.
fixes #1336
=> Fix group membership for peers API response

management/server/account.go, management/server/http/peers_handler.go, management/server/http/peers_handler_test.go, management/server/mock_server/account_mock.go, management/server/telemetry/updatechannel_metrics.go, management/server/updatechannel.go
Instead of GetAllConnectedPeers that needs to traverse the whole connections map to find one channel there.
This also removes update channel manager metrics with ms time unit as micro should be enough.
=> Implement lightweight method to check is peer has update channel

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> Update API descriptions and examples

management/cmd/management.go, management/cmd/root.go, management/server/jwtclaims/jwtValidator.go
Ensure the jwks expiresInTime is not zero and add a log indicating the new expiration time
Replace the configuration property only when the flag is being used
fixes #1379
=> Fix jwks validation and flag/config overriding

management/server/policy.go
Fix nil handling in getAllPeersFromGroups to not include nil pointer in the output.
=> Fix nil pointer handling in get peers from group

client/cmd/status.go
users can filter status based on peer fully qualified names.
e.g., netbird status -d --filter-by-names peer-a.netbird.cloud,peer-b.netbird.cloud
Enable detailed information when using just filter flags.
=> Support status filter by names

client/cmd/login.go, client/cmd/root.go, client/cmd/up.go, client/internal/config.go, client/internal/config_test.go
The goal was to be able to remove a preshared key by setting it to empty string.
The changes needed to be able to hande the usecase described in https://github.com/netbirdio/netbird/issues/887.
=> Allow removal of preshared keys

client/Dockerfile
Changing the docker base image to use version 1.8.9 of iptables.
=> Change docker base image

infrastructure_files/getting-started-with-zitadel.sh
This merge request addresses an issue where a port mapping in the management.json configuration generated by `getting-started-with-zitadel.sh` forces the generation of an access token with a different issuer. As a consequence, Zitadel rejects the access token as invalid.
- #1395
=> Fix quickstart script incompatibility with latest Zitadel version

management/server/account.go, management/server/user.go
Some IdPs might have eventual consistency for their API calls, and refreshing the cache with its data may return the deleted user as part of the account
Introduce a new account manager method, removeUserFromCache, to remove the user from the local cache without refresh
=> Remove the user from the cache without refreshing it

client/system/info_windows.go
Before, netbird would exit and prevent the agent from starting if getting the system name using WMI was an issue.
This change returns a default value in this case
#1418
=> Fix Windows name on WMI error

.github/workflows/release.yml, CONTRIBUTING.md, client/installer.nsis, client/netbird.wxs
By copying the emulator driver next to our binary, our GUI setting popup works on remote desktop connections
the dll is added as part of our sign pipelines workflow
#986 #1189
=> Fix Windows settings popup with mesa 3d openGL emulator

management/server/peer.go, management/server/user.go
Prior to this update, the user's last login was only updated on the dashboard authentication
=> Update user's last login when authenticating a peer

client/ios/NetBirdSDK/login.go
The SSO check on iOS fails if the management runs an older version that does not include PKCE yet.
=> Allow iOS to connect to old management versions

.github/workflows/android-build-validation.yml, client/firewall/nftables/acl_linux.go, client/firewall/nftables/manager_linux.go, client/firewall/nftables/manager_linux_test.go, client/internal/acl/manager_test.go, iface/tun_usp_linux.go
Add default allow rules for input and output chains.
=> Fix allow netbird traffic for nftables and userspace

.github/workflows/android-build-validation.yml
=> Update Android build env

management/server/account.go
Group updates to user auto groups will propagate by default for new accounts
=> Enable group propagation by default

management/server/account.go, management/server/group.go, management/server/mock_server/account_mock.go, util/common.go
This PR extends the account manager to be able to look up a group by its name.
=> Add getGroupByName method

management/server/account.go
This PR fixes the issue that caused JWT group membership not to be stored, therefore causing many event logs and inconsistency.
#1470
=> Fix race condition with JWT group sync

client/internal/dns/local.go, client/internal/dns/mock_server.go, client/internal/dns/server.go, client/internal/dns/upstream.go, client/internal/dns/upstream_ios.go, client/internal/dns/upstream_nonios.go, client/internal/dns/upstream_test.go, client/internal/engine.go
This adds an availability check for each DNS server group right after receiving DNS updates from management. 
If no servers of a group are available the group will be disabled.
When we receive an upstream DNS server, we add the address in the system without checking if the address is reachable; this may cause issues as some queries will fail and may delay peer connection if the domains served by the upstream might contain our management layer.
=> Validate upstream reachability on first DNS configuration

client/internal/dns/file_linux.go, client/internal/dns/file_linux_test.go, client/internal/dns/file_parser_linux.go, client/internal/dns/file_parser_linux_test.go, client/internal/dns/file_repair_linux.go, client/internal/dns/file_repair_linux_test.go, client/internal/dns/host_linux.go, client/internal/dns/resolvconf_linux.go, go.mod, go.sum
In the case of disabled stub listeren the list of name servers is unordered. The solution is to configure the resolv.conf file directly instead of dbus API.
Because third-party services also can manipulate the DNS settings the agent watch the resolv.conf file and keep it up to date.
- apply file type DNS manager if in the name server list does not exist the 127.0.0.53 address
- watching the resolv.conf file with inotify service and overwrite all the time if the configuration has changed and it invalid
- fix resolv.conf generation algorithm
=> Support disabled resolved stub server mode

management/server/account.go, management/server/account_test.go, management/server/dns.go, management/server/event.go, management/server/http/accounts_handler.go, management/server/http/nameservers_handler.go, management/server/http/nameservers_handler_test.go, management/server/mock_server/account_mock.go, management/server/nameserver.go, management/server/nameserver_test.go, management/server/peer.go, management/server/policy.go, management/server/route.go, management/server/setupkey.go, management/server/setupkey_test.go, management/server/user.go, management/server/user_test.go
We allow service users with user role read-only access to all resources so users can create service user and propagate PATs without having to give full admin permissions.
=> Allow service users with user role read-only access to all resources

.github/ISSUE_TEMPLATE/bug-issue-report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Update bug-issue-report and feature request templates

encryption/letsencrypt.go, management/cmd/management.go
Uses proper permissions to create dirs. `os.ModeDir` creates a directory with no bits set
=> Fix data dir creation permissions

client/internal/dns/file_parser_linux_test.go, client/internal/dns/file_repair_linux.go, client/internal/dns/upstream.go, client/internal/dns/upstream_ios.go, client/internal/dns/upstream_nonios.go, client/internal/dns/upstream_test.go
=> Fix iOS DNS timeout

client/cmd/service_controller.go, client/internal/connect.go, client/internal/dns/dbus_linux.go, client/internal/dns/file_linux.go, client/internal/dns/host.go, client/internal/dns/host_android.go, client/internal/dns/host_darwin.go, client/internal/dns/host_ios.go, client/internal/dns/host_linux.go, client/internal/dns/host_windows.go, client/internal/dns/local.go, client/internal/dns/network_manager_linux.go, client/internal/dns/resolvconf_linux.go, client/internal/dns/response_writer.go, client/internal/dns/server.go, client/internal/dns/server_android.go, client/internal/dns/server_darwin.go, client/internal/dns/server_linux.go, client/internal/dns/service_listener.go, client/internal/dns/service_memory.go, client/internal/dns/systemd_linux.go, client/internal/dns/unclean_shutdown_android.go, client/internal/dns/unclean_shutdown_darwin.go, client/internal/dns/unclean_shutdown_ios.go, client/internal/dns/unclean_shutdown_linux.go, client/internal/dns/unclean_shutdown_windows.go, client/internal/dns/upstream.go, client/internal/engine.go, iface/iface_linux.go
1. When the Netbird agent terminates ungracefully (kill, power outage, panic, etc.), the system DNS settings are not restored.
This can result in broken DNS resolution (e.g. a DNS server provided by a peer), in which case the agent won't be able to connect to the management server.
To fix this issue we create an indicator file after adjusting the system DNS settings.
This file is deleted once the settings are restored.
If the agent terminates ungracefully it won't be able to delete this file. Therefore when it is started again it will detect the existence of this file and restore the previous DNS state.
- On Linux
`/var/lib/netbird/resolv.conf`, contains the old `/etc/resolv.conf`
`/var/lib/netbird/manager`, contains the name of the previous host manager and last netbird IP address
- …
=> Restore dns on unclean shutdown

client/internal/dns/service_listener.go
it was worrying to see multiple warnings and no success message when lacking CAP_NET_BIND_SERVICE
=> getFirstListenerAvailable(): adjust logging levels and add success message

go.mod, go.sum, management/cmd/management.go, management/server/config.go, management/server/grpcserver.go
Otherwise, get it from the GRPC peer address.
This PR extends management config with a new `TrustedHTTPProxies` option that accepts a list of network prefixes ex: `"192.168.1.1/32", "10.0.0.0/16"` that is used for evaluation of client real ip according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address
=> Extract peer real IP from Load Balancer when possible

client/internal/dns/service_listener.go, client/internal/ebpf/ebpf/dns_fwd_linux.go, client/internal/ebpf/ebpf/src/readme.md
Ensure we use WG address instead of loopback addresses for eBPF.
- First try to use 53 port
- Try to use 5053 port on WG interface for eBPF
- Try to use 5053 on WG interface or loopback interface
=> Update port, ip choice logic in DNS service

management/cmd/management.go, management/server/account.go, management/server/account_test.go, management/server/file_store.go, management/server/file_store_test.go, management/server/geolocation/geolocation.go, management/server/geolocation/geolocation_test.go, management/server/grpcserver.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/peers_handler.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer/peer.go, management/server/posture/geo_location.go, management/server/posture/geo_location_test.go, management/server/sqlite_store.go, management/server/sqlite_store_test.go, management/server/store.go
This PR uses the geolocation service to resolve IP to location. The lookup happens once on the first connection - when a client calls the Sync procedure.
The location is stored as part of the peer:
```go
type Location struct {
ConnectionIP net.IP 
CountryCode  string
CityName     string
GeoNameID    uint 
}
```
=> Extend peer meta with location information

management/server/account.go, management/server/user.go
In some cases, when the refresh cache fails, we should try to get the cache from the external cache obj.
This may happen if the IDP is not responsive between storing metadata and refreshing the cache
=> Get cache from external cache when refresh fails

management/server/posture/geo_location.go, management/server/posture/geo_location_test.go
=> Deny peer without location when evaluate geo check

management/server/account_test.go, management/server/http/posture_checks_handler.go, management/server/http/posture_checks_handler_test.go, management/server/policy.go, management/server/policy_test.go, management/server/posture/checks.go, management/server/posture/checks_test.go, management/server/sqlite_store.go
As the possible set of check definitions is known, we can be less abstract about the serialization.
=> Simplify checks definition serialisation

management/server/account.go
=> Properly handle cache error and return userdata

management/server/http/api/openapi.yml, management/server/nameserver.go, management/server/nameserver_test.go
Allows administrators to add a third nameserver configuration. 
Dashboard PR: https://github.com/netbirdio/dashboard/pull/337
=> Allow adding 3 nameserver addresses

management/server/account.go, management/server/account_test.go, management/server/file_store.go, management/server/file_store_test.go, management/server/policy_test.go, management/server/rule.go, management/server/sqlite_store.go
This PR removes all usage of `Account.Rules` in the management. We still keep the endpoint that translates rules to policies and the other way around.
> The users with management on version < [v0.15.3](https://github.com/netbirdio/netbird/releases/tag/v0.15.3) should first upgrade their systems to [v0.25.8](https://github.com/netbirdio/netbird/releases/tag/v0.25.8), run management to properly migrate rules to policies, and then upgrade to **0.26.0+**.
=> Remove Account.Rules from Store engines

management/server/geolocation/geolocation.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/geolocations_handler.go, management/server/http/handler.go, management/server/http/peers_handler.go, management/server/http/posture_checks_handler.go, management/server/posture/checks.go, management/server/posture/checks_test.go, management/server/posture_checks.go
=> Enhance the management of posture checks

management/server/store.go
=> Use SQLite store as default when running tests when env is not set

management/server/http/middleware/auth_middleware_test.go, management/server/http/middleware/bypass/bypass.go, management/server/http/middleware/bypass/bypass_test.go
=> Extend bypass middleware with support of wildcard paths

management/server/account.go
The settings validation was moved behind the user permission check to avoid unnecessary validation in case the user is not allowed to update the settings anyway.
=> FIx order when validating account settings

.github/workflows/test-infrastructure-files.yml, management/server/geolocation/database.go
Resolve the issue of a cross-device link error when transferring geolocation databases to the management datadir, which is mounted on Docker.
=> Fix invalid cross-device link when moving geolocation databases

management/server/http/api/openapi.yml
Because the new parser for some reason can not handle the exampls for timestamp without quotes this PR adds quotes to all timestamp examples.
=> Add quotes to timestamp examples in openapi spec 

management/cmd/management.go, signal/cmd/run.go
Output log version at service startup. e.g.:
```
2024-02-29T14:52:33+01:00 INFO management/cmd/management.go:319: management server version 0.26.2
2024-02-29T14:52:33+01:00 INFO management/cmd/management.go:320: running HTTP server and gRPC server on the same port: [::]:3001
```
=> Log version when starting management and signal

management/server/scheduler.go, management/server/scheduler_test.go
Using time.Ticker allows us to avoid recursive calls that may end up in schedule running and possible deadlock if no routine is listening for cancel calls
switch to closing channel
=> Handle canceling schedule and avoid recursive call

client/system/info_windows.go
this handles virtualized systems without Win32_ComputerSystemProduct entries by returning 'unknown' for system product name
n/a
=> Do not fail on virtualized windows systems

management/server/account.go
using the login expired issue could cause problems with the ticker used in the scheduler
This change makes 1s the minimum number returned when rescheduling the peer expiration task
=> Return 1s when next expiration is too low

management/server/sqlite_store.go, management/server/sqlite_store_test.go
This change returns status.NotFound only on gorm.ErrRecordNotFound and status.Internal on every other DB error
=> Check for record not found when searching the store

client/server/server.go, client/server/server_test.go
This change adds a fallback retry to the daemon service
this retry has a larger interval with a shorter max retry run time
=> Add fallback retry to daemon

client/cmd/root.go, client/cmd/service.go
allows telling CLI what is the service name to control (for multi-instance deployments)
separated out of https://github.com/netbirdio/netbird/pull/1586
=> add --service/-s flag for specifying system service name

client/internal/dns/server.go, client/internal/engine.go
moved the e.dnsServer.ProbeAvailability() to run after ACL apply filtering
run the probes in parallel
fixes #1704
=> Unblock ACL apply filtering because of dns probes

client/cmd/testutil.go, client/internal/engine_test.go, client/server/server_test.go, management/client/client_test.go, management/server/http/peers_handler_test.go, management/server/management_proto_test.go, management/server/management_test.go, management/server/nameserver_test.go, management/server/route_test.go
This should reduce the number of lines like:
```shell
2024-03-17T20:07:19.2357150Z time="2024-03-17T20:07:01Z" level=error msg="no dns domain is set, returning empty zone"
2024-03-17T20:07:19.2358679Z time="2024-03-17T20:07:01Z" level=error msg="no dns domain is set, returning empty zone"
2024-03-17T20:07:19.2360189Z time="2024-03-17T20:07:01Z" level=error msg="no dns domain is set, returning empty zone"
2024-03-17T20:07:19.2361706Z time="2024-03-17T20:07:01Z" level=error msg="no dns domain is set, returning empty zone"
2024-03-17T20:07:19.2363215Z time="2024-03-17T20:07:01Z" level=error msg="no dns domain is set, returning empty zone"
2024-03-17T20:07:19.2364841Z time="2024-03-17T20:07:01Z" level=error msg="no dns domain is set, returning empty zone"
2024-03-17T20:07:19.2366344Z …
```
=> Add missing dns domain to tests to avoid verbose test logs

management/server/grpcserver.go
The issue happens when a new account is created not through the dashboard but by logging in a new machine.
The fix just does 3 retries with a delay on token validation.
=> Fix invalid token on peer login due to the cache race

management/server/idp/azure.go
Get scope from endpoint url instead of hardcoding for Azure (Entra ID). This is to fix errors occured when the endpoint is not https://graph.microsoft.com.
#1663
=> Get scope from endpoint url instead of hardcoding for Azure (Entra ID)

infrastructure_files/docker-compose.yml.tmpl.traefik
=> Changing the dashboard image pull from wiretrustee to netbirdio for traefik docker template

client/cmd/service_installer.go
This enables auto restart of the windows agent daemon service on event of failure
=> Auto restart Windows agent daemon service

client/internal/routemanager/client.go, client/internal/routemanager/client_test.go
Now that we have the latency between peers available we can use this data to consider when choosing the beste route. This way the route with the routing peer with the lowes latency will be prefered over others with the same target network.
https://github.com/netbirdio/netbird/issues/1554
=> Add latency based routing

management/server/account.go
Sometimes the Owner role will be passed to new users, and they need to be able to delete the account
=> Allow owners that did not create the account to delete it

util/grpc/dialer.go
Running `netbird login` as non-root will fail setting the fwmark, which is not required for this procedure, hence we don't use the custom dialer for it
=> Don't use the custom dialer as non-root

client/internal/engine.go, client/internal/peer/conn.go, client/internal/peer/status.go, client/internal/peer/status_test.go, client/internal/routemanager/client.go, client/server/server.go
Adding a mutex to the struct although the norm, could not be used due to the state being copied around. Fixes #1759 
- [x ] Is it a bug fix
=> Routes is a map, employing safe read/writes ops

client/internal/routemanager/systemops_linux.go
On some kernels removing ip rules with a bunch of criteria lead to removal of the existing `main` rule. This approach makes sure we only delete rules of predefined preference
=> Use fixed prefs

client/internal/routemanager/systemops_linux.go, client/internal/routemanager/systemops_test.go
=> Add sysctl opts to prevent reverse path filtering from dropping fwmark packets

management/server/migration/migration.go, management/server/migration/migration_test.go, management/server/network.go, management/server/sqlite_store.go, management/server/sqlite_store_test.go, route/route.go
Migrates all `serializer:gob` fields to `serializer:json`.
```
2024-04-17T11:36:52+02:00 INFO management/server/migration/migration.go:97: Migration of accounts.network_net from gob to json completed
2024-04-17T11:36:52+02:00 INFO management/server/migration/migration.go:97: Migration of routes.network from gob to json completed
2024-04-17T11:36:52+02:00 INFO management/server/migration/migration.go:97: Migration of routes.peer_groups from gob to json completed
```
=> Migrate serializer:gob fields to serializer:json

management/server/account.go, management/server/http/users_handler.go, management/server/jwtclaims/claims.go, management/server/jwtclaims/extractor.go, management/server/jwtclaims/extractor_test.go, management/server/user.go
This will reduce calls to cache and external IDP managers by reducing the redeem invite calls to only when the invited claim is received.
=> Redeem invite only when incoming user was invited

client/ui/client_ui.go
This PR adds support for the GUI client to display an error window when clicking connect or disconnect.
Example:
=> Add support for GUI app to display error

management/server/account.go
There was a race condition within the `getAccountWithAuthorizationClaims` method which was causing some operations to not store the updated data properly in the backend because it was overwriting with an old state. This PR adds account locks to this method to avoid overwriting.
How I reproduced:
- make sure you reach line 1782 in account.go (either remove the top conditions or use single account mode and change your env)
- add a random sleep between 0 and 2 seconds either in the `updateAccountDomainAttributes` right before the `SaveAccount` (line 1420) or within the `SaveAccount` method itself like
```
time.Sleep(time.Duration(rand.Float64() * float64(time.Second)))
```
- add a process querying any api endpoint so that the domain attributes get updated with a small enough frequency like …
=> Add account locks to getAccountWithAuthorizationClaims method

client/internal/routemanager/manager.go, util/net/net.go
This PR adds the required exception for the custom routing so that exit nodes can be used in the iOS app.
=> Support exit nodes on iOS 

.github/workflows/golangci-lint.yml, management/server/account.go, management/server/peer.go
Added one retry to the IdP lookup. Properly handle empty userdata when creating account during peer login from an iphone.
=> Add retry to IdP cache lookup

client/ios/NetBirdSDK/preferences.go
Adding methods to manage rosenpass settings from iOS.
=> Support rosenpass on iOS

client/internal/routemanager/client.go, client/server/route.go, route/route.go
Copying the IDs for `routes list` accidentally modified the original routes, resulting in a panic.
Now we copy the desired values explicitly
=> Fix route selection IDs

management/server/grpcserver.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/posture_checks_handler.go, management/server/http/posture_checks_handler_test.go, management/server/posture/checks_test.go, management/server/posture/process.go, management/server/posture/process_test.go
Separate the unix process path into Linux and MacOS process path for  handling platform-specific paths more effectively.
=> Separate Unix process path into Linux and macOS paths

client/internal/routemanager/systemops_bsd.go
Sometimes the bsd routing table contains routes with the flag `W`:
> W      RTF_WASCLONED   Route was generated as a result of cloning
These routes only appear using the `a` flag:
`netstat -nra`
This prevents us from creating routes for netbird.
This change ignores routes of this types and creates the routes, overriding the cloned ones.
#1900
=> Ignore cloned routes on bsd

iface/wg_configurer_usp.go
Current implementation of removeAllowedIP recreates the wg iface, killing all open ports and connections. This is due to that "lines" is the complete output of `get` from wg-usp and not the specific interface which changes should be applied to.
Refactor removeallowedip to be similar to addallowedip.
fixes #1912 
- [ x] Is it a bug fix
=> Fix removeAllowedIP

client/internal/dns/file_linux.go
Stop the file repairer before doing the restore. If it does not do it the file repairer logic automatically overwrites the restored file.
=> Fix resolv.conf repairer logic

client/internal/login.go, management/client/grpc.go
Try login only if we have a server public key
fixes #1907
=> Fix a panic when management is behind an invalid proxy

client/internal/routemanager/systemops_bsd.go
Similar to #1817, BSD base OSes will return "cannot allocate memory" errors when routing table is expanding.
See issue #1681, this is an additional fix
=> Retry reading routing table (bsd)

management/server/migration/migration.go, management/server/migration/migration_test.go, management/server/peer/peer.go, management/server/sqlite_store.go, management/server/sqlite_store_test.go
Migrates all net ip blob fields to serializer:json.
=> Migrate blob net ip fields to json serializer

client/internal/dns/server.go
In 0.27.5 we started removing the handler for the root zone in case of a network failure. But when the failure was gone we didn't add the handler back to the local resolver. 
This PR adds the handler again fix the issue and add it back to the resolver.
fixes #1969
=> Fix lost root zone handler

release_files/install.sh
Adds support for installing and updating NetBird on Synology NAS devices. 
```bash
curl -fsSL https://pkgs.netbird.io/install.sh | sh
```
```bash
curl -fsSL https://pkgs.netbird.io/install.sh | sh -s -- --update
```
#1977 
#1325
=> Add  installer support for Synology

client/internal/dns/upstream.go
This PR enabled the temopary deactivation of nameservers in case they are unresponsive for some time.
=> Enable namserver deactivation if unresponsive on iOS

client/internal/connect.go, client/internal/peer/conn.go
The iOS app only allows to connect to a limited number of peers before it reaches its memory limits (currently 50MB for the network extension). This PR is the first step in optimizing the memory usage for iOS by increasing the garbage collection.
https://github.com/netbirdio/netbird/issues/1899#issuecomment-2109235977
=> Increase garbage collection on ios

client/internal/engine.go, client/internal/engine_test.go
Because the `connWorker` are operating with the `e.peerConns` list we must ensure all workers exited before we modify the content of the `e.peerConns` list.
If we do not do that the engine will start new `connWorkers` for the exists ones, and they start connection for the same peers in parallel.
=> Gracefully conn worker shutdown

management/server/peer/peer.go
This change will store Peer.Location information with the peer meta allowing trace
=> Store location information in peer event meta

client/internal/connect.go, client/internal/connect_test.go
check if WgPort is available, if not find a free port
fixes issue #546
=> use the next available port for wireguard

client/cmd/login.go, client/cmd/login_test.go
Reverts netbirdio/netbird#2037
Some distributions based on debian actually sets the XDG_ variables even on server versions.
=> Revert "Accept any XDG_ environment variable to determine desktop"

client/firewall/create_linux.go
Some systems don't play nice with a test chain, so we dropped the idea, and instead, we just checked for the filter table
With this check, we might face a case where iptables is selected once, and on the next netbird up/down, it will go back to using nftables
=> Refactor firewall manager check

management/server/account.go, management/server/file_store.go, management/server/http/posture_checks_handler.go, management/server/mock_server/account_mock.go, management/server/posture/checks.go, management/server/sql_store.go, management/server/store.go
This PR refactors the conversion of posture checks from API objects to system objects and backward.
It adds a method to find an existing posture check definition based on the check definition.
=> Add FindExistingPostureCheck

client/android/client.go, client/system/info.go, client/system/info_android.go
Fill the UI version info in system meta on Android
=> Fill the UI version info in system meta on Android

client/internal/engine.go, client/internal/peer/conn.go
This will prevent peer connections via other peers.
=> Ignore candidates whose IP falls into a routed network

management/server/idp/zitadel.go
According to the Zitadel documentation, `openid` scope is required when requesting JWT tokens.
Apparently Zitadel was accepting requests without it until very recently. Now lack thereof causes 400 Bad Requests which makes it impossible to authenticate to the Netbird dashboard.
https://zitadel.com/docs/guides/integrate/service-users/client-credentials#2-authenticating-a-service-user-and-request-a-token
None
=> Add missing `openid` scope when requesting JWT token in Zitadel

client/cmd/debug.go, client/cmd/root.go, client/cmd/route.go
=> Respect env for debug and routes sub commands

client/internal/routemanager/client.go, client/internal/routemanager/dynamic/route.go, client/internal/routemanager/refcounter/refcounter.go, client/internal/routemanager/static/route.go
Removes the check about whether a peer is still connected before removing allowed IPs (= decreasing ref count to 0)
Fixes #2093
=> Never skip removing allowed IPs

go.mod, go.sum
=> Use forked go-netroute

client/cmd/testutil.go, client/internal/engine_test.go, client/server/server_test.go, go.mod, go.sum, signal/README.md, signal/client/client_test.go, signal/cmd/run.go, signal/metrics/app.go, signal/metrics/metrics.go, signal/peer/peer.go, signal/peer/peer_test.go, signal/server/signal.go
=> Add basic signal metrics

management/server/account.go, management/server/account_test.go
Optimizes the JWT group sync process by preventing unnecessary account saves and network map generation when there are no changes in JWT group membership. Additionally, it addresses a bug where the last API group added to the user's auto groups was being removed unintentionally.
- #1824
=> Optimize JWT Group Sync

client/cmd/testutil_test.go
This will reduce the client binary size in almost 25%
=> Prevent building test code for client

management/server/migration/migration.go, management/server/sql_store_test.go
When fetching empty values from the database to check for migration our parser failed to handle null strings preventing the service from start
This uses sql.NullString to handle that and check for empty string resulted from null data
=> Fix store migration on empty string

client/internal/networkmonitor/monitor_windows.go
=> Fix windows network monitor next hop ip log

management/server/store.go
=> Automatically migrate older management store engine to SQLite

infrastructure_files/getting-started-with-zitadel.sh
Update the container images in the `getting-started-with-zitadel.sh` Docker Compose template of:
- Zitadel -> `2.54.3`
- CockroachDB -> `latest-v23.2`
This change brings Zitadel to a stable version and fixes many bugs. Zitadel now requires CockroachDB at least version 23.2.
And the pull request also fixed a typo in the Docker Compose template.
=> Update Zitadel and CockroachDB Container Image Version

management/server/account.go, management/server/account_test.go, management/server/dns_test.go, management/server/grpcserver.go, management/server/mock_server/account_mock.go, management/server/nameserver_test.go, management/server/peer.go, management/server/peer_test.go, management/server/posture_checks.go
=> Optimize process checks database read

client/internal/routemanager/dynamic/route.go
=> Lower retry interval on dns resolve failure

client/firewall/iptables/router_linux.go, client/firewall/nftables/manager_linux.go, client/firewall/nftables/route_linux.go, client/firewall/nftables/router_linux_test.go
This makes sure loopback traffic is not affected by NAT
=> Add loopback ignore rule to nat chains

.github/workflows/test-infrastructure-files.yml, infrastructure_files/getting-started-with-zitadel.sh
This PR replaces cockroachDB as default DB for Zitadel  in the getting started script to deploy script. Users can switch back to cockroachDB by setting the environment variable ```ZITADEL_DATABASE``` to ```cockroach```.
The PR fix some typos as well.
- #1785
=> Feature/Use Zitadel Postgres Integration by default

infrastructure_files/docker-compose.yml.tmpl, infrastructure_files/getting-started-with-zitadel.sh
removed domainname for coturn service as it is needed only for SSL configs
Added log configuration for each service with a rotation and max size
ensure ZITADEL_DATABASE=postgres works
=> Add log config and removed domain

client/internal/dns/upstream.go
this fixes an issue introduced when we set the DNS query to request DNSSEC records on macOS. 
fixes #2201
=> Remove DNSSEC parameters and configure AuthenticatedData

.goreleaser_ui_darwin.yaml, client/Dockerfile
Add MACOSX_DEPLOYMENT_TARGET and MACOS_DEPLOYMENT_TARGET to target build compatible with macOS 11+ instead of relying on the builder's local Xcode version.
fixes #2218
=> add MACOSX_DEPLOYMENT_TARGET environment to control GUI build target

client/ui/client_ui.go
1. Add client-side multilingual support(MacOS&Windows)
2. Automatically adapt multilingualism according to the file mapping rules provided by Windows.
Windows
MacOS
#1937
=> Client UI Multiple language support

management/server/sql_store.go
added temporary domain check for existing accounts to trace where the issue originated
Refactor save account due to complexity score
=> Add stack trace when saving empty domains

client/internal/networkmonitor/monitor_bsd.go, client/internal/networkmonitor/monitor_linux.go
This removes interface based checks, the Linux one is not stable and monitoring the default route is sufficient.
=> Remove interface network monitor checks

management/server/metrics/selfhosted.go
Fix a bug where the post context was canceled before sending metrics to the server.
The interval time was decreased, and an optional environment variable NETBIRD_METRICS_INTERVAL_IN_SECONDS was added to control the interval time.
=> Fix issue with canceled context before pushing metrics and decreasing pushing interval

management/server/sql_store.go, management/server/sql_store_test.go
Added CreateBatchSize for both sql stores and updated tests to test large accounts with Postgres too. Increased the account peer size to 6K.
fixes #2151
=> Fix parameter limit issue for Postgres store

client/internal/routemanager/manager.go, client/internal/routemanager/notifier/notifier.go, client/internal/routemanager/systemops/systemops.go, client/internal/routemanager/systemops/systemops_android.go, client/internal/routemanager/systemops/systemops_bsd_test.go, client/internal/routemanager/systemops/systemops_generic_test.go, client/internal/routemanager/systemops/systemops_ios.go, client/ios/NetBirdSDK/client.go, client/ios/NetBirdSDK/routes.go, client/server/server.go
This PR adds support for exit nodes on iOS. It includes a small refactor to move the mobile notifier into the systemops and keep an in-memory map off all routes so that we can reuse the same logic for routing than on the desktop clients. It updates the route selection to show the domain names and the resolved IPs in the UI.
=> Support DNS routes on iOS

client/system/info_linux.go
=> fix 2260: fallback serial to Board

management/server/account.go, management/server/file_store.go, management/server/group.go, management/server/mock_server/account_mock.go, management/server/sql_store.go, management/server/store.go, management/server/user.go
=> Add batch save/update for groups and users

signal/server/signal.go
=> fix forwarded metrics

client/internal/routemanager/client.go
compare route update with the current routes, if routes aren't different skip recalculating of routes, like always please feel free to edit as you see fit
=> Ignore non unique route updates

client/cmd/root.go, util/log.go, util/syslog_nonwindows.go, util/syslog_windows.go
=> feat(client): send logs to syslog

management/server/sql_store.go, management/server/sql_store_test.go
This change fixes an inconsistency between the value of the boolean fields in the peer status struct, and those same values in the db table.
The problem should be in how the fields get updated in the `SavePeerStatus` function in the `management/server/sql_store.go` file, particularly because of how GORM manages the update itself. There's an [explanation on the GORM documentation](https://gorm.io/docs/update.html#Updates-multiple-columns) on why this happens.
This could be an issue for other boolean fields updates as well.
https://github.com/netbirdio/netbird/issues/2110
=> fix: save peer status correctly in sqlstore

signal/README.md, signal/cmd/run.go
This PR adds the ability to provide custom SSL certificates to the signal service. Most of the code was adapted from [management/cmd/management.go](https://github.com/netbirdio/netbird/blob/e8c2fafccd9ebb649a3d15f1b361e09bb2b61639/management/cmd/management.go) since it already offers the functionality I was looking to implement.
Two flags have been added, `--cert-file` and `--cert-key`, which accept a string pointing to a file path for the SSL certificate and key. When `--letsencrypt-domain` is set, these options are ignored.
This is my first try at go, so please let me know if anything needs refactored and fixed!
Along with https://github.com/netbirdio/dashboard/pull/399, closes #2242
=> Support custom SSL certificates for the signal service

client/cmd/down.go, client/internal/engine.go, client/internal/networkmonitor/monitor_bsd.go, client/server/server.go, management/client/grpc.go, signal/client/grpc.go, util/grpc/dialer.go
This PR awaits the engine shutdown before sending the confirmation back to the cli. It also fixes an issue where there was a race condition when running multiple up and down commands in sequence.
=> Wait on daemon down

client/internal/routemanager/systemops/systemops_generic.go, client/internal/routemanager/systemops/systemops_windows_test.go
When adding a host route for a peer's IP address that belongs to a connected network, macOS may stop using ARP/NDP to resolve the IP address. This will lead to unreachability of the targeted IP. 
This PR prevents adding exclusion routes for connected networks.
=> Don't add exclusion routes for IPs that are part of connected networks

client/internal/dns/upstream.go
- Count success queries and compare it before doing after network map probes.
- Reduce the first dns probe to 500ms
- Updated test domain with com instead of . due to Palo alto DNS proxy server issues
=> Add faster availability DNS probe and update test domain to .com

client/internal/networkmonitor/monitor_windows.go
check if the nexthop interfaces are Microsoft ISATAP devices and ignore their suffixes when comparing them
=> Check if route interface is a Microsoft ISATAP device

client/internal/dns/host.go, client/internal/dns/host_darwin.go
On macOS use the recommended settings for providing split DNS. As per the docs an empty string will force the configuration to be the default. In order to to support split DNS an additional service config is added for the local server and search domain settings.
see: https://developer.apple.com/documentation/devicemanagement/vpn/dns
=> Refactor macOS system DNS configuration

client/firewall/uspfilter/uspfilter.go
This fixes an issue where UDP rules were ineffective for userspace clients (Windows/macOS)
=> Remove default allow for UDP on unmatched packet

management/server/file_store.go, management/server/peer.go, management/server/sql_store.go, management/server/sql_store_test.go, management/server/store.go
SyncPeer was storing the account with a simple read lock
This change introduces the SavePeer method to the store to be used in these cases
=> Add SavePeer method to prevent a possible account inconsistency

management/server/account.go, management/server/account_test.go
- [Unexpected behaviour when syncing groups from IdP(Zitadel)](https://github.com/netbirdio/netbird/issues/2322)
=> Remove redundant check for empty JWT groups

management/server/peer.go, management/server/status/error.go
This pull request refactors the login functionality by integrating store.SavePeer. The changes aim to improve the handling of peer login processes, particularly focusing on synchronization and error handling.
Changes:
- Refactored login logic to use store.SavePeer.
- Added checks for login without lock for login necessary checks from the client and utilized write lock for full login flow.
- Updated error handling with status.NewPeerLoginExpiredError().
- Moved geoIP check logic to a more appropriate place.
- Removed redundant calls and improved documentation.
- Moved the code to smaller methods to improve readability.
-
=> Refactor login with store.SavePeer

management/server/account.go, management/server/dns.go, management/server/event.go, management/server/file_store.go, management/server/group.go, management/server/integrated_validator.go, management/server/nameserver.go, management/server/peer.go, management/server/policy.go, management/server/posture_checks.go, management/server/route.go, management/server/setupkey.go, management/server/sql_store.go, management/server/store.go, management/server/user.go
This pull request adds a write lock mechanism for peers when saving their connection status. The primary goal is to ensure thread safety and prevent race conditions during peer status updates.
Key Changes
- Implemented write locks for peers by their key.
- Utilized read account locks for methods used by grpcServer.Sync.
- Renamed lock methods for clarity.
=> Add write lock for peer when saving its connection status

management/server/account.go, management/server/grpcserver.go, management/server/mock_server/account_mock.go
Moved the write peer lock to avoid latency caused by disk access
Updated the method CancelPeerRoutines to use the peer public key
=> Move write peer lock

management/server/account.go, management/server/grpcserver.go, management/server/management_proto_test.go, management/server/mock_server/account_mock.go
Use accountID retrieved from the sync call to acquire read lock sooner and avoiding extra DB calls.
- Use the account ID across sync calls
- Moved account read lock
- Renamed CancelPeerRoutines to OnPeerDisconnected
- Added race tests
-
=> Use accountID retrieved from the sync call to acquire read lock sooner

.editorconfig, formatter/formatter.go, formatter/formatter_test.go, formatter/set.go, util/log.go
```console
journalctl
```
```diff
- Jul 19 14:41:01 rpi /usr/bin/netbird[614]: 2024-07-19T14:41:01+02:00 ERRO %!s(<nil>): error while handling message of Peer [key: REDACTED] error: [wrongly addressed message REDACTED]
- Jul 19 21:53:03 rpi /usr/bin/netbird[614]: 2024-07-19T21:53:03+02:00 WARN %!s(<nil>): disconnected from the Signal service but will retry silently. Reason: rpc error: code = Internal desc = server closed the stream without sending trailers
- Jul 19 21:53:04 rpi /usr/bin/netbird[614]: 2024-07-19T21:53:04+02:00 INFO %!s(<nil>): connected to the Signal Service stream
- Jul 19 22:24:10 rpi /usr/bin/netbird[614]: 2024-07-19T22:24:10+02:00 WARN [error: read udp 192.168.1.11:48398->9.9.9.9:53: i/o timeout, upstream: 9.9.9.9:53] %!s(<nil>): got an error while connecting to …
```
=> fix(util): syslog output contains duplicated timestamp

management/server/geolocation/database.go
Adding geolocation download prompt message.
When the network condition is poor, there are no prompts when downloading the geolocation file.
#2046
=> Adding geolocation download log message.

management/server/config.go
Currently in the setup that is used in getting started with zitadel script, only 2 audiences are configured when the http server checks the auth token.  Those 2 are:  1. HttpConfig.AuthAudience and 2. DeviceAuthorization.ProviderConfig.Audience.
The HttpConfig authAudience is setup like this: "AuthAudience": "$NETBIRD_AUTH_CLIENT_ID"
The DeviceAuthorization.ProviderConfig.Audience is setup like this:  "Audience": "$NETBIRD_AUTH_CLIENT_ID_CLI",
Therefore, any auth token that will be accepted by the api server has to have either of those 2 audiences set. 
In order to provide an automation user (zitadel machine user) with a clientid/clientsecret to allow for unattended login by ansible/terraform/etc, it is not obvious how to get a token with that audience, at least I haven't figured out how. …
=> Add extra auth audience field on HttpConfig for automation user to authorize via zitadel

client/cmd/debug.go
This allows to get interface and route information added by the agent
=> Move Bundle to before netbird down

.github/workflows/release.yml
Systems that validates the binary version didn't like the build number as we set
This fixes the versioning and will use a static build number
To validate the version output you can run the following command in powershell:
```shell
[System.Diagnostics.FileVersionInfo]::GetVersionInfo('C:\Program Files\Netbird\netbird.exe')
ProductVersion   FileVersion      FileName
--------------   -----------      --------
0.28.7.0          0.28.7.0          C:\Program Files\Netbird\netbird.exe
```
=> Fix Windows file version

client/cmd/root.go
- Change default config location on FreeBSD
`/etc/netbird/` -> `/var/db/netbird/`
#2383
=> change default config location on freebsd

client/internal/auth/oauth.go
=> Offer only Device Code Flow on FreeBSD

client/ios/NetBirdSDK/client.go
Adding a nullpointer check to the GetRouteSelection for iOS to avoid possible nullpointer exceptions.
=> On iOS add error handling for getRouteselector

management/server/peer.go
when getting all peers we don't need to calculate network map when not a regular user
=> Skip network map check if not regular user

client/cmd/login.go, client/cmd/root.go, client/cmd/up.go, client/cmd/up_daemon_test.go
Adds a flag and a bit of logic to allow a setup key to be passed in using a file. The flag should be exclusive with the standard `--setup-key` flag.
N/A
I am attempting to set up netbird automatically in a Lix environment, but the secrets library I use requires that I write the secrets to files and ask programs to use those at runtime. I believe this change will also allow someone to use docker secrets to provide a setup key.
I am unsure what/if changes should be made to any documentation or to the README file.
(I apologize if I have missed anything, this is my first time contributing to an open source project.)
=> Allow setup keys to be provided in a file

client/cmd/login.go, client/cmd/root.go, client/cmd/up.go
refactor functions and variable assignment
=> [client] Parse data from setup key

management/server/account.go, management/server/setupkey.go, management/server/setupkey_test.go, management/server/user.go
=> [management] Prevent removal of All group from peers during user groups propagation 

relay/server/store.go, relay/server/store_test.go
When a peer disconnects gracefully from the server and immediately connects back, then the server will clean up an incorrect peer instance from the in-memory store. In this fix the store checks the peers instance before deleting it.
Error happened here:
https://github.com/netbirdio/netbird/actions/runs/10281624634/job/28451564919?pr=2399
=> [client] Feature/relay integration fix reconnection

client/internal/networkmonitor/monitor_bsd.go, client/internal/networkmonitor/monitor_generic.go, client/internal/networkmonitor/monitor_windows.go, client/internal/routemanager/systemops/systemops_windows.go
This new one uses functions from netioapi.h to monitor route changes. This change ensures that we include routes that point to virtual interfaces, such as vEthernet created by the Hyper-V Virtual Switch.
=> Replace windows network monitor implementation

management/server/account.go, management/server/account_cache.go, management/server/management_proto_test.go, management/server/peer.go
This PR adds a buffer for the getAccount operation during login to collect requests over a specific time inteval and only call the database once. This way reducing overall load on the DB.
=> [management] Add buffering for getAccount requests during login

client/internal/connect.go, client/internal/connect_test.go
Rely on `net.ListenUDP` to get an available port for wireguard in case the configured one is in use
=> [client] Refactor free port function

infrastructure_files/configure.sh, infrastructure_files/docker-compose.yml.tmpl, infrastructure_files/docker-compose.yml.tmpl.traefik
Updated the configure script and docker-compose templates to better support deployment with postgres. Prevents the need to manually add the NETBIRD_STORE_ENGINE_POSTGRES_DSN environment variable to the docker-compose file after the configuration script is run (https://docs.netbird.io/selfhosted/postgres-store). Also provides warning to the user if the NETBIRD_STORE_CONFIG_ENGINE=postgres and NETBIRD_STORE_ENGINE_POSTGRES_DSN is not set.
=> [misc] Add support for NETBIRD_STORE_ENGINE_POSTGRES_DSN environment variable in setup.env

management/server/account.go, management/server/http/handler.go, management/server/sql_store.go, management/server/telemetry/http_api_metrics.go
=> [management] Refactor HTTP metrics

client/internal/engine_test.go, iface/iface_test.go, iface/tun.go, iface/tun_windows.go
RequestedGUID is the GUID of the created network adapter, which then influences NLA generation deterministically.
With this change, NetBird should not generate multiple interfaces in every restart on Windows.
Resolves #1658 #2004
=> [client] Use static requested GUID when creating Windows interface

client/internal/peer/conn.go, client/internal/peer/worker_relay.go, relay/client/client.go
Fix **netbird down** command
The ICE agent closes the connection in async way. After the close event, it restarted the connection upgrade to Relay. In the relay code it started new go routines. Check the context.Err() in all cases when an event can happen in async way.
=> [relay] Fix peer close function

client/cmd/testutil_test.go, client/internal/engine_test.go, client/server/server_test.go, management/client/client_test.go, management/cmd/management.go, management/cmd/management_test.go, management/server/config.go, management/server/grpcserver.go, management/server/management_proto_test.go, management/server/management_test.go, management/server/token_mgr.go, management/server/token_mgr_test.go
In the config file make no sense to use the config keyword.
Rename RelayConfig to Relay
=> [relay] Rename RelayConfig to Relay

client/internal/engine.go, client/internal/peer/conn.go, client/internal/peer/conn_test.go, client/internal/peer/stdnet.go, client/internal/peer/stdnet_android.go
Store the StunTurn address in atomic store
Does not need to apply a lock and extra function to update the addresses
=> [relay] Store the StunTurn address in thread safe store

go.mod, go.sum, release_files/install.sh
This add `rpm-ostree` binary detection in installation script and update `kardianos/service` module to lastest commits. It should close https://github.com/netbirdio/netbird/issues/1634
Latest commits of `kardianos/service` correctly detect and discriminate between `/etc` folders (init.d, systemd/system....)
=> [misc] Support rpm-ostree based distros in installation script

client/internal/connect.go
=> [client] Avoid panic when there is no conn client

infrastructure_files/getting-started-with-zitadel.sh
The previous X-Frame DENY header prevented to display the page inside an iFrame. 
The current OIDC library for the dashboard uses iFrame to perform a silent login. 
> Silent signing uses cookies from your OIDC provider to restore the session and retrieve tokens. It opens an IFrame in the background, directed to a specific page on your OIDC provider.
This fix changes the X-Frame-Options header `DENY` to `SAMEORIGIN`
=> [dashboard] Use X-Frame-Options sameorigin header

relay/server/relay.go, relay/server/relay_test.go
This allows the relay to run behind a proxy doing TLS termination
=> Support exposed address with scheme

iface/iface_create.go, iface/iface_darwin.go, management/server/peer.go
The interface creation on macOS seems to be asynchronus why the tun.create methode somethimes failes becasue the interface is not ready yet. To work around this issue we introduce a retry on tun.create
=> [client] Retry on tun creation for darwin

.github/workflows/test-infrastructure-files.yml
=> Remove pre-release step from workflow

management/server/activity/sqlite/crypt.go, management/server/activity/sqlite/crypt_test.go, management/server/activity/sqlite/migration.go, management/server/activity/sqlite/migration_test.go, management/server/activity/sqlite/sqlite.go
This PR updates the encryption scheme for events data from the legacy CBC encryption with a static IV to the GCM (Galois/Counter Mode) encryption. 
Closes #2246
=> [management] Add GCM encryption and migrate legacy encrypted events

client/internal/connect.go, client/internal/engine.go
Instead of starting and stopping the engine, stop engine and force recreate from connect. This might tie network monitor to autoconnect feature. Additionally, when recreating the engine ensure existing engine is stopped.
#2454 
#2196 
#2011
=> [client] Ensure engine is stopped before starting it back

management/cmd/root.go, relay/cmd/root.go, signal/cmd/run.go
Currently, the listen port for the metrics server is hardcoded for the signal and relay service.
Updated the default port for management from 8081 to 9090.
=> [management] Add command flag to set metrics port for signal and relay service, and update management port

signal/peer/peer.go, signal/server/signal.go
The metrics for active peers on signal is leaking and growing. The metrics should be in sync with management connections. This PR changes when we report active peers
=> [signal] Fix signal active peers metrics

relay/client/client.go, relay/client/manager.go, relay/client/picker.go, relay/server/peer.go, relay/server/store.go, relay/server/store_test.go
Fix leaked server connections
- close unused connections in the client lib
- close deprecated connection in the server lib
The Server Picker is reusable in the guard if we want in the future. So we can support the server address changes.
=> Fix leaked server connections

client/internal/config.go, util/file.go, util/permission.go, util/permission_windows.go
Enforce folder permission on Windows, giving only administrators and system access to the NetBird folder.
=> Enforce permissions on Win

relay/client/client.go, relay/healthcheck/receiver.go, relay/healthcheck/receiver_test.go, relay/healthcheck/sender.go, relay/healthcheck/sender_test.go, relay/server/peer.go
Add support to relay heath check threshold using the environment variable NB_RELAY_HC_ATTEMPT_THRESHOLD. By default that is set to 1 try.
It is recommended to change this setting on both the server and clients connecting to the relay.
=> [relay] Add health check attempt threshold

client/internal/peer/conn.go, client/internal/peer/conn_status.go, client/internal/peer/conn_test.go
The ConnStatus variable has been read in internal/peer/conn.go:330 and has been written in internal/peer/conn.go:422. It was not thread safe.
=> [client] Fix race condition while read/write conn status in peer conn

client/internal/peer/conn.go, client/internal/peer/worker_relay.go
When enabling the WG watcher the code checks the context cancellation status. Unfortunately, we canceled it in the Disable function only but are required to cancel it when exit the watcher go routine.
=> [client] Cancel the context of wg watcher when the go routine exit

relay/client/picker.go, relay/client/picker_test.go
If all server is unavailable then the server picker never returns because we never close the result channel
=> Exit from processConnResults after all tries

management/server/http/peers_handler.go, management/server/http/peers_handler_test.go
=> [management] Restrict accessible peers to user-owned peers for non-admins

management/server/http/api/openapi.yml
Our API doc was generating the wrong example for the IP range posture check call because the openAPI definition was type string but got an example array. Moved the example to the array level to avoid duplicated array brackets.
=> [misc] Fix ip range posture check example in API doc

client/internal/networkmonitor/monitor_bsd.go, client/internal/wgproxy/proxy_userspace.go
=> [client] Remove usage of custom dialer for localhost

client/cmd/status.go
```
docker0.netbird.cloud:
NetBird IP: 100.64.122.40
Public key: NEtQbOTpIVdmQFm4VMXXZvauPI9gdkrNarfAbuzeFVY=
Status: Connected
-- detail --
Connection type: P2P
ICE candidate (Local/Remote): host/prflx
ICE candidate endpoints (Local/Remote): 192.168.100.235:57255/192.168.100.1:51820
Relay server address: rel://192.168.anon-5QCcF.domain:8086
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Last connection update: 5 minutes, 19 seconds ago
Last WireGuard handshake: 2 minutes, 24 seconds ago
Transfer status (received/sent) 600 B/360 B
Quantum resistance: false
Routes: -
Latency: 877.896µs
```
=> [client] Anonymize relay address in status peers view

management/server/idp/zitadel.go, management/server/idp/zitadel_test.go
Adds a zitadelErrorResponse struct to decode errors returned from zitadel rather than just returning a status code, so more information can be learned about potential configuration issues. Helped to diagnose #2616
I have some other small changes and improvements to compatibility later, but this was a pretty clear cut and standalone improvement.
=> [management] improve zitadel idp error response detail by decoding errors

go.mod, go.sum, management/server/http/handler.go
Propagates the opentelemetry meter into management integrations.
=> [management] Propagate metrics

release_files/install.sh
1. Made the script check for doas to work with alpine linux
2. Specified a set DNS server in the curl statement that downloads the binaries. I had issues where the curl request wouldnt resolve the URL, my theory is that since one of the redirect URL's are very long the standard DNS wont resolve it. This is what i experienced on alpine linux, and setting the google dns in the curl request fixed the issue.
3. Change "-C" to "-c" in the sort statement, the sort version in alpine linux doesnt have the "-C" function and it works just as well with "-c"
=> Install sh alpine fixes

client/internal/peer/conn.go
If it has an active P2P connection meanwhile the Relay connection is broken with the server then we removed the WireGuard peer configuration.
=> [relay-client] Fix Relay disconnection handling

go.mod, go.sum, signal/server/signal.go
This PR moves the dummy message handling used in client probes into the signal dispatcher.
=> [signal] Move dummy signal message handling into dispatcher

client/internal/connect.go, client/internal/engine.go
Tweaking logic at connect to ensure wgInterface doesn't exist before starting a new engine #2196
=> [client] Check wginterface instead of engine ctx

management/server/account.go
=> [management] Remove admin check on getAccountByID

management/cmd/management.go, util/file.go, util/file_suite_test.go, util/file_test.go
This change allows users to reference environment variables using Go template format, like `{{ .EnvName }}`
I also moved the previous file test code to file_suite_test.go. I will migrate these tests to another PR.
=> Add support to envsub go management configurations

go.mod, go.sum, signal/server/signal.go
The new dispatcher version has a fix for error handling if a peer is not connected.
=> [signal] new signal dispatcher version

client/firewall/nftables/manager_linux.go, client/firewall/nftables/manager_linux_test.go, client/firewall/nftables/router_linux.go
This specifically concerns the established/related rule since this one is not compatible with iptables-nft even if it is generated the same way by iptables-translate.
#2725
=> [client] Add table filter rules using iptables

relay/metrics/realy.go, relay/server/handshake.go, relay/server/relay.go
Move the handshake logic to separated struct but fully keep the protocol.
- The server will respond to the client after it is ready to process the peer
- Preload the response messages
The authentication step is faster because do not need to marshal the response messages and this change fix flickering tests (see: NB-1047).
=> [relay-server] Move the handshake logic to separated struct

client/firewall/iptables/router_linux.go, client/firewall/nftables/router_linux.go, client/firewall/nftables/router_linux_test.go
This fixes  an issue with the ebpf proxy port being changed by the nat rules
```
-A NETBIRD-RT-NAT -i wt0 ! -o lo -j MASQUERADE
-A NETBIRD-RT-NAT ! -i lo -o wt0 -j MASQUERADE
```
```
chain netbird-rt-postrouting {
type nat hook postrouting priority srcnat - 1; policy accept;
iifname "wt0" oifname != "lo" counter packets 0 bytes 0 masquerade
oifname "wt0" iifname != "lo" counter packets 0 bytes 0 masquerade
}
```
=> [client] Exclude loopback from NAT

infrastructure_files/getting-started-with-zitadel.sh
Update Zitadel version at docker compose in quickstart script from 2.54.3 to 2.54.10 because 2.54.3 isn't stable and has a lot of bugs.
Updated Zitadel version to 2.54.10 because most features don't work properly on 2.54.3 as I experienced.
As I updated my Zitadel version on my local Netbird installation, Zitadel features started working as intended.
Issue is discussed with Zitadel in the link below:
https://github.com/zitadel/zitadel/discussions/8708#discussioncomment-10830883
- [+] Is it a bug fix
- [+] Is a feature enhancement
=> Update Zitadel version on quickstart script

management/server/sql_store.go, management/server/sql_store_test.go
This PR resolves the issue with `json_array_length` compatibility between SQLite and PostgreSQL. It adjusts the query to conditionally cast types:
- **PostgreSQL**: Casts to `json` with `::json`.
- **SQLite**: Uses the text representation directly.
Closes #2745
=> Fix JSON function compatibility for SQLite and PostgreSQL

client/ui/netbird-ui.rb.tmpl, release_files/install.sh
Since 0.30.2, the decompressed binary path from the signed package has changed, now it doesn't contain the arch suffix 
This change handles that
=> Fix decompress zip path

client/firewall/create_linux.go
=> [client] Make native firewall init fail firewall creation

client/internal/acl/manager.go
- Ignores empty sources when applying route rules
- Accumulates errors and returns them when applying route rules
=> [client] Ignore route rules with no sources instead of erroring out

client/internal/peer/ice/agent.go
In the previous versions, iOS had some limitations regarding relay. We worked around those issues by never allowing an iOS app to be a leader in a relay connection. This was causing some connections to never be established. With the new relay and the removal of the proxy we can now fully use relay on iOS.
=> [client] allow relay leader on iOS

management/server/account.go, management/server/account_test.go, management/server/activity/codes.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handler.go, management/server/http/peers_handler_test.go, management/server/http/setupkeys_handler.go, management/server/http/setupkeys_handler_test.go, management/server/metrics/selfhosted.go, management/server/migration/migration.go, management/server/migration/migration_test.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer/peer.go, management/server/peer_test.go, management/server/setupkey.go, management/server/setupkey_test.go, management/server/sql_store.go, management/server/sql_store_test.go, management/server/status/error.go, management/server/store.go
This PR adds the following changes:
- migrated setup keys from plain text to hashed format in the database
- allows custom expiration time for setup keys. There is no limit anymore, it even allows not expiring keys
- add delete endpoint for setup keys
=> [management] Setup key improvements

go.mod, go.sum
The gVisor release was removed which is described at
https://github.com/google/gvisor/issues/11085#issuecomment-2438974962.
Update the gVisor version in netbird to fix the build failure.
https://github.com/google/gvisor/issues/11085
=> [client] Fix the broken dependency gvisor.dev/gvisor

management/server/telemetry/updatechannel_metrics.go, management/server/updatechannel.go, management/server/updatechannel_test.go
Adding metrics to the network map diff calculation.
=> [management] add metrics to network map diff

relay/client/manager.go, relay/client/manager_test.go, relay/client/picker_test.go
The cleanup loop did not manage those situations well when a connection failed or 
the connection success but the code did not add a peer connection to it yet.
- in the cleanup loop check if a connection failed to a server
- after adding a foreign server connection force to keep it a minimum 5 sec
=> Fix unused servers cleanup

client/server/panic_generic.go, client/server/panic_windows.go, client/server/server.go
To use, set env var, e.g. 
```powershell
[System.Environment]::SetEnvironmentVariable('NB_WINDOWS_PANIC_LOG', "$env:ProgramData\netbird\netbird.err", 'Machine')
```
=> [client] Log windows panics

management/server/peer.go
When adding a peer the participation in the all group was not checked and could cause issues that a network map was not send.
=> [management] Fix add peer all group network map update

client/server/server.go
This change removes the cached device flow oauth info when a down command is called
Removing the need for the agent to be restarted
=> [client] Fix cached device flow oauth

client/firewall/iptables/acl_linux.go, client/firewall/iptables/router_linux.go, client/firewall/iptables/router_linux_test.go, client/firewall/manager/firewall.go, client/firewall/nftables/acl_linux.go, client/firewall/nftables/router_linux.go, client/firewall/nftables/router_linux_test.go, util/net/net.go
Replace dynamic postrouting rules with input interface with dynamic prerouting rules + static postrouting rules.
Older versions, such as Ubuntu 20.04, don't support matching on the input interface in the postrouting chain. As a result the masquerade rules didn't match at all.
Following an example with route `10.20.1.0/24`
```
table ip netbird {
chain netbird-rt-postrouting {
type nat hook postrouting priority srcnat - 1; policy accept;
iifname "wt0" oifname != "lo" ip daddr 10.20.1.0/24 counter packets 0 bytes 0 masquerade
oifname "wt0" iifname != "lo" ip saddr 10.20.1.0/24 counter packets 0 bytes 0 masquerade
}
}
```
```
-A POSTROUTING -j NETBIRD-RT-NAT
-A NETBIRD-RT-NAT -d 10.20.1.0/24 -i wt0 ! -o lo -j MASQUERADE
-A NETBIRD-RT-NAT -s 10.20.1.0/24 ! -i lo -o wt0 -j MASQUERADE
```
``` …
```
=> [client] Use the prerouting chain to mark for masquerading to support older systems

management/server/sql_store.go
=> [management] Remove context from database calls

management/server/grpcserver.go
=> [management] Add peer lock to grpc server

client/internal/peer/status.go, client/internal/peer/status_test.go, client/internal/peer/worker_ice.go, client/internal/routemanager/client.go, client/internal/routemanager/refcounter/refcounter.go
- ICE do not trigger disconnect callbacks if the stated did not change
- Fix route calculation callback loop
- Move route state updates into protected scope by mutex
- Do not calculate routes in case of peer.Open() and peer.Close()
=> [client] Remove loop after route calculation

client/cmd/service.go, client/cmd/service_controller.go, client/internal/connect.go, client/internal/peer/status.go
- Fix race when accessing service controller server instance
- Fix race when retrieving ctx state error
- Fix concurrent map access in status
=> [client] Fix race conditions

management/server/account.go, management/server/account_test.go, management/server/group.go, management/server/group/group.go, management/server/peer.go, management/server/setupkey.go, management/server/sql_store.go, management/server/sql_store_test.go, management/server/status/error.go, management/server/store.go, management/server/user.go
Remove calls to get and save whole account in setup key operations.
=> [management] Refactor setup key to use store methods

management/server/account.go, management/server/grpcserver.go, management/server/peer.go, management/server/status/error.go, management/server/updatechannel.go, management/server/user.go
=> [management] Add more logs to the peer update processes

management/server/group.go, management/server/http/peers_handler.go
The peers endpoint should not return groups for the peers in limited user view.
=> [management] Fix limited peer view groups

management/server/account.go
Even if inactivity is disabled before the change, the scheduled method can still be triggered. The method is never triggered when inactivity is disabled after the change. This is necessary to solve the error problem of SQL Tests.
=> Fix the Inactivity Expiration problem.

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [NetBird Guru](https://gurubase.io/g/netbird) to Gurubase. NetBird Guru uses the data from this repo and data from the [docs](https://docs.netbird.io/) to answer questions by leveraging the LLM.
In this PR, I showcased the "NetBird Guru", which highlights that NetBird now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me …
=> Introducing NetBird Guru on Gurubase.io

management/server/peer.go
=> [management] Fix process posture check evaluation on Sync

management/server/account.go, management/server/activity/codes.go, management/server/user.go
=> [management] Add activity events to group propagation flow

client/firewall/nftables/manager_linux.go
=> [client] Fix allow netbird rule verdict

client/internal/connect.go, client/internal/engine.go, client/internal/peer/status.go, client/internal/peer/worker_ice.go, relay/client/client.go, relay/client/client_test.go, relay/client/guard.go, relay/client/manager.go, relay/client/picker.go, relay/client/picker_test.go
Can support firewalls with restricted WS rules
- allow to run engine without Relay servers
- keep up to date Relay address changes
- handle thread-safe way the relay client instance
- reimplement guard code
- atomic store for Relay server address management
- allow to run engine without success Relay connection
- fix status indication
- allow to upgrade/downgrade between ICE Turn and Relay
=> [relay] Refactor initial Relay connection

client/firewall/nftables/manager_linux_test.go
=> [client] Test nftables for incompatible iptables rules

client/internal/routemanager/systemops/systemops_linux.go
```
rules := getSetupRules()
for _, rule := range rules {
if err := addRule(rule); err != nil {
if errors.Is(err, syscall.EOPNOTSUPP) {
log.Warnf("Rule operations are not supported, falling back to the legacy routing setup")
setIsLegacy(true)
return r.setupRefCounter(initAddresses, stateManager)
}
return nil, nil, fmt.Errorf("%s: %w", rule.description, err)
}
}
```
This code could fall back to the exclusion route setup in which case we never clean up previously set up sysctl opts. This PR moves the sysctl setup to after the fallback detection
=> [client] Set up sysctl and routing table name only if routing rules are available

client/internal/routemanager/systemops/systemops_linux.go
We allow this condition to match:
```
rules := getSetupRules()
for _, rule := range rules {
if err := addRule(rule); err != nil {
if errors.Is(err, syscall.EOPNOTSUPP) {
log.Warnf("Rule operations are not supported, falling back to the legacy routing setup")
setIsLegacy(true)
return r.setupRefCounter(initAddresses, stateManager)
}
return nil, nil, fmt.Errorf("%s: %w", rule.description, err)
}
}
```
=> [client] Allow routing to fallback to exclusion routes if rules are not supported

client/iface/bind/control_android.go, go.mod, go.sum, util/net/dialer_init_android.go, util/net/listener_init_android.go, util/net/protectsocket_android.go
Support exit node feature on Android via P2P communication
Protect the WireGuard UDP listeners with marks.
The implementation can support the VPN permission revocation events in thread safe way. It will be important if we start to support the running time route and DNS update features.
=> [client] Android exit node via P2P

management/server/peer.go, management/server/peer_test.go, management/server/posture_checks.go
=> [management] refactor to use account object instead of separate db calls for peer update

management/server/route.go, management/server/route_test.go
This fixes the behavior where multiple policies with different access levels were applied to all distribution group peers. 
Now, we ensure that route firewall rules generation will consider source group peers of access control policies and apply rules to peers from these groups. Peers from the distribution group that don't belong to any source group will have their traffic dropped.
This will change behavior for existing and valid policies benefiting from this flaw.
=> [client] Account different policiy rules for routes firewall rules

infrastructure_files/getting-started-with-zitadel.sh
Update Caddyfile and Docker Compose to support HTTP3
Closes #2785 
- [X ] Is a feature enhancement
=> Update Caddyfile and Docker Compose to support HTTP3

client/iface/bind/udp_mux.go
if address is unspecified and it is ipv6 then networks = []ice.NetworkType{ice.NetworkTypeUDP4, ice.NetworkTypeUDP6}
https://github.com/netbirdio/netbird/issues/46
=> Unspecified address: default NetworkTypeUDP4+NetworkTypeUDP6

client/anonymize/anonymize.go, client/anonymize/anonymize_test.go, client/server/debug.go, client/server/debug_test.go
Adds the `state.json` file to the debug bundle.
Example content:
```json
{
"dns_state": {
"DNSAddress": "",
"ManagerType": 3,
"WgIface": "wt0"
},
"iptables_state": {
"acl_entries": {
"FORWARD": [
[
"-i",
"wt0",
"-j",
"DROP"
],
[
"-i",
"wt0",
"-j",
"NETBIRD-RT-FWD"
],
[
"-o",
"wt0",
"-m",
"conntrack",
"--ctstate",
"RELATED,ESTABLISHED",
"-j",
"ACCEPT"
],
[
"-m",
"mark",
"--mark",
"0x1bd01",
"-j",
"NETBIRD-ACL-INPUT"
]
],
"INPUT": [
[
"-i",
"wt0",
"-j",
"DROP"
],
[
"-i",
"wt0",
"-j",
"NETBIRD-ACL-INPUT"
],
[
"-i",
"wt0",
"-m",
"conntrack",
"--ctstate",
"RELATED,ESTABLISHED",
"-j",
"ACCEPT"
]
],
"OUTPUT": [
[
"-o",
"wt0",
"-j",
"DROP"
],
[
"-o",
"wt0",
"-j",
"NETBIRD-ACL-OUTPUT"
],
[
"-o",
"wt0",
"!",
"-d",
"100.89.214.39/16",
"-j",
"ACCEPT"
],
[
"-o",
"wt0",
"-m",
"conntrack",
"--ctstate", …
```
=> [client] Add state file to debug bundle

client/system/info.go, client/system/info_darwin.go, client/system/info_linux.go, client/system/info_windows.go, client/system/static_info.go, client/system/sysinfo_linux_test.go
Get static system info once for Windows, Darwin, and Linux nodes
This should improve startup and peer authentication times
=> [client] Get static system info once

client/internal/engine.go, management/server/account_test.go
cleanup leftovers from status recorder when stopping the engine
=> [client] Cleanup status resources on engine stop

client/internal/routemanager/systemops/systemops_linux.go
=> [client] Don't return error in rule removal if protocol is not supported

client/internal/routemanager/manager.go
Makes sure the route selector is initialized even if custom routing is disabled or we error out early.
=> [client] Init route selector early

client/internal/peer/conn.go
setting rand time range to 100-300ms instead of 100-800ms
=> Reduce max wait time to initialize peer connections

client/internal/engine.go, client/internal/peer/conn.go, client/internal/peer/conn_test.go, util/semaphore-group/semaphore_group.go, util/semaphore-group/semaphore_group_test.go
Limit the peer connection initialization at 200 peers at the same time
=> [client] Add peer conn init limit

client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/manager.go, client/internal/engine.go
=> DNS forwarder

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handlers/policies/policies_handler.go, management/server/http/handlers/policies/policies_handler_test.go, management/server/networks/resources/types/resource.go, management/server/types/policyrule.go, management/server/types/resource.go
=> [management] Extends policy with source and destination resources

management/server/account.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handlers/networks/handler.go, management/server/http/handlers/networks/resources_handler.go, management/server/http/handlers/networks/routers_handler.go, management/server/mock_server/account_mock.go, management/server/networks/manager.go, management/server/networks/resources/manager.go, management/server/networks/resources/types/resource.go, management/server/networks/resources/types/resource_test.go, management/server/networks/routers/manager.go, management/server/networks/routers/types/router.go, management/server/networks/types/network.go, management/server/permissions/manager.go, management/server/settings/manager.go, management/server/status/error.go, management/server/store/sql_store.go, management/server/store/store.go, management/server/users/manager.go
=> [management] Add managers to link networks API with store

client/internal/dns/handler_chain.go, client/internal/dns/handler_chain_test.go, client/internal/dns/mock_server.go, client/internal/dns/server.go, client/internal/dns/service_memory.go, client/internal/dns/upstream.go, client/internal/dnsfwd/forwarder.go, client/internal/engine_test.go, client/internal/routemanager/dnsinterceptor/handler.go, client/internal/routemanager/dynamic/route.go, dns/dns.go, go.mod, go.sum
=> Add handler chains

client/internal/engine.go, client/internal/routemanager/client.go, client/internal/routemanager/manager.go, client/internal/routemanager/manager_test.go, client/internal/routemanager/mock.go
=> Use DNS route feature flag

client/ui/client_ui.go
fyne.io/systray package [calls onTrayReady before fully initializing](https://github.com/fyne-io/systray/blob/v1.11.0/systray_unix.go#L161), causing some calls (e.g SetIcon) to [fail silently](https://github.com/fyne-io/systray/blob/v1.11.0/systray_unix.go#L58-L60) because `props` global variable inside systray package is not yet set, while the [MenuItems can be updated normally without failure](https://github.com/fyne-io/systray/blob/v1.11.0/systray.go#L213-L223).
This causes netbird-ui icon to stay stuck on Disconnected if netbird service was running and connected before netbird-ui starts up.
This is mainly a workaround since the [issue in systray is not responsive](https://github.com/fyne-io/systray/issues/35).
=> [client] Fix race condition with systray ready

.github/workflows/golang-test-darwin.yml, .github/workflows/golang-test-linux.yml, .github/workflows/golang-test-windows.yml
=> [misc] split tests with management and rest

client/internal/peer/worker_ice.go
Check for IPv6 addresses during hole punching, adding brackets around them as needed
#2327 and #2606
=> fix: reformat IPv6 ICE addresses when hole punching

infrastructure_files/getting-started-with-zitadel.sh
When I remove 80 http port in Caddyfile, netbird client cannot connect server:443. Logs show error below: {"level":"debug","ts":1733809631.4012625,"logger":"http.stdlib","msg":"http: TLS handshake error from redacted:41580: tls: client requested unsupported application protocols ([h2])"} I wonder here h2 protocol is absent.
- [✓] Is it a bug fix
=> fix client unsupported h2 protocol when only 443 activated

client/iface/device/kernel_module_linux.go
Used the values as resolved when the first iota value was the second const in the block.
See example: https://go.dev/play/p/bMReMFC9anU
=> [client] Avoid using iota on mixed const block

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/networks/resources/types/resource.go
=> [management] Revert to using address field in api

management/cmd/management.go, management/server/groups/manager.go, management/server/http/handlers/networks/resources_handler.go, management/server/networks/manager_test.go, management/server/networks/resources/manager.go, management/server/networks/resources/manager_test.go, management/server/networks/resources/types/resource.go, management/server/store/sql_store.go, management/server/store/sql_store_test.go, management/server/store/store.go
=> [management] properly add and remove resources from groups

management/server/route_test.go, management/server/types/account.go, management/server/types/account_test.go
=> [management] Account for routing source peers 

management/server/route_test.go, management/server/types/account.go
=> [management] Fix duplicate resource routes when routing peer is part of the source group

.github/workflows/golangci-lint.yml, management/server/metrics/selfhosted.go, management/server/metrics/selfhosted_test.go
=> [management] add selfhosted metrics for networks

client/internal/dns/handler_chain.go, client/internal/dns/handler_chain_test.go
=> [client] Ignore case when matching domains in handler chain

client/firewall/iptables/manager_linux.go, client/internal/dnsfwd/manager.go, client/internal/engine.go
=> [client] Allow inbound rosenpass port

management/server/account.go, management/server/account_test.go, management/server/http/middleware/auth_middleware.go, management/server/jwtclaims/extractor.go
Fix unintended removal of synced JWT groups when accessing the API with PAT.
Fixes #3127
=> [management] Preserve jwt groups when accessing API with PAT

management/server/http/testing/integration/setupkeys_handler_integration_test.go, management/server/types/account.go, management/server/types/account_test.go
If the peer is a router and it would be added to the accessible peers part of the network map. This PR excludes a peer so it is not shown as connecting to itself.
=> [management] exclude self from network map if self is routing peer

relay/server/listener/ws/listener.go
Properly format IPv6 addresses found in `X-Real-IP` headers to avoid errors on the call to `net.ResolveTCPAddr`. IPv6 addresses need to be formatted `[1234::abcd]:443`, which is handled automatically by `net.JoinHostPort`.
=> Handle IPv6 addresses in X-Real-IP header on relay service

client/internal/engine.go, client/internal/peer/status.go
=> [client] Prevent local routes in status from being overridden by updates

client/internal/routemanager/systemops/systemops_linux.go
=> [client] Don't fail on v6 ops when disabled via kernel params

client/ssh/login.go, client/ssh/lookup.go, client/ssh/lookup_darwin.go
=> [client] Allow ssh to rootless netbird

client/internal/dns/host_unix.go
If the inner host manager init fails, we will be left with a non-nil `s.hostManager` despite the inner value being nil. Any `s.hostManager != nil` check will pass, but method calls on this struct will panic.
=> [client] Fix a panic on shutdown if dns host manager failed to initialize

relay/client/client.go, relay/messages/message.go, relay/messages/message_test.go, relay/server/handshake.go, relay/server/peer.go
Code cleaning
- Keep message byte processing in message.go file
- Add new unit tests
=> [relay] Code cleaning in message marshalling

client/system/info_android.go
Hello please find the propagation of android device serial
=> [client>android] add serial, product model, product manufacturer

client/firewall/iptables/acl_linux.go, client/firewall/iptables/manager_linux.go, client/firewall/iptables/manager_linux_test.go, client/firewall/manager/firewall.go, client/firewall/nftables/acl_linux.go, client/firewall/nftables/manager_linux.go, client/firewall/nftables/manager_linux_test.go, client/firewall/uspfilter/rule.go, client/firewall/uspfilter/uspfilter.go, client/firewall/uspfilter/uspfilter_bench_test.go, client/firewall/uspfilter/uspfilter_test.go, client/internal/acl/manager.go, client/internal/acl/manager_test.go, client/internal/dnsfwd/manager.go, client/internal/engine.go
`OUTPUT` chains are unused and obsolete, only the userspace filter still uses them for hooks
=> [client] Remove outbound chains

management/server/group.go, management/server/http/handlers/groups/groups_handler.go, management/server/http/handlers/groups/groups_handler_test.go, management/server/networks/resources/manager.go
=> [management] fix groups delete and resource create and update error response

relay/client/dialer/quic/quic.go, relay/server/listener/quic/listener.go
Fixes an issue on macOS where the server throws errors with default settings:
`failed to write transport message to: DATAGRAM frame too large.`
Further investigation is required to optimize MTU-related values.
=> [relay] Set InitialPacketSize to the maximum allowable value

.github/workflows/golang-test-freebsd.yml, client/ui/client_ui.go, client/ui/font_bsd.go, client/ui/font_darwin.go, client/ui/network.go
=> [client] Allow freebsd to build netbird-ui

client/server/debug.go
=> [client] Use correct stdout/stderr log paths for debug bundle on macOS

client/internal/statemanager/manager.go, client/server/debug.go
=> [client] Back up corrupted state files and present them in the debug bundle

client/firewall/iptables/acl_linux.go, client/firewall/iptables/rule.go, client/firewall/nftables/acl_linux.go, client/firewall/nftables/rule_linux.go
=> [client] Mark redirected traffic early to match input filters on pre-DNAT ports

management/server/peer.go
=> [manageemnt] port forwarding add peer manager fix network map

client/cmd/testutil_test.go, client/internal/engine_test.go, client/server/server_test.go, management/client/client_test.go, management/server/account_test.go, management/server/dns_test.go, management/server/http/testing/testing_tools/tools.go, management/server/integrations/port_forwarding/controller.go, management/server/management_proto_test.go, management/server/management_test.go, management/server/nameserver_test.go, management/server/peer_test.go, management/server/peers/manager.go, management/server/route_test.go
=> [management] fix testing tools

client/firewall/iptables/router_linux.go, client/firewall/nftables/router_linux.go, client/internal/routemanager/ipfwdstate/ipfwdstate.go, client/internal/routemanager/server_nonandroid.go, client/internal/routemanager/systemops/systemops_linux.go
Add new package ipfwdstate that implements reference counting for IP forwarding 
state management. This allows multiple usage to safely request IP forwarding
without interfering with each other.
TODO:
- Read initial state from system config
- Implement DisableIPForwarding call
=> [client] Manage the IP forwarding sysctl setting in global way

go.mod, go.sum, relay/client/dialer/ws/conn.go, relay/client/dialer/ws/ws.go, relay/server/listener/ws/conn.go, relay/server/listener/ws/listener.go
The nhooyr.io/websocket package was renamed to github.com/coder/websocket when the project was transferred to "coder" as the new maintainer.
Use the new import path and update go.mod and go.sum accordingly.
See #3240 cc @lixmal
=> [relay] Use new upstream for nhooyr.io/websocket package

management/server/grpcserver.go
=> [management] add logs for grpc API

signal/server/signal.go
- Use guardian pattern to reduce control flow depth
- Fixed variable & package name clash
- Propagate ctx in Server.Send
- Enable graceful shutdown in Server.ConnectStream, by honoring <-stream.Context().Done()
=> [signal] Fix context propagation in signal server

client/firewall/iptables/manager_linux.go, client/firewall/manager/firewall.go, client/firewall/nftables/manager_linux.go, client/firewall/uspfilter/uspfilter.go, client/firewall/uspfilter/uspfilter_filter_test.go, client/internal/routemanager/manager.go, client/internal/routemanager/server_android.go, client/internal/routemanager/server_nonandroid.go
=> [client] Enable userspace forwarder conditionally

client/internal/dns/host_windows.go, client/internal/dns/unclean_shutdown_windows.go
=> [client] Use GPO DNS Policy Config to configure DNS if present

management/server/account.go, management/server/activity/sqlite/sqlite.go, management/server/http/handlers/events/events_handler_test.go, management/server/http/handlers/users/users_handler_test.go, management/server/http/testing/benchmarks/users_handler_benchmark_test.go, management/server/mock_server/account_mock.go, management/server/user.go, management/server/user_test.go
Refactor user info retrieval during deletion to avoid loading the entire account for each user.
=> [management] Optimize user bulk deletion 

management/server/store/sql_store.go, management/server/store/sql_store_test.go
Introduces batching support for `SaveUsers` and `SaveGroups` to improve performance when handling large datasets.
=> [management] Add batching support for SaveUsers and SaveGroups

client/ui/client_ui.go, client/ui/icons.go, client/ui/icons_windows.go
Instead of embedding icons and PNGs in every binary, embedded them only in the respective binaries that require it
=> Use go build to embed less icons

client/server/server.go
Closes https://github.com/netbirdio/netbird/issues/3253
=> [client] Skip CLI session expired notifcation if notifications are disabled

client/firewall/uspfilter/forwarder/udp.go
Previously the deadline was set to a specific time in the future in the beginning but never updated.
This prevents the code from reaching the last seen update. Eventually the connection is cut off due to timeout.
=> [client] Fix udp forwarder deadline

.goreleaser_ui.yaml, release_files/ui-post-install.sh
Add post-install script to netbird-ui deb and rpm packages to restart process if running.
=> [client] Restart netbird-ui post-install in linux deb&rpm

management/server/account.go, management/server/store/sql_store.go, management/server/store/sql_store_test.go, management/server/store/store.go, management/server/testdata/store_with_expired_peers.sql, management/server/testdata/storev1.sql, management/server/types/account.go
Faster server bootstrap by counting accounts rather than fetching all from storage in the account manager instantiation.
This change moved the deprecated need to ensure accounts have an All group to tests instead.
=> [management] faster server bootstrap

client/iface/configurer/kernel_unix.go, client/iface/configurer/usp.go, client/iface/device/interface.go, client/iface/iface.go, client/iface/iface_test.go, client/internal/engine.go, client/internal/engine_test.go, client/internal/iface_common.go, client/internal/peer/conn.go, client/internal/peer/iface.go, client/internal/peerstore/store.go, client/internal/rosenpass/manager.go, client/internal/routemanager/dnsinterceptor/handler.go
The allowedIPs is a string type and it causes inconsistency. It could be:
- "100.108.186.247"
- "100.108.186.247/32"
- "100.108.186.247/32,100.108.186.2/32"
In this PR convert allowed IP variable type to netip.Prefix
=> [client] Replace string to netip.Prefix

client/ui/client_ui.go
Adding Netbird GitHub Link to the Client UI About Sub Menu
-
Mandatory in my opinion. You are free to decline/reject this PR if you like or if it isn't qualified (a reason would be nice then). Thanks anyway for the efforts guys.
=> [client] Add Netbird GitHub link to the client ui about sub menu

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/icmp_test.go, client/firewall/uspfilter/uspfilter.go
This tracks ICMP echo/reply with ID only. This will make multiple consequent pings part of the same icmp session, aligned with how linux conntrack does it.
=> Track icmp with id only

client/iface/bind/ice_bind.go, client/iface/wgproxy/bind/proxy.go, client/internal/peer/conn.go
- When a peer is connected with TURN and a Relay connection is established, do not force switching to Relay. Keep using TURN until disconnection.
- In the proxy preparation phase, the Bind Proxy does not set the remote `conn` as a fake address for Bind. When running the Work() function, the proper proxy instance updates the `conn` inside the Bind.
This change breaks the **[client] Fix/pkg loss #3338** PR.
=> [client] Fix TURN-Relay switch

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/tcp.go, client/firewall/uspfilter/conntrack/udp.go, client/firewall/uspfilter/uspfilter.go
We already have rule IDs in blocked events, this one adds rule IDs to allowed events for peer traffic
=> Add peer traffic rule IDs to allowed connections in flows

client/embed/embed.go, client/internal/connect.go, client/server/server.go
The "runningChan" provides feedback to the UI or any client about whether the service is up and running. If the client exits earlier than when the service successfully starts, then this channel causes a block.
- Added timeout for reading the channel to ensure we don't cause blocks for too long for the caller
- Modified channel writing operations to be non-blocking
=> [client] Prevent to block channel writing

management/server/http/handlers/networks/handler.go, management/server/http/handlers/networks/resources_handler.go, management/server/http/handlers/networks/routers_handler.go
The network's endpoints were returning null when a GET request was run on 0 elements. This PR returns an empty array now to keep in sync with the responses of the other endpoints
=> [management] return empty array instead of null on networks endpoints

client/ui/font_windows.go
Fix #3345 and #2603
Fix Advanced Setting cannot open by reverting default font for Windows 10/11/2022 platform.
=> [client] Fix Advanced Setting unable to open on Windows 11 with Chinese Locale Setting

management/server/http/handlers/networks/resources_handler.go
When creating a network resource, the "Enabled" field in the NetworkResourceRequest was forced to true, thus not respecting the requested state of the "Enabled" field. This PR removes the forced true state of the "Enabled" field.
=> [management] Fix always enabling of NetworkResource in createResource()

client/internal/dns/host_windows.go
- The registry key that is currently used to check if the client is in GPO mode or not is not correct. You can have DNSClient key present if you define other DNS settings by GPO (Ex: Disable Netbios, disable mutlicast, ...) but not using GPO to configure Nrpt policies.
- When client is in GPO mode, there is no need to push the local policy configuration as this entry will be discared. The way of Microsoft to check if there is NRPT settings configured by GPO is to check the DnsPolicyConfig key is present (That's why it's coherent to check that key and not the DNSClient key)
> If any NRPT settings are configured in domain Group Policy, then all local Group Policy NRPT settings are ignored
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn593 …
=> [client] Fix DNS Nrpt policies

client/firewall/uspfilter/uspfilter.go, client/internal/netflow/manager.go
The code was bypassing inbound tracking if the packet was passed to the virtual stack in netstack mode, this PR fixes that.
=> [client] Fix flows for embedded listeners

management/server/policy.go
We should not send port range when a port is set or when protocol is all or icmp
=> [management] Fix invalid port range sync

.github/workflows/golangci-lint.yml, management/server/group.go, management/server/group_test.go
- Updates account peers when a group linked to a network router is modified
- Prevents group deletion if it's still being used by any network router
=> [management] Sync account peers on network router group changes

go.mod, go.sum, management/server/grpcserver.go, management/server/token_mgr.go
=> [management] Fix extended config when nil

client/internal/peer/conn.go, client/internal/peer/worker_ice.go
Prevent calling the onDisconnected callback if the ICE connection has never been established
If call onDisconnected without onConnected then overwrite the relayed status in the conn priority variable.
=> [client] Prevent calling the onDisconnected callback in incorrect state

client/internal/auth/pkce_flow.go
With this change, browser sessions won't be considered for CLI authentication, and credentials will be requested.
=> [client] Force new user login on PKCE auth in CLI (behavior change)

client/iface/bind/udp_mux.go, client/iface/bind/udp_mux_universal.go, client/internal/peer/ice/agent.go, formatter/hook/hook.go, util/log.go
set default for hook when caller is not set
based on #3585
gRPC logs:
```
2025-03-29T16:05:30+01:00 INFO ./caller_not_available:0: 2025/03/29 16:05:30 INFO: [core] [Channel #3]Channel switches to new LB policy "pick_first"
2025-03-29T16:05:30+01:00 INFO ./caller_not_available:0: 2025/03/29 16:05:30 INFO: [core] [Channel #3 SubChannel #4]Subchannel created
```
ICE logs:
```
2025-03-29T16:07:28+01:00 INFO ./caller_not_available:0: ice WARNING: 2025/03/29 16:07:28 Discard message from (udp4 host 94.237.63.127:51820), unknown TransactionID 0x2aafb8441436fadf118fe929
2025-03-29T16:07:28+01:00 INFO ./caller_not_available:0: ice TRACE: 16:07:28.987802 agent.go:1105: Inbound STUN (Request) from 94.237.63.127:51820 to udp4 srflx 94.134.125.44:12343 related 0.0.0.0:51000, useCandidate: false …
```
=> [client] Use the netbird logger for ice and grpc

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/tcp.go, client/firewall/uspfilter/conntrack/tcp_bench_test.go, client/firewall/uspfilter/conntrack/tcp_test.go, client/firewall/uspfilter/conntrack/udp.go
- Handle Rst in both directions properly
- Remove IsEstablished
- Eliminate mutex
- Fix first state for inbound conns
- Update counters before terminating conns
- Create new conns for packets with Syn flag only
- Add more tests
=> [client] Improve TCP conn tracking

client/firewall/iptables/router_linux.go, client/firewall/iptables/router_linux_test.go, client/firewall/nftables/acl_linux.go, client/firewall/nftables/router_linux.go, client/firewall/nftables/router_linux_test.go, client/iface/configurer/usp.go, client/internal/netflow/conntrack/conntrack.go, client/internal/netflow/types/types.go, client/internal/routemanager/systemops/systemops_linux.go, util/net/env_linux.go, util/net/net.go, util/net/net_linux.go
This change enables site2site traffic flow support in kernel mode.
Packets in and out of the NetBird interface mark the associated connection with the respective fwmark (per direction).
This is then used to filter events from the conntrack socket and determine the conn direction.
=> [client] Mark netbird data plane traffic to identify interface traffic correctly

client/internal/dns/file_unix.go, client/internal/dns/handler_chain.go, client/internal/dns/handler_chain_test.go, client/internal/dns/host.go, client/internal/dns/host_darwin.go, client/internal/dns/host_windows.go, client/internal/dns/mock_server.go, client/internal/dns/network_manager_unix.go, client/internal/dns/server.go, client/internal/dns/server_test.go, client/internal/dns/systemd_linux.go, client/internal/dns/upstream.go, client/internal/dns/upstream_android.go, client/internal/dns/upstream_ios.go, client/internal/dns/upstream_test.go, client/internal/routemanager/dnsinterceptor/handler.go, client/internal/routemanager/dynamic/route.go, client/internal/routemanager/dynamic/route_generic.go, client/internal/routemanager/dynamic/route_ios.go, client/server/network.go, management/domain/domain.go
- Increase dns route upstream query timeout
- Set up match domains for dns routes
- Fix reverse zone search domains
- Flush dns cache on Windows
- Handle non-A/AAAA queries by next handler in chain
=> [client] Automatically register match domains for DNS routes

client/internal/dns/local.go
=> [client] Support CNAME in local resolver

management/server/updatechannel.go, management/server/updatechannel_test.go
Replaced write lock with read lock for peerChannels map access where only read operations are performed
=> [management] Refactor/management/updchannel

client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/forwarder_test.go
[client] Refactor DNSForwarder to improve  handle wildcard domain resource id matching
=> [client] Refactor DNSForwarder to improve  handle wildcard domain resource id matching

release_files/install.sh
Fix install.sh for some installations by explicitly setting the file permissions correctly.
https://github.com/netbirdio/netbird/issues/1168
=> [misc] update gpt file permissions in install.sh

client/internal/engine.go, client/internal/peer/conn.go, client/internal/peer/conn_test.go, client/internal/peer/handshaker.go
Between two agents, if both have enabled Rosenpass but only one side is set to permissive mode, the WireGuard handshake never occurs.
Figure out the proper preshared key setting for WrieGuard after the connection, based on the offer-answer signaling messages.
=> [client] Fix Rosenpass permissive mode handling

management/server/http/handler.go, management/server/http/middleware/auth_middleware.go, management/server/http/middleware/auth_middleware_test.go
=> [management] fix lastLogin on dashboard

client/ui/network.go
When deselecting a single exit node in the menu the exit node was deselected but the checkbox wasn't unchecked properly. This fixes it
=> [client] Fix exit node deselection

client/firewall/iptables/router_linux.go, client/firewall/nftables/router_linux.go
In some cases there is a conflict between to-be-masqueraded and to-be-redirected packets (e.g. by Docker). In that case we need to make sure the redirect mark is applied. So these rules always go last while nat rules always go first.
=> [client] Ensure dst-type local marks can overwrite nat marks

client/cmd/login.go
=> Move static check when running on foreground

.github/workflows/golang-test-linux.yml
=> [misc] Exclude client benchmarks from CI

release_files/install.sh
[client] Add macOS .pkg installer support to installation script and use .pkg installer default
=> [client] Add macOS .pkg installer support to installation script

management/client/grpc.go
=> [client] Revert mgm client error handling

client/cmd/root.go, client/ui/client_ui.go, client/ui/debug.go, upload-server/types/upload.go
=> [client] Add debug upload option to netbird ui

client/cmd/debug.go, client/server/debug.go, client/ui/client_ui.go, client/ui/debug.go, client/ui/network.go
=> [client] Add debug for duration option to netbird ui

client/internal/conn_mgr.go, client/internal/engine.go, client/internal/lazyconn/manager/manager.go
Fix the exclude list handling. When the agent gets a new network map, it manages the changes in the excluded peers.
Cases:
- Extend the exclude list with a new peer: start permanent peer connection
- Remove a peer from the exclude list: we do not know the actual state of the peer connection, so we must suppose it is not in "**idle**". Start the `inactivity listener` for peer.
- If a peer is newly created in the management server and it will be in exclude list (i.e. it is a router) then the manager can not start the connection immediately because the `peer.Conn` is not exist yet. It is normal and the engine code will create the peer and start the connection in the next step.
=> [client] Automatically start the connection if exclude list is changing

management/server/migration/migration.go, management/server/migration/migration_test.go, management/server/networks/resources/types/resource.go, management/server/networks/routers/types/router.go, management/server/networks/types/network.go, management/server/store/sql_store.go, management/server/store/sql_store_test.go, management/server/store/store.go, management/server/types/group.go
=> [management] add gorm tag for primary key for the networks objects

relay/client/dialer/quic/quic.go
This sets ServerName in the TLS config when using hostnames to fix the validation.
Potentially fixes #3672
=> [client] set TLS ServerName for hostname-based QUIC connections

management/server/store/sql_store.go
=> [management] removal of foreign key constraint enforcement on sqlite

management/client/rest/accounts.go, management/client/rest/dns.go, management/client/rest/events.go, management/client/rest/geo.go, management/client/rest/groups.go, management/client/rest/networks.go, management/client/rest/peers.go, management/client/rest/policies.go, management/client/rest/posturechecks.go, management/client/rest/routes.go, management/client/rest/setupkeys.go, management/client/rest/tokens.go, management/client/rest/users.go
Fixes panic occurring when body is nil (this usually happens when connections is refused) due to lack of nil check by centralizing `response.Body.Close()` behavior.
https://github.com/netbirdio/kubernetes-operator/issues/21
=> [management/client/rest] fix panic when body is nil

management/server/account.go, management/server/account_test.go
=> [management] Delete service users with account manager

client/internal/conn_mgr.go, client/internal/engine.go
This is a chicken-and-egg problem. The exclude list depends on the peer store. So we must fill the peer store, and because of it, the engine creates the lazy activity listeners. Just in the next step, when we update the exclude list, update the connection to permanent state.
=> Fix exclude list handling

signal/peer/peer.go, signal/server/signal.go
=> [signal] adjust signal log levels 2

client/internal/routemanager/notifier/notifier.go
If we get domain routes the Network prefix variable in route structure will be invalid (engine.go:1057). When we handower to Android the routes, we must to filter out the domain routes. If we do not do it the Android code will get "invalid prefix" string as a route.
=> [client, android] Do not propagate empty routes

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> [management] Add connection type filter to Network Traffic API

client/internal/dns/systemd_linux.go
=> [client] Disable dnssec for systemd explicitly

management/server/account.go
=> [management] Make startup period configurable

client/installer.nsis
=> [client] Offer to remove netbird data in windows uninstall

management/cmd/management.go, management/server/store/sql_store.go, management/server/store/store.go, management/server/store/store_test.go
=> [management] add flag to disable auto-migration

client/ui/client_ui.go, version/update.go
=> [client] Fix UI new version notifier

client/internal/acl/manager.go, client/internal/engine.go
v0.40.0 switched the order of applying ACLs and routes, making setting up legacy management too late. So, we moved it to an earlier place in the network map update.
Fixes #3841
=> [client] Fix legacy routes when connecting to mgmt servers older than v0.30.0

client/internal/netflow/manager.go, management/client/grpc.go
- Do not reconnect to mgm server in case of handler error
- Set to nil the flow grpc client to prevent double close call
=> [client] Do not reconnect to mgm server in case of handler error

management/server/nameserver.go, management/server/nameserver_test.go
=> [management] Extend nameserver match domain validation

client/internal/engine.go
=> [client] avoid overwriting state manager on iOS

management/client/rest/accounts_test.go, management/client/rest/client.go
Fixes panic when response has no body or body does not conform to `management/server/http/util.(ErrorResponse)`
=> [management/client/rest] Fix panic on unknown errors

management/server/user.go
=> [management] Fix user groups propagation

management/client/rest/client.go, management/client/rest/impersonation.go, management/client/rest/impersonation_test.go, management/client/rest/options.go, management/server/types/settings.go
Ability to return a REST Client impersonated for a specific account
=> [management] REST client impersonation

client/ui/client_ui.go, client/ui/network.go
* Add "Deselect All" Menu Item to Exit Node Menu
* Only rebuild the Exit Nodes menu if the state is changed.
=> [client] Add "Deselect All" Menu Item to Exit Node Menu

client/ui/client_ui.go, client/ui/process/process.go
=> [client] Log duplicate client ui pid

client/anonymize/anonymize.go, client/iface/configurer/kernel_unix.go, client/iface/configurer/usp.go, client/iface/configurer/wgshow.go, client/iface/device/interface.go, client/iface/iface.go, client/internal/debug/debug.go, client/internal/debug/wgshow.go, client/internal/engine.go, client/internal/engine_test.go, client/internal/iface_common.go, client/internal/peer/status.go
Add output similar to wg show to the debug package.
=> [client] Add output similar to wg show to the debug package

client/internal/dns/handler_chain.go
This combines several log lines into one. On a busy machine those could become detached from each other and it was impossible to read.
=> [client] Improve dns match trace log

client/internal/dns/host_windows.go
- run ipconfig /registerdns before flushing
- disable WINS on the netbird interface
- disable "dynamic updates" and "registration enabled" on the interface
=> [client] Run registerdns before flushing

release_files/install.sh
This PR fixes the issue https://github.com/netbirdio/netbird/issues/3014.
`dnf config-manager` is useful for adding a remote  `repo` file but the `add_rpm_repo` function called on line 264 already writes the `repo` to the appropriate location and therefore when `dnf config-manager` is ran it raises an error stating that the repo already exists. This causes the script to stop and prevents the installation from completing. Users have found adding `--overwrite` to `dnf config-manager` works (https://github.com/netbirdio/netbird/issues/3014#issuecomment-2621112511) but this is unnecessary to begin with.
https://github.com/netbirdio/netbird/issues/3014.
> By submitting this pull request, you confirm that you have read and agree to the terms of the [Contributor License …
=> remove error causing dnf config-manager add

client/internal/engine.go, client/internal/relay/relay.go
=> [client] Increase stun status probe timeout

client/internal/conn_mgr.go, client/internal/engine.go, client/internal/lazyconn/manager/manager.go
In the conn_mgr we must distinguish two contexts. One is relevant for lazy-manager, and one (engine context) is relevant for peer creation. If we use the incorrect context, then when we disable the lazy connection feature, we cancel the peer connections too, instead of just the lazy manager.
=> [client] Refactor context management in ConnMgr for clarity and consistency

client/internal/dns/local/local.go, client/internal/dns/local/local_test.go
This fixes search domains on alpine in particular, where the system resolver returns an error `bad address` if 
- the `A` respone is fine
- the `AAAA` is something other than `NOERROR`
=> [client] Fix local resolver returning error for existing domains with other types

client/ui/client_ui.go
=> [client] Fix unnecessary UI updates

signal/cmd/env.go, signal/cmd/run.go
Hello, I like the idea of being able to configure the services from an env file for the relay service (e.g `NB_LISTEN_PORT`), so I copied this to the relay service.
I did not test nor compile the code, just did what looked correct.
If it happens to be correct, I'll also do it with the other services (management).
Once merged, we should be able to go from:
``` yaml
signal:
image: netbirdio/signal:$NETBIRD_SIGNAL_TAG
command: ["--letsencrypt-domain", "foo.com", "--ssl-dir", "/etc/letsencrypt"]
```
To:
``` yaml
signal:
image: netbirdio/signal:$NETBIRD_SIGNAL_TAG
environment:
NB_LETSENCRYPT_DOMAIN: foo.com
NB_SSL_DIR: /etc/letsencrypt
```
Or better use an `env_file` and have better agnosticism in the docker-compose file.
> By submitting this pull request, you confirm that you have read and …
=> Set signal flags from environment variables

client/internal/dns/upstream_android.go, client/internal/dns/upstream_general.go, client/internal/routemanager/client/client.go, client/internal/routemanager/dnsinterceptor/handler.go
This makes iOS use the private dialer, which is required for dns traffic into the tunnel. DNS interceptor upstream traffic always is, so we use it unconditionally.
Addtionally, this switches the hardcoded old dns approach (pre-resolve) to depend on whatever setting is configured in the management.
=> [client] Support wildcard DNS on iOS

management/server/peer.go, management/server/policy_test.go, management/server/posture/nb_version.go, management/server/posture/nb_version_test.go, management/server/types/account.go, management/server/types/firewall_rule.go
This PR adds backward compatibility for clients with versions prior to `v0.48.0` that do not support port range firewall rules. For these older clients, port ranges are expanded into individual ports during network map generation.
=> [management] Add backward compatibility for older clients without firewall rules port range support

client/ui/client_ui.go
This PR refactors showLoginURL to improve error handling and connection status checks by delaying the login fetch until user interaction and closing the pop-up if already connected.
- Moved s.login(false) call into the click handler to defer network I/O.
- Added a conn.Status check after opening the URL to skip reconnection if already connected.
- Enhanced error logs for missing verification URLs and service status failures.
=> [client] Refactor showLoginURL to improve error handling and connection status checks

client/ui/client_ui.go, management/cmd/management.go, version/update.go, version/update_test.go
This PR enhances the version checker to send a custom User-Agent header when polling for updates, and configures both the management CLI and client UI to use distinct agents. 
- NewUpdate now takes an `httpAgent` string to set the User-Agent header.
- `fetchVersion` builds a custom HTTP request (instead of `http.Get`) and sets the User-Agent.
- Management CLI and client UI now pass `"nb/management"` and `"nb/client-ui"` respectively to NewUpdate.
- Tests updated to supply an `httpAgent` constant.
- Logs if there is a new version available for management
=> [management] check and log on new management version

infrastructure_files/getting-started-with-zitadel.sh
=> [misc] getting-started-with-zitadel.sh: drop unnecessary port 8080

client/internal/config.go, client/internal/connect.go, client/internal/connect_test.go
Support for random WireGuard ports has been added. You can now run:
```shell
netbird up --wireguard-port 0
```
to let the system automatically select a random available port.
This option can be helpful when running multiple devices in some NATed networks to achieve P2P connections. 
Note: When upgrading from clients older than [v0.25.4](https://github.com/netbirdio/netbird/releases/tag/v0.25.4), the WireGuard connection port will be replaced with a randomly assigned port.
=> [client] Support random wireguard port on client

management/server/peer.go, management/server/status/error.go
management: replace `invalid user` with a clear error message about mismatched logins
=> [management] provide clear error message about mismatched logins

management/server/store/sql_store.go
If a lock is not specified when retrieving account peers do not include it in the query.
=> [management] fix store get account peers without lock

management/server/peer.go
=> [management] Remove deleted user peers from groups on user deletion

.github/workflows/mobile-build-validation.yml, client/android/client.go, client/android/exec.go
On Android 11 (SDK <= 30) and earlier, pidfd-related system calls are blocked by seccomp policies, causing SIGSYS crashes.
This change overrides `checkPidfdOnce` to return an error on affected versions, preventing the use of unsupported pidfd features.
=> [client] Disable pidfd check on Android 11 and below

management/client/client_test.go, management/server/account/manager.go, management/server/dns_test.go, management/server/ephemeral.go, management/server/ephemeral_test.go, management/server/management_proto_test.go, management/server/mock_server/account_mock.go, management/server/nameserver_test.go, management/server/peer.go, management/server/peer_test.go
…and run BufferUpdateAccountPeers once
currently every ephemeral peer removal cleanup() is run for every peer because of strict timer. we add cleanupWindow to increase the batch of removing peers 
=> [management] added cleanupWindow for collecting several ephemeral peers to delete

management/server/peer.go
Ensures that ephemeral peers are always suffixed with random IP and removes the need to check for existing DNS label by relying on the first attempt constraint hit.
=> always suffix ephemeral peer name

client/iface/bind/activity.go, client/iface/bind/activity_test.go, client/iface/configurer/kernel_unix.go, client/iface/configurer/usp.go, client/iface/device/interface.go, client/iface/iface.go, client/internal/conn_mgr.go, client/internal/engine_test.go, client/internal/iface_common.go, client/internal/lazyconn/activity/listener.go, client/internal/lazyconn/inactivity/manager.go, client/internal/lazyconn/inactivity/manager_test.go, client/internal/lazyconn/manager/manager.go, client/internal/lazyconn/wgiface.go, monotime/time.go
=> [client] Fix elapsed time calculation when machine is in sleep mode

client/iface/netstack/tun.go
This avoids to have in the logs:
```
ERRO client/iface/netstack/tun.go:46: failed to parse NB_NETSTACK_SKIP_PROXY: strconv.ParseBool: parsing "": invalid syntax
```
When you run netbird client in rootless mode and in the absence of the var `NB_NETSTACK_SKIP_PROXY`, you get a parsing error in the logs. People would need to set the variable explicitly to avoid the parsing error in the logs which I don't think it was left like this on purpose?
=> [client] avoid parsing NB_NETSTACK_SKIP_PROXY if empty

relay/client/client.go, relay/client/manager_test.go, relay/client/peer_subscription.go, relay/server/store/listener.go, relay/server/store/notifier.go
Fix nil pointer in Relay conn address
Meanwhile, we create a relayed net.Conn struct instance, it is possible to set the relayedURL to nil.
```
panic: value method github.com/netbirdio/netbird/relay/client.RelayAddr.String called using nil *RelayAddr pointer
```
- Fix relayed URL variable protection
- Protect the channel closing
=> [client] Fix/nil relayed address

relay/client/manager.go
The openConn function no longer blocks the relayAddress function call in manager layer
=> [client, relay] The openConn function no longer blocks the relayAddress function call

client/internal/peer/ice/agent.go, client/internal/peer/ice/env.go
Make ICE failed timeout configurable via NB_ICE_FAILED_TIMEOUT_SEC
We want the NetBird agent to tolerate longer periods of ICE failure. Currently, only the disconnection timeout can be adjusted. However, setting the disconnection timeout longer than the ICE failed timeout is meaningless from ICE’s perspective.
=> [client] make ICE failed timeout configurable

.devcontainer/Dockerfile
Container will fail to build with newer versions of gopls unless golang is updated to 1.24. The latest stable version supporting 1.23 is gopls v0.18.1
Changed gopls@latest to gopls@v0.18.1 in .devcontainer/Dockerfile
github.com/netbirdio/netbird/issues/4238
=> Dockerfile: pin gopls to v0.18.1 (latest that supports golang 1.23)

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/tcp.go, client/firewall/uspfilter/conntrack/udp.go, client/firewall/uspfilter/filter.go, client/firewall/uspfilter/forwarder/endpoint.go, client/firewall/uspfilter/forwarder/icmp.go, client/firewall/uspfilter/forwarder/tcp.go, client/firewall/uspfilter/forwarder/udp.go, client/firewall/uspfilter/log/log.go, client/firewall/uspfilter/log/log_test.go, client/firewall/uspfilter/nat.go
This improves logging performance when logs are off by eliminating the variadic function call.
| Test Case      | Variadic         |  LogN   | Improvement |
|-------------------|-----------------------|-----------------------------|-------------|
| 2 Args - Disabled | 72.75ns, 32B, 1 alloc | 0.85ns, 0B, 0 allocs        | 86x faster  |
| 2 Args - Enabled  | 102.2ns, 35B, 1 alloc | 23.45ns, 0B, 0 allocs       | 4.4x faster |
| 6 Args - Disabled | 112.5ns, 96B, 1 alloc | 0.85ns, 0B, 0 allocs      | 132x faster |
| 6 Args - Enabled  | 124.9ns, 97B, 1 alloc | 38ns, 0B, 0 allocs        | 3.3x faster |
> By submitting this pull request, you confirm that you have read and agree to the terms of the [Contributor License Agreement](https://github.com/netbirdio/netbird/blob/main/CONTRIBUTOR_LICENSE_AG …
=> [client] Improve userspace filter logging performance

client/internal/routemanager/systemops/systemops_linux.go
Prio `100` is used by Cilium and possibly others (100 being a popular number), which conflicts with our rules.
Fixes #2926
=> [client] Increase ip rule priorities to avoid conflicts

LICENSE, LICENSES/AGPL-3.0.txt, LICENSES/BSD-3-Clause.txt, LICENSES/REUSE.toml, README.md, management/LICENSE, relay/LICENSE, signal/LICENSE
Dual license: apply AGPL‑3.0 to management/, signal/, and relay directories (BSD‑3 remains for the rest).
=> License Change to AGPLv3

.github/workflows/forum.yml, .github/workflows/release.yml
=> [misc] Post release to forum

client/internal/dns/file_parser_unix_test.go, client/internal/dns/server.go, client/internal/dns/server_test.go
=> [client] Skip dns upstream servers pointing to our dns server IP to prevent loops

client/Dockerfile, client/netbird-entrypoint.sh
- If the peer is already logged in according to the logs, do not run the up command.
- Increase the default timeout.
=> [client] Do not run up cmd if not needed

client/grpc/dialer.go, management/internals/server/server.go, signal/cmd/run.go, util/wsproxy/server/proxy.go
This eliminates TLS, TCP and any server name mismatches
=> [client,management,signal] Handle grpc from ws proxy internally instead of via tcp

util/wsproxy/server/proxy.go
=> [management,signal] Remove ws-proxy read deadline

client/internal/dnsfwd/cache.go, client/internal/dnsfwd/cache_test.go, client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/forwarder_test.go
[client] Implement DNS query caching in DNSForwarder
.
=> [client] Implement DNS query caching in DNSForwarder

client/internal/peer/conn.go, client/internal/peer/conn_test.go, client/internal/peer/guard/env.go, client/internal/peer/guard/ice_monitor.go, client/internal/peer/guard/sr_watcher.go, client/internal/peer/handshaker.go, client/internal/peer/handshaker_listener.go, client/internal/peer/handshaker_listener_test.go, client/internal/peer/worker_ice.go
When an ICE agent connection was in progress, new offers were being ignored. This was incorrect logic because the remote agent could be restarted at any time.
In this change, whenever a new session ID is received, the ongoing handshake is closed and a new one is started.
- Populate initial candidates in the ICE monitor.
- Ensure the session ID is updated when the agent is recreated. Because of this, the Offer listener is now synchronized with the ICE listener.
- Set the NB_ICE_MONITOR_PERIOD parameter to be configurable for end-to-end testing purposes
Paste the …
=> [client] Recreate agent when receive new session id
