netbirdio/netbird

.goreleaser.yaml, infrastructure_files/config.json, infrastructure_files/docker-compose.yml, management/Dockerfile, management/Dockerfile.debug, management/README.md, management/cmd/root.go
Updated the binary to wiretrustee-mgmt and added documentation for the config file format. Also updated the docker-compose file.
Closes #70
=> Update mgmt binary name and config doc

cmd/up.go, connection/engine_test.go, signal/client.go, signal/signal_test.go
Add support to Server with TLS for the signal client.
Closes #74
=> Support Signal server with TLS 

.github/workflows/golang-test.yml, .goreleaser.yaml, README.md, infrastructure_files/docker-compose.yml, signal/Dockerfile, signal/README.md, signal/cmd/root.go, signal/cmd/run.go, signal/cmd/signal.go, signal/main.go
=> Self contained signal cmd build

go.mod, go.sum, management/server/http/handler/peers.go, management/server/http/handler/setupkeys.go, management/server/http/handler/util.go, management/server/http/middleware/handler.go, management/server/http/server.go
Setting basic CORS headers, let's confirm the implications here and define more fine-grained headers in the near future.
=> Add cors headers

client/cmd/login_test.go, client/cmd/up_test.go, client/testdata/store.json, management/server/account.go, management/server/account_test.go, management/server/file_store.go, management/server/http/handler/setupkeys.go, management/server/management_test.go, management/server/setupkey.go, management/server/setupkey_test.go, management/server/testdata/store.json
=> extend setup key logic

client/cmd/login_test.go, client/cmd/up_test.go, client/testdata/store.json, management/server/account.go, management/server/account_test.go, management/server/config.go, management/server/file_store.go, management/server/http/handler/setupkeys.go, management/server/http/server.go, management/server/management_test.go, management/server/setupkey.go, management/server/setupkey_test.go, management/server/testdata/store.json
Serving static UI Dashboard files by Management HTTP server is no necessary anymore
=> Mgmt remove http static files

management/server/account.go, management/server/file_store.go, management/server/http/handler/peers.go, management/server/http/handler/setupkeys.go, management/server/http/handler/util.go, management/server/http/server.go, management/server/peer.go, management/server/store.go
=> Extend peer http endpoint

.github/workflows/release.yml, .goreleaser.yaml, README.md
=> Add homebrew tap

README.md
Adding windows installer documentation
closes #108
=> Add windows installer documentation

.goreleaser.yaml
Building signal and Management Arm 6
=> Signal management arm builds

client/cmd/login.go, client/cmd/root.go, client/cmd/up.go, client/internal/config.go, client/internal/connection.go, client/internal/engine.go, client/internal/wgproxy.go, iface/iface.go, iface/iface_test.go
See https://github.com/wiretrustee/wiretrustee/issues/139#issuecomment-952561984
=> feature: add Wireguard preshared-key support

management/server/account.go, management/server/account_test.go, management/server/file_store_test.go, management/server/http/handler/peers.go, management/server/http/handler/setupkeys.go, management/server/http/handler/util.go, management/server/peer_test.go, management/server/user.go
* retrieve domain from jwt token
* store domain when creating new account
* store domain for existing accounts
=> Store domain information

go.sum, infrastructure_files/management.json.tmpl, management/cmd/management.go
* Fix IDPManagement initialization when no config
* Remove LetsEncryption configurations for example
=> Fix IDPManagement initialization when no config

management/server/http/handler/peers.go, management/server/http/handler/peers_test.go, management/server/http/handler/setupkeys.go, management/server/http/handler/util.go, management/server/jwtclaims/claims.go, management/server/jwtclaims/extractor.go, management/server/jwtclaims/extractor_test.go
* Moved the jwtClaims code to its own package
* Renamed types and Functions
* Add extractor test
=> Jwtclaims package

iface/ifacename.go, iface/ifacename_darwin.go, management/server/account.go, management/server/account_test.go, management/server/file_store.go, management/server/file_store_test.go, management/server/http/handler/peers.go, management/server/http/handler/peers_test.go, management/server/http/handler/setupkeys.go, management/server/jwtclaims/claims.go, management/server/jwtclaims/extractor.go, management/server/jwtclaims/extractor_test.go, management/server/mock_server/account_mock.go, management/server/store.go, management/server/testdata/store.json, management/server/user.go
* added 2 domain attribute fields to store and account
* Add GetAccountByDomain method
* Add Domain Category to authorization claims
* Added NewRegularUser function
* Initial GetAccountWithAuthorizationClaims test cases
* Added grouping user of private domains via GetAccountWithAuthorizationClaims method
* Updated HTTP handles with new GetAccountWithAuthorizationClaims method and related tests mocks
=> Group users of same private domain

.github/workflows/release.yml
With the latest versions of runner 
and updates of dependencies 
a new version was generated.
=> Update windows sign pipeline version

management/server/account.go, management/server/account_test.go
Improved the behavior tests for private domains and its logic as well because on existing accounts there was no primary status update
=> Improve private domain's behavior tests and logic

client/internal/engine.go, client/internal/engine_test.go, management/proto/management.pb.go, management/server/account_test.go, management/server/grpcserver.go, management/server/management_proto_test.go, management/server/network.go, management/server/peer.go
Fix outdated update coming from management
even when it is actually not outdated.
=> Persist Network Serial to Store

client/internal/oauth/auth0.go, client/internal/oauth/auth0_test.go, client/internal/oauth/oauth.go
Adding package for retrieving an access token with a device login flow
For now, we got Auth0 as a client but the Interface Client is ready
=> Add OAuth Package and Auth0 Client

infrastructure_files/setup.env
making documentation a bit clear
close #276
=> update audience documentation

README.md
=> Changing back link for Docker

.github/workflows/release.yml
skipping docker login when PR to catch issues earlier
Also, uploading artifacts and keeping then for 3 days
This will help some debug
=> Skip docker login and upload artifacts

client/server/server.go, client/ui/client_ui.go
Update daemon server adminURL and managementURL fields and Removed the UP call in the login function
=> Update daemon server adminURL and managementURL fields

client/cmd/ssh.go, client/ssh/client.go
https://github.com/netbirdio/netbird/issues/371
=> Fix SSH command on Docker

.goreleaser_ui_darwin.yaml
custom name_template for darwin ui release checksum file
fix darwin ui version injection to correct path
=> Fix checksum conflict and version injection

management/server/http/handler.go
This helps our FE to get proper request responses
=> Handle CORS requests before authentication

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handler.go, management/server/http/routes.go, management/server/http/routes_test.go
Routing API will allow us to list, create, update, and delete routes
=> Add routing Rest API support

management/server/peer.go, management/server/turncredentials.go, management/server/updatechannel.go, management/server/updatechannel_test.go
Also, prevent peer update when SSH is the same
=> Use select for turn credentials and peers update

go.mod, go.sum
Update service library with rcS init system support
=> Update service lib

README.md, client/internal/login.go
Marked network routes feature as done in readme
=> Check if login stream was canceled before printing warn

client/internal/routemanager/client.go
=> Use the client network for log errors

management/server/peer.go
Automatically assign groups of the setup key
to a newly added peer.
relates to
https://github.com/netbirdio/netbird/issues/458
=> Assign groups to peers when registering with the setup key

go.mod, go.sum
Switch library usage to upstream and update to latest version
It also updates its dependencies, fixing some issues with DTLS library
=> Update ICE library

client/cmd/status.go
```
user@host:~/$ netbird status --ipv4
100.91.24.1
```
=> Output plain NetBird IPv4 in status command

management/server/account.go, management/server/account_test.go
If domain is invalid we call GetAccountByUserOrAccountId
=> Check if domain from claim is valid

management/server/account.go, management/server/idp/auth0.go, management/server/idp/idp.go, management/server/user.go
wt_pending_invite property is set for every user on IdP.
Avoid setting it when unnecessary.
=> Do not set wt_pending_invite when unnecessary

client/ui/client_ui.go
This does minor changes to the UI to better visually identity the application on the desktop.
=> Set the application icon, settings window title and systray tooltip

.github/workflows/release.yml
This version has a fix for the
macOS UI client architecture
=> Update sign pipeline version to 0.0.4

go.mod, go.sum, management/server/metrics/selfhosted.go
We will collect the active peer min and max versions
=> Update last run time and active count

client/internal/dns/host_linux.go, client/internal/dns/systemd_linux.go
Sometimes resolvconf will manage the /etc/resolv.conf file And systemd-resolved still the DNS manager
=> Check if system is our manager when resolvconf

.github/workflows/golang-test-darwin.yml, .github/workflows/golang-test-linux.yml, .github/workflows/golang-test-windows.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml, .github/workflows/test-docker-compose-linux.yml, client/cmd/root.go, client/internal/routemanager/firewall_nonlinux.go, client/internal/routemanager/systemops_linux.go, go.mod, iface/module_linux.go, iface/module_linux_test.go, signal/cmd/run.go, util/file_test.go
Removed ioctl code and removed exception from lint action
=> Update go version

.github/workflows/test-docker-compose-linux.yml, client/internal/dns/server.go, go.mod, go.sum, infrastructure_files/configure.sh, infrastructure_files/tests/setup.env
This prevents changing the system DNS config when there is nothing to new
It also prevents issues with network changes on google chrome
=> Store the previous applied dns configuration hash

README.md
add link to a community repository authored and maintained by @physk
=> Add netbird installer project

client/cmd/login.go, client/cmd/ssh.go, client/cmd/up.go, client/internal/config.go, client/internal/config_test.go, client/internal/connect.go, client/server/server.go
As we will be passing more flags to configure local agents, we need a more flexible type
=> Use configuration input struct

client/internal/routemanager/systemops_nonlinux.go
Typo - "netforwad" -> "netforward"
=> Fix typo - "netforwad" -> "netforward"

management/Dockerfile
=> Fix cgo dependencies in the management docker container

client/system/info_darwin.go
Resolved the macOS version error issue https://github.com/netbirdio/netbird/issues/527
Now it is showing macOS version instead of the darwin version
=> Macos version error

client/cmd/root.go, client/cmd/root_test.go
This prevents conflict with the
ssh command shorthand flag
=> Revert preshared-key shorthand flag

management/server/account.go, management/server/http/peers.go, management/server/http/peers_test.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer_test.go
Add GET peer HTTP API endpoint
=> Add GetPeer API method

README.md
=> Add network activity monitoring as complete in Readme

.github/workflows/release.yml
=> Use new sign pipeline v0.0.5

management/server/account.go, management/server/account_test.go, management/server/file_store.go, management/server/grpcserver.go, management/server/peer.go, management/server/peer_test.go
Add account settings with a global peer expiration flag and duration
=> Add account settings

management/server/peer.go
=> Reject peer login expiration update when no SSO login

go.mod, go.sum
This service pkg update includes a log directory check and creation for init systems that rely on shell script. 
See the update here: [b923b894](https://github.com/netbirdio/service/commit/b923b89432b0f50ce6bc14830ba0c83e6ae0f541)
=> Update service pkg with log directory fix

client/internal/engine.go
Properly close all resources in case of any error during the start or stop procedure of engine.
=> Fix error handling in Stop/Start functions

management/server/grpcserver.go, management/server/peer.go, management/server/turncredentials.go
=> Fix peer status update when expiring peers

client/internal/peer/conn.go, client/internal/peer/conn_test.go
- make code more readable by split code into smaller functions
- add CandidateTypePeerReflexive check
- Add tests
=> Refactor/clean shouldUseProxy

client/internal/login.go
Simple code cleaning. Remove duplicated steps in login.
In the defer already close the management connection.
=> Remove mgm close steps, in defer doing it already

management/server/idp/idp.go, management/server/idp/keycloak.go, management/server/idp/keycloak_test.go
Added intergration with keycloak user API.
* Keycloak integration - Peer detail does not show Username  ([#601][i601])
* Usernames are not saved  ([#716][i716])
* Usernames are not displayed for peers ([#724][i724])
[i601]: https://github.com/netbirdio/netbird/issues/601
[i716]: https://github.com/netbirdio/netbird/issues/716
[i724]: https://github.com/netbirdio/netbird/issues/724
=> Add Keycloak Idp Manager

management/server/http/middleware/jwt.go
We will log the middleware log now, but in the next releases we should provide a generic error that can be parsed by the dashboard.
Partially helps with the issue reported in #750
=> Add JWT middleware validation failure log

.github/workflows/golang-test-linux.yml, client/android/client.go, client/cmd/up.go, client/internal/connect.go, client/internal/engine.go, client/internal/engine_stdnet.go, client/internal/engine_stdnet_android.go, client/internal/peer/conn.go, client/internal/peer/conn_test.go, client/internal/peer/stdnet.go, client/internal/peer/stdnet_android.go, client/internal/stdnet/iface_discover.go, client/internal/stdnet/stdnet.go, client/internal/stdnet/stdnet_test.go, client/server/server.go
On Android, because of the hard SELinux policies can not list the
interfaces of the ICE package. Without it can not generate a host type
candidate. In this pull request, the list of interfaces comes via the Java
interface.
=> Add custom ice stdnet implementation

client/android/client.go, client/android/login.go
Refactor the auth code into async calls for mobile framework
=> Refactor the authentication part of mobile exports

client/internal/connect.go, client/internal/peer/listener.go, client/internal/peer/notifier.go, client/internal/peer/status.go
Add OnDisconnecting service callback for mobile
=> Add OnDisconnecting service callback

encryption/encryption.go
Fix slice bounds out of range in msg decryption
=> Fix slice bounds out of range in msg decryption

release_files/install.sh
Check for available package managers in order of preference and select the first one found.
=> Use first available package manager

client/android/client.go, client/internal/connect.go, client/internal/dns/server_test.go, client/internal/engine.go, client/internal/engine_stdnet.go, client/internal/engine_stdnet_android.go, client/internal/peer/conn.go, client/internal/peer/stdnet.go, client/internal/peer/stdnet_android.go, client/internal/stdnet/discover.go, client/internal/stdnet/discover_mobile.go, client/internal/stdnet/discover_mobile_test.go, client/internal/stdnet/discover_pion.go, client/internal/stdnet/filter.go, client/internal/stdnet/iface_discover.go, client/internal/stdnet/stdnet.go
The Discoverer return with []*transport.Interface instead of string
=> Separate discover methods

management/server/peer.go
=> Fix network map fetch when adding a peer

client/cmd/status.go, client/cmd/status_test.go
=> Use local time zone for display last update changes

client/internal/peer/conn.go, iface/tun_android.go
=> Enable roaming for mobile

client/internal/engine.go, shared_sock/sock_linux.go, shared_sock/sock_linux_test.go, shared_sock/sock_nolinux.go
=> Fix resource close process

management/server/idp/azure.go, management/server/idp/azure_test.go, management/server/idp/idp.go
Added intergration with azure user API.
Use the steps in [azure-ad.md](https://github.com/netbirdio/docs/blob/cb03373f8feb9da0204606ab055fa9825f0f9a26/docs/integrations/identity-providers/self-hosted/azure-ad.md)  for configuration.
=> Add Azure Idp Manager

client/internal/engine.go, sharedsock/filter_linux.go, sharedsock/filter_nolinux.go, sharedsock/sock_linux.go, sharedsock/sock_linux_test.go
=> Correct sharedsock BPF fields

sharedsock/sock_nolinux.go
Fix sharedsock build on android
=> Fix sharedsock build on android

release_files/install.sh
=> creates the install dir before moving the bin dir

management/cmd/management.go, management/server/idp/auth0.go, management/server/idp/auth0_test.go, management/server/idp/azure.go, management/server/idp/idp.go, management/server/idp/keycloak.go, management/server/idp/keycloak_test.go, management/server/idp/zitadel.go, management/server/idp/zitadel_test.go
=> Automatically load IdP OIDC configuration

management/server/idp/auth0.go
=> Resolve issue with AuthIssuer URL assignment in auth0

management/server/user.go
=> Track user block/unblock activity event

iface/bind/udp_mux_universal.go
Fixes NPE when querying XORMappedAddr in UDPMux
=> Fix panic when getting XORMapped addr

client/internal/routemanager/systemops_linux.go
Read and check ip_forward from proc before write
=> Fix issue 872

management/server/file_store.go, management/server/http/policies_handler.go
=> Add policy validation during update. Stop update policies from rules.

go.mod, management/server/telemetry/http_api_metrics.go
=> Measure write requests separately from read requests

management/server/telemetry/http_api_metrics.go
=> Count only successful HTTP request durations

client/firewall/uspfilter/uspfilter.go
=> Feat linux firewall support fix async

management/cmd/management.go, management/server/idp/auth0.go, management/server/idp/auth0_test.go, management/server/idp/azure.go, management/server/idp/idp.go, management/server/idp/keycloak.go, management/server/idp/keycloak_test.go, management/server/idp/zitadel.go, management/server/idp/zitadel_test.go
Refactor the existing struct to have a more generic configuration for all IdPs, along with an additional config that can hold key-value pairs for IdP-specific settings.
* Refactor IdP Config Structure for Improved Management ([#870][i870])
[i870]: https://github.com/netbirdio/netbird/issues/870
=> Refactor IdP Config Structure

client/internal/peer/conn.go, client/internal/peer/env_config.go
Add force relay conn env var for debug purpose
Move another conn related env settings into a common go file
=> Add force relay conn env var for debug purpose

infrastructure_files/nginx.tmpl.conf
This PR implements a template for an Nginx configuration that works with Netbird.
- [X ] Is a feature enhancement
=> Added nginx template

management/server/idp/idp.go
Get Okta and Authentik config from generic configuration
=> Get IdP config from generic configs

management/server/metrics/selfhosted.go
The new features PATs and service users where not monitored for selfhosted envs yet. Added metrics to keep track.
=> Add selfhosted metrics for PATs and service users

client/cmd/down.go, client/cmd/login.go, client/cmd/root.go, client/cmd/service.go, client/cmd/service_controller.go, client/cmd/service_installer.go, client/cmd/ssh.go, client/cmd/status.go, client/cmd/up.go
=> Revert "Configure CLI flags properly"

client/internal/acl/manager.go, client/internal/acl/manager_test.go
Add SSH accept rule on the client if SSH is enabled for the peer.
=> Add SSH accept rule on the client

management/server/http/accounts_handler.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
To properly display on the docs website we need a small adjustment otherwise the parser can not properly get the parameters
=> Update openapi doc

management/server/peer.go
=> Reject adding peer if already exists with a pub key

management/server/peer.go
=> Add comment clarifying AddPeer race check

infrastructure_files/setup.env.example
=> Organize example setup.env with sections

.github/workflows/release.yml
Added a trigger to the release workflow to start generating API pages in docs repo based on openapi specification and build a new docker.
=> Add trigger for docs generation to release workflow

management/server/http/policies_handler.go
Check port values before updating the policy rule
=> Fix validation for ACL policy rules ports

client/android/client.go, client/android/peer_notifier.go
On mobile system the direct flag is unused
=> Remove unused field from peer state

client/android/client.go
Eliminate default trace log level on mobile
=> Eliminate default trace log level on mobile

release_files/darwin-ui-installer.sh
Added app restart so the newly installed version in case of an update is running not the old one.
Also added service uninstall not not show any errors in installer in case of update.
=> Add app restart to brew installer

management/server/http/api/openapi.yml
=> Update the API description with the correct API state

.gitignore
For multiple IdPs I have a config each to simply switch for testing that should not be uploaded by accident.
=> Extend gitignore to ignore multiple configs

client/internal/dns/server.go
=> Fix the stop procedure in DefaultDns

.github/workflows/release.yml, .goreleaser_ui.yaml
=> Remove unused netbird UI dependencies

client/internal/config.go, client/internal/config_test.go
* netbird pre-shared not persistent   ([#887][i887])
[i887]: https://github.com/netbirdio/netbird/issues/887
=> Fix pre-shared key not persistent

management/server/account.go, management/server/account_test.go, management/server/activity/codes.go, management/server/group.go, management/server/group_test.go, management/server/http/groups_handler.go, management/server/http/groups_handler_test.go, management/server/http/util/util.go, management/server/mock_server/account_mock.go
=> Check links of groups before delete it

client/internal/routemanager/firewall_linux.go, client/internal/routemanager/iptables_linux.go, client/internal/routemanager/iptables_linux_test.go, client/internal/routemanager/nftables_linux.go, client/internal/routemanager/nftables_linux_test.go
Sync the iptables/nftables usage with ACL logic
=> Sync the iptables/nftables usage with acl logic

client/firewall/nftables/manager_linux.go
Fixed nfset does not bind to the corresponding rule.
=> Fix nfset not binds to the rule

management/server/http/middleware/auth_middleware.go, management/server/jwtclaims/jwtValidator.go
=> Use error level for JWT parsing error logs

client/internal/routemanager/nftables_linux.go
=> Add default forward rule

management/cmd/management.go, management/server/metrics/selfhosted.go
This information allows us to define priority on supporting different managers
=> Record idp manager type

client/firewall/iptables/manager_linux.go, client/firewall/iptables/manager_linux_test.go, client/firewall/iptables/rule.go, go.mod, go.sum
Use ipset (via Netlink) to optimize rule count for iptables
=> Feat optimize acl performance iptables

client/internal/wgproxy/factory_linux.go
=> Avoid compiling linux NewFactory for Android

client/internal/auth/pkce_flow.go, client/internal/templates/embed.go, client/internal/templates/pkce-auth-msg.html
Add screen  after the completion of the PKCE authorization flow. The changes include adding a new HTML template to render the PKCE authentication message and refactoring existing code for improved readability and error handling
=> Add html screen for pkce flow

client/internal/auth/pkce_flow.go, management/cmd/management.go
Added error handling in PKCE flow to detect and return authentication errors.
=> Handle authentication errors in PKCE flow

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> Update setup key auto_groups description

client/internal/wgproxy/factory_linux.go, client/internal/wgproxy/proxy_ebpf.go
=> Handle conn store in thread safe way

client/internal/routemanager/iptables_linux.go
=> Fix error handling in iptables initialization

README.md
=> Update new release banner

management/server/idp/auth0.go, management/server/idp/auth0_test.go, management/server/idp/authentik.go, management/server/idp/azure.go, management/server/idp/google_workspace.go, management/server/idp/idp.go, management/server/idp/keycloak.go, management/server/idp/okta.go, management/server/idp/zitadel.go, management/server/user.go
=> Specify invited by email when inviting a user

client/cmd/login.go, client/cmd/status.go, client/internal/dns/server.go
Fix the links to the doc pages
=> Update links to the proper doc page

management/server/account.go, management/server/activity/codes.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/peer.go
Track the even of a user logging in their peer.
Track the event of a peer login expiration.
=> Add peer login and expiration activity events

client/internal/auth/oauth.go
Switches the order of initialization in the OAuth flow within the `NewOAuthFlow` method. Instead of initializing the Device Authorization Flow first, it now initializes the PKCE Authorization Flow first, and falls back to the Device Authorization Flow if the PKCE initialization fails.
=> Switch OAuth flow initialization order

client/cmd/login.go
- Fixes  improperly escaped PKCE flow auth URL
- Enhance the client authentication process within the Linux environment. For Linux instances lacking desktop support (such as servers), authentication will be streamlined to require setup keys and the device flow (if configured) exclusively
=> Enhance linux client authentication

release_files/install.sh
This pull request addresses the need to enhance the installer script by introducing a new parameter `--update` to trigger updates. The goal is to streamline the update process for binary installations and provide a better experience for users.
=> Add auto-update feature in netbird script for binary installation

.github/workflows/install-script-test.yml, release_files/install.sh
prevent failing tests by using a github token to perform requests in our CI/CD
=> Use github token to read api

management/server/idp/auth0_test.go, management/server/idp/idp.go
=> Ignore empty fields in the app metadata when storing on IDP

management/server/metrics/selfhosted.go
=> Account ephemeral setup keys metrics

management/server/http/setupkeys_handler.go, management/server/http/setupkeys_handler_test.go
=> Update ephemeral field on the API response

client/internal/wgproxy/proxy_ebpf.go
=> Set not found ebpf log to Info

.github/workflows/test-infrastructure-files.yml
docker compose output updated and the key Project is gone from the results
=> Fix: docker test for infrastructure files

client/cmd/login.go
=> Update  Linux Desktop Detection Check

client/internal/acl/manager_create.go, client/internal/acl/manager_create_linux.go, client/internal/checkfw/check.go
The source code files related to the Android firewall had incorrect build tags set.
=> Fix Android build

.github/workflows/android-build-test.yml, .github/workflows/android-build-validation.yml
Extend the CI with gomobile build.
With this step we can validate that the code can run on Android
=> Add Android test build

client/android/login.go
Fix SSO check
- change the order of the PKCE and device auth flow check, prefer PKCE
- fix error handling in PKCE check
=> Fix sso check

client/cmd/login.go, client/internal/auth/oauth.go, client/internal/auth/pkce_flow.go, client/internal/auth/util.go
- Enable authentication via the device code flow for Linux devices without a desktop environment, if configured prior to using setup keys
- Enhance the closure of the PKCE server upon authentication completion or user cancellation with context
- Fix EOF error occurring during PKCE authentication after the login has expired
=> Improve Client Authentication

management/cmd/management.go, management/server/config.go, management/server/idp/idp.go, util/file.go
=> Add direct write file to avoid moving docker mounted files

release_files/install.sh
* Updating NetBird  ([#1105][i1105])
[i1105]: https://github.com/netbirdio/netbird/issues/1105
=> Fix Update Failure in Netbird Installer Script

client/firewall/iptables/manager_linux.go
Comment will be ignored in iptables implementation 
because some system this feature is not supported.
=> Remove comments from iptables

release_files/install.sh
See https://github.com/netbirdio/public-keys/issues/1#issuecomment-1736322449
=> install.sh: Sync Debian keys and repo source file location with docs

management/server/http/api/openapi.yml
=> Update the description for the delete method for user API

management/server/user.go
=> Fix peer login expiration event duplication

management/server/account.go, management/server/account_test.go, management/server/ephemeral.go, management/server/ephemeral_test.go, management/server/http/peers_handler.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/user.go
Delete user peers when deleting a user
=> Delete user peers when deleting a user

management/server/metrics/selfhosted.go, management/server/metrics/selfhosted_test.go
=> Add routing groups metrics

management/server/peer.go, management/server/turncredentials.go, management/server/updatechannel.go, management/server/updatechannel_test.go, management/server/user.go
=> Reorder peer deletion when deleteing a user

management/server/account.go, management/server/dns.go, management/server/group.go, management/server/nameserver.go, management/server/peer.go, management/server/policy.go, management/server/route.go, management/server/setupkey.go, management/server/user.go
=> Improve updateAccountPeers by bypassing AM and using account directly

client/ui/client_ui.go
=> Use the PCKE flow in the UI

.gitattributes, .github/workflows/golangci-lint.yml
=> Run linter action on MacOS and Windows

management/server/account.go, management/server/idp/authentik.go, management/server/idp/azure.go, management/server/idp/google_workspace.go, management/server/idp/okta.go
=> Add Pagination for IdP Users Fetch

management/client/client_test.go
=> chore: pkg import only once

go.mod, go.sum, management/server/http/handler.go, management/server/http/middleware/auth_middleware.go, management/server/http/middleware/auth_middleware_test.go
=> Add management-integrations

CONTRIBUTING.md
=> Contribution guide - Explicitly disable CGO for client

management/server/store.go
=> Log store engine type

management/server/sqlite_store.go, management/server/user.go
=> Fix SaveUserLastLogin in SQLite store

management/server/sqlite_store.go
=> Fix GetAccountByPrivateDomain for SQLite

.github/workflows/test-infrastructure-files.yml, infrastructure_files/management.json.tmpl
removed duplicated key and added tests
=> Fix redirect urls template processing

version/url.go, version/url_darwin.go, version/url_linux.go, version/url_windows.go
Based on the registry, determine the installation source (MSI or EXE) 
and open the appropriate link in the update notification menu
=> Download link based on installation type

management/server/idp/auth0.go
=> Log auth0 batch length

go.mod, go.sum, management/server/http/handler.go
=> Pass JWT Claims Extractor to Integrations

client/internal/routemanager/client.go, client/internal/routemanager/nftables_linux.go
Set filterTable only for ipv4 table
fixes #947
=> Fix network route adding rule to filter table

management/server/http/users_handler.go
=> Remove logging of User names on Debug level

go.mod, go.sum
Fix the black icon background on Windows.
Update to the patched systray library.
=> Fix black icon background on Win

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
=> Extend devcontainer with dind and go features

management/server/activity/codes.go
Introducing new activity events to record integration creation, updating, and deletion in the activity events. This enhancement enables the tracking of user actions related to integrations.
=> Add integration activity events

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/peers_handler.go, management/server/http/peers_handler_test.go
Extend the peer and peers API endpoints with accessible peers.
=> Extend API with accessible peers

management/server/group.go, management/server/group_test.go, management/server/user.go, management/server/user_test.go
Extending the logic to permit the removal of groups and users issued by integrations, especially upon request by an admin service user.
=> Enable deletion of integration resources

management/server/http/middleware/access_control.go
=> Log access control error

management/server/sqlite_store.go
=> Fix PAT copy for GetUserByTokenID in SQLite store

management/server/activity/sqlite/sqlite.go
=> Fix duplicated Activity events shown

management/server/account.go, management/server/user.go
To take into consideration that the cache may know more users
=> Improve Account cache reload condition

management/server/account.go
=> Fix lookupCache to work when idp has more users

CONTRIBUTING.md, client/installer.nsis
=> Add client UI shortcut links for standard users in Windows

client/system/info_windows.go
GetInfo() was not reporting the windows type and windows verison correctly. THis has been fixed with this PR.
=> Fix windows os info

.github/workflows/release.yml
=> Update signing pipelines to version 0.0.10

client/system/info_windows.go
=> Add Windows version to correct system info field

management/server/http/users_handler.go, management/server/user.go
Validate email and user are not empty
=> Fix panic on empty username for invites

.github/workflows/sync-main.yml
=> Add sync-main.yml GitHub workflow

CONTRIBUTING.md
=> Add Dev Container Support section in contributing guideline

management/server/mock_server/account_mock.go
=> Fix SaveOrAddUser and GetPeers methods in MockAccountManager

client/cmd/login.go, management/server/account.go, management/server/grpcserver.go, management/server/http/handler.go, management/server/http/middleware/auth_middleware.go, management/server/http/middleware/auth_middleware_test.go, management/server/mock_server/account_mock.go
Introduce group-based access control for the addition of new peers with JWT.
=> Add JWT group-based access control for adding new peers

.github/workflows/release.yml
Removing extra cache store with setup-go action and adding `~/.cache/go-build` to the cached directory list
=> Improve release workflows speed

client/internal/routemanager/notifier.go
Compare the differences between the new routes and initial routes
=> Fix route change notifier

client/firewall/nftables/acl_linux.go
Remove duplicated chain add operation
=> Remove duplicated chain add

.github/workflows/golang-test-windows.yml
=> Use cached wintun zip package in github workflows

management/server/http/api/openapi.yml
The Policies API should be the way to go.
=> Soft deprecate Rules API

client/internal/engine.go
=> Fix client SSH server error log

iface/tun_usp_linux.go
=> Fix typo in iface/tun_usp_linux.go

go.mod, go.sum
=> Fix musl build

management/server/grpcserver.go
=> Fix peer meta core compability with older clients

client/android/client.go
=> Export info log level setter for Android

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> Remove query parameter from policy endpoints

infrastructure_files/docker-compose.yml.tmpl, infrastructure_files/getting-started-with-zitadel.sh
=> Use dashboard v2 for getting started scripts

go.mod, go.sum, management/cmd/management.go, management/server/config.go
=> Expose trusted proxy list and counter configuration for realip middleware

management/server/http/geolocations_handler.go, management/server/http/handler.go, management/server/http/posture_checks_handler.go, management/server/http/posture_checks_handler_test.go
=> Disallow Geo check creation/update without configured Geo DB

management/server/geolocation/geolocation.go, management/server/geolocation/geolocation_test.go, management/server/geolocation/store.go
=> Fix shared access to in memory copy of geonames.db

management/server/posture_checks.go
=> Regenerate network map on posture check update

management/server/group.go, management/server/http/groups_handler.go
Return error when peer is not valid and fix count with invalid peers.
=> Return error when peer is not valid

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/posture_checks_handler.go, management/server/http/posture_checks_handler_test.go
=> Make city name optional

go.mod, go.sum, management/cmd/management.go
=> Switch realip middleware to upstream

management/server/geolocation/store.go
=> Fix geonames db reload

management/server/http/api/openapi.yml, management/server/posture_checks.go, management/server/posture_checks_test.go
=> Ensure posture check name uniqueness when create

management/server/grpcserver.go
=> Fix misassigned peer metadata

management/server/http/api/openapi.yml
=> Mark new peer meta fields required in OpenAPI spec

management/server/metrics/selfhosted.go, management/server/metrics/selfhosted_test.go
=> Add posture checks metrics report

management/server/posture/checks.go
=> Fix copying posture checks definitions

infrastructure_files/getting-started-with-zitadel.sh
=> Add support for device flow on getting started with zitadel

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/posture_checks_handler.go, management/server/http/posture_checks_handler_test.go, management/server/posture/checks.go, management/server/posture/checks_test.go, management/server/posture/network.go, management/server/posture/network_test.go
=> Rename PrivateNetworkCheck to PeerNetworkRangeCheck

infrastructure_files/management.json.tmpl, infrastructure_files/nginx.tmpl.conf
Add grpc_set_header to the nginx example template
=> Add reverse proxy settings to management.json template

.github/ISSUE_TEMPLATE/bug-issue-report.md
=> Update bug-issue-report.md label

.golangci.yaml, client/internal/auth/oauth.go, iface/netstack/tun.go, management/server/activity/event.go, management/server/peer/peer.go
Exported functions and methods should have comments. This warns on undocumented exported functions and methods.
=> Enable review linter with exported docs check

management/server/account.go, management/server/account_test.go, management/server/peer.go, management/server/peer/peer.go, management/server/user.go, management/server/user_test.go
This change register creation time for new peers, users and accounts
=> Register creation time for peer, user and account

README.md
=> add ansible collections contributions

management/server/account.go
add log for when a domain is not present
=> Update account attributes only when there is a domain

management/server/idp/zitadel.go
This fixes the "Invite User" button in Dashboard v2.0.0 and enables the usage of the --user-delete-from-idp flag for Zitadel.
Unlike the NetBird SaaS solution, we rely on Zitadel to send the emails on our behalf.
Refs: #855 
- [ X] Is a feature enhancement
=> Add support for inviting/deleting users via Zitadel

management/server/idp/authentik.go, management/server/idp/authentik_test.go, management/server/scheduler_test.go
also updated the scheduler tests to use a higher times on windows
=> Validate authentik issuer url

client/internal/routemanager/manager.go
Removes `nil`ing of the context preventing a crash
=> Remove context niling

client/system/info_linux.go
In meta info collect chassis serial
=> In meta info collect chassis serial

client/internal/routemanager/systemops_linux.go
Fixes https://github.com/netbirdio/netbird/issues/1761
=> Ignore "Address family not supported by protocol" errors

README.md
=> Update network security image

client/internal/routemanager/systemops_linux.go
=> Timeout rule removing loop and catch IPv6 unsupported error in loop

management/server/account.go, management/server/idp/okta.go, management/server/mock_server/account_mock.go
=> chore: fix function names in comment

client/internal/connect.go, client/internal/routemanager/systemops.go, client/internal/routemanager/systemops_bsd.go, client/internal/routemanager/systemops_darwin.go, client/internal/routemanager/systemops_linux.go, client/internal/routemanager/systemops_windows.go, util/net/dialer_generic.go
=> Fix routing issues

client/internal/routemanager/systemops_darwin.go, client/internal/routemanager/systemops_darwin_test.go
Fixes https://github.com/netbirdio/netbird/issues/1681
=> Retry macOS route command

client/internal/connect.go
=> Log panics

infrastructure_files/docker-compose.yml.tmpl
=> Add log-level to the management's docker service command

client/internal/routemanager/systemops_windows.go
=> Use route active store

client/internal/routemanager/manager.go, client/internal/routemanager/systemops_linux.go, client/internal/wgproxy/proxy_ebpf.go, iface/wg_configurer_kernel.go, iface/wg_configurer_usp.go, util/net/dialer_generic.go, util/net/listener_generic.go, util/net/net.go, util/net/net_linux.go
This PR allows disabling all fwmark and exclusion routes, for debugging purposes or to workaround potential issues.
=> Allow disabling custom routing

.github/workflows/golangci-lint.yml, management/server/activity/codes.go
=> Use fixed activity codes

client/internal/peer/conn.go
=> Fix ICE endpoint remote port in status

management/server/sqlite_store.go, management/server/sqlite_store_test.go
=> Use a better way to insert data in batches

client/Dockerfile
=> Copy client binary to a directory in path

management/server/http/setupkeys_handler.go, management/server/http/util/util.go
=> Fix incorrect response content-type header

client/internal/routemanager/client.go, client/internal/routemanager/routemanager.go, client/internal/routemanager/systemops.go, client/internal/routemanager/systemops_android.go, client/internal/routemanager/systemops_darwin.go, client/internal/routemanager/systemops_darwin_test.go, client/internal/routemanager/systemops_ios.go, client/internal/routemanager/systemops_linux.go, client/internal/routemanager/systemops_nonlinux.go, client/internal/routemanager/systemops_test.go, client/internal/routemanager/systemops_windows.go
Replaces powershell with the route command and caches route lookups on windows
=> Replace powershell with route command

management/server/peer.go
Check for connection channel before calculating and sending the network map
=> Check if channel exist before sending network map

management/server/geolocation/geolocation.go, management/server/geolocation/store.go
Update log level to trace and update the check db interval from 60s to 300s
=> Update the check interval for new geo db and change log level

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/peers_handler.go, management/server/http/peers_handler_test.go
=> Return system serial on a peer HTTP API call

management/server/account.go
=> Remove GetNetworkMap stacktrace

.github/workflows/release.yml, client/firewall/uspfilter/allow_netbird_windows.go, client/internal/routemanager/systemops_windows.go
=> Fix windows route exec path

release_files/systemd/netbird-management.service, release_files/systemd/netbird-signal.service, release_files/systemd/netbird@.service
Fixed typos in systemd .service files
#1971
=> Fix typo in systemd .service files

client/internal/engine.go, client/internal/wgproxy/proxy_ebpf.go
=> Don't cancel proxy context on conn close

client/internal/engine.go, client/internal/networkmonitor/monitor.go, client/internal/networkmonitor/monitor_bsd.go, client/internal/networkmonitor/monitor_generic.go, client/internal/networkmonitor/monitor_linux.go, client/internal/networkmonitor/monitor_mobile.go, client/internal/networkmonitor/monitor_windows.go
=> Refactor network monitor to wait for stop

client/ui/client_ui.go
in case we get no status we mark the GUI app as disconnected
fixes #2006
=> Update the GUI status when daemon unavailable

client/internal/routemanager/systemops_darwin.go, iface/iface_test.go, iface/tun_darwin.go
=> Add dummy ipv6 to macos interface

client/internal/relay/relay.go
Some systems might respond with a small delay depending on various factors. Increasing the timeout to reduce the number of false-positive reports
=> Increase the status checks timeout

client/cmd/login.go, client/cmd/login_test.go
=> Accept any XDG_ environment variable to determine desktop

client/server/server.go
=> Fix the initial daemon retry interval

client/firewall/create_linux.go
=> Use info log-level for firewall manager discover

management/server/account.go
=> Remove extra error mapping

CODE_OF_CONDUCT.md
=> fix a typo in CODE_OF_CONDUCT.md

management/server/group.go, management/server/group_test.go
=> Don't allow delete group from peer groups

client/internal/templates/pkce-auth-msg.html
=> Fix PKCE auth html

management/server/account.go, management/server/file_store.go, management/server/peer.go, management/server/sql_store.go, management/server/status/error.go, management/server/store.go
This PR reduced database reads by adding getAccountIDBy... to the store and adjusting the database locks.
=> Improve login performance

client/system/info_freebsd.go, client/system/info_linux.go, client/system/osrelease_unix.go
Fix OS version info in the system metadata
=> Fix OS version info on FreeBSD

client/internal/peer/conn.go
Handle **conn.sentExtraSrflx** variable in thread safe way
=> Handle conn.sentExtraSrflx variable in thread safe way

management/server/metrics/selfhosted.go
Prevent using expired ctx when sending metrics and increase timeout from 30 to 45.
=> Prevent using expired ctx when sending metrics

client/internal/engine.go, client/internal/peer/conn.go, signal/client/client.go, signal/client/client_test.go
=> Remove unused variables from peer conn

util/net/net.go
=> Do not use SO_MARK in case of netstack mode.

client/system/info.go, client/system/process.go
Support checkFileAndProcess function for posture check on FreeBSD
=> Fix checkFileAndProcess function on FreeBSD

client/internal/connect.go
=> fix network monitor ref check

client/system/info_android.go
=> Trim new line char from Android version

client/internal/networkmonitor/monitor_windows.go, client/internal/routemanager/systemops/systemops_bsd.go, client/internal/routemanager/systemops/systemops_generic.go, client/internal/routemanager/systemops/systemops_windows.go
This fixes issues with IPv6 zones
=> Fix windows route zones

management/server/account.go, management/server/route.go
=> Fix dns route retrieval condition

client/internal/engine.go, client/internal/peer/conn_test.go, client/internal/wgproxy/factory_linux.go, client/internal/wgproxy/factory_nonlinux.go
=> Do not use eBPF proxy in case of USP mode

client/ui/route.go
Use select widget for dns routes on GUI
=> Use selector to display dns routes in GUI

.github/workflows/release.yml
=> Using macOS-latest to build GUI

client/internal/networkmonitor/monitor_windows.go
=> Improve windows network monitor

client/ui/route.go
Add all routes, overlapping and exit routes tabs
All routes:
Overlapping routes:
Exit-nodes routes:
=> Add multiple tabs for route selection

client/system/info_linux.go
=> Fix linux serial number retrieval

management/server/account.go
=> Fix nil pointer exception in case of error

client/ui/route.go
=> Sort routes by ID and remove DNS routes from overlapping list

management/server/user.go
We noticed occasional overwrites on the domain field with empty strings which was causing unneccessary updates. This PR checks this.
=> Avoid empty domain overwrite

iface/tun_android.go, iface/tun_darwin.go, iface/tun_ios.go, iface/tun_netstack.go, iface/tun_usp_unix.go, iface/tun_windows.go, iface/wg_log.go
=> Add logging option for WG device

util/log.go, util/syslog_windows.go
this is a follow up for commit 1d6f5482ddae3ae6805f279e180034a3b127c013
There are two SonarQube issues that needed fixing:
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=netbirdio_netbird&open=AZC6oQn7LtoaMq5atDqH
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&types=CODE_SMELL&id=netbirdio_netbird&open=AZC6oQpqLtoaMq5atDqI
related to #2255
=> refactor(util): fix sonarcube issues

signal/README.md, signal/metrics/app.go, signal/server/signal.go
=> Add get_registration_delay_milliseconds metric

signal/server/signal.go
=> Fix metric label typo

signal/cmd/run.go
remove migration function for wiretrustee directories to netbird
refactor main run function
=> Remove copy functions from signal

client/internal/dns/host_darwin.go
previously, we called the restore method from the startup when there was an unclean shutdown. But it never had the state keys to clean since they are stored in memory
this change addresses the issue by falling back to default values when restoring the host's DNS
=> Fix macOS DNS unclean shutdown restore call on startup

client/internal/dns/host_darwin.go
Without this fix, 0 may be added to the search domain
=> Minor fix local dns search domain

management/client/grpc.go
=> Retry management connection only on context canceled

client/internal/networkmonitor/monitor_windows.go
ignore checks for Teredo and ISATAP interfaces
=> Ignore network monitor checks for software interfaces

signal/cmd/run.go, signal/metrics/metrics.go
Fix error handling in metrics server setup
=> Fix error handling

client/internal/dns/service_listener.go
=> Fix race in set listener

client/cmd/service_installer.go
=> Save daemon address on service install

management/server/group.go, management/server/user.go
=> Save account on saving users and groups

client/internal/routemanager/dynamic/route.go
=> Allow route updates even if some domains failed resolution

README.md
=> Remove Codacy badge as it is broken

.github/workflows/test-infrastructure-files.yml
replace calls to docker-compose with docker compose
=> Use docker compose command

.github/workflows/release.yml
Fix the binary version and remove the other arch syso generation.
=> Fix windows binary version

.github/ISSUE_TEMPLATE/bug-issue-report.md
=> Update bug-issue-report.md to include netbird debug cmd

.github/ISSUE_TEMPLATE/bug-issue-report.md
=> Update bug-issue-report.md to include anon flag

client/internal/auth/device_flow.go, client/internal/engine.go, client/internal/routemanager/sysctl/sysctl_linux.go, client/ssh/server.go, management/client/grpc.go, management/server/grpcserver.go, management/server/http/posture_checks_handler_test.go, management/server/idp/auth0_test.go, management/server/jwtclaims/jwtValidator.go, management/server/posture_checks.go, sharedsock/sock_nolinux.go
=> [misc] Fix linting Issues

management/server/account.go, management/server/file_store.go, management/server/peer.go, management/server/sql_store.go, management/server/store.go
=> Split DB calls in peer login

release_files/install.sh
To make the binary work on synology there was a code snippet missing during the install.
https://github.com/netbirdio/netbird/issues/1977
=> Loading tun module for synology in install.sh

.github/ISSUE_TEMPLATE/bug-issue-report.md
=> Use clearer wording on issue template

management/server/grpcserver.go
=> Fix logging out peers on deletion

management/server/account.go, management/server/account_request_buffer.go, management/server/management_proto_test.go, management/server/peer.go
=> [management] Rename request buffer and update default interval

client/cmd/root_test.go
=> Add test for SetFlagsFromEnvVars

encryption/route53.go, encryption/route53_test.go, relay/cmd/env.go, relay/cmd/main.go, relay/healthcheck/sender_test.go
- Remove config file support
- Add ENV variable support
=> [relay] Feature/relay remove cfg file

relay/server/relay.go
Add IP address for the error messages in the
Hello section
=> [relay] Extend the error messages with IP

.github/workflows/release.yml
=> [misc] Update sign pipeline version to 0.0.13

relay/Dockerfile, relay/cmd/env.go, relay/cmd/root.go, relay/doc.go, relay/main.go
Create Dockerfile
Refactor the cmd package to the same ways like signal and management services
=> [relay] Feature/relay integration docker

.github/workflows/test-infrastructure-files.yml
=> [misc] Test infrastructure files generation with postgres store

client/internal/peer/conn.go
Fix status indication after switching from p2p to relay.
=> [relay] Feature/relay integration fix conn state

.github/workflows/release.yml
=> Use new sign pipeline

client/internal/engine.go, client/internal/engine_test.go, client/internal/peer/conn.go, client/internal/routemanager/client.go, client/internal/routemanager/dynamic/route.go, client/internal/routemanager/manager.go, client/internal/routemanager/server_android.go, client/internal/routemanager/server_nonandroid.go, client/internal/routemanager/sysctl/sysctl_linux.go, client/internal/routemanager/systemops/systemops.go, client/internal/routemanager/systemops/systemops_generic.go, iface/iface_moc.go, iface/iwginterface.go, iface/iwginterface_windows.go
=> [relay] Replace the iface to interface

client/internal/engine.go, client/internal/peer/conn.go, client/internal/peer/conn_test.go, client/internal/peer/stdnet.go, client/internal/peer/stdnet_android.go
=> [relay] Move ICE related configs to a new struct

relay/client/dialer/ws/ws.go, relay/server/listener/ws/listener.go
=> [relay] Add url path to connection

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> Update route API doc with max domain number

client/cmd/service.go, client/cmd/service_controller.go
=> Fix service down

relay/client/client.go, relay/client/dialer/ws/ws.go, relay/messages/message.go, relay/messages/message_test.go, relay/server/listener/ws/listener.go, relay/server/peer.go, relay/server/relay.go
=> Add version byte to wire protocol

relay/messages/message.go
=> Add unknown message type

relay/healthcheck/sender.go, relay/healthcheck/sender_test.go, relay/server/peer.go
- Fix timeout timer reset
- Optimise the test parameters for CI
=> [relay] Fix health check

relay/client/client.go, relay/messages/address/address.go, relay/messages/auth/auth.go, relay/messages/message.go, relay/messages/message_test.go, relay/server/peer.go, relay/server/relay.go
=> Use hello msg struct

relay/healthcheck/sender_test.go
=> [relay] Feature/relay integration fix test

client/cmd/service_controller.go, client/internal/connect.go, client/server/server.go
=> [client] Avoid deadlock when auto connect and early exit

management/server/token_mgr.go
=> Fix empty relay config

client/internal/peer/conn.go, client/internal/peer/worker_ice.go, client/internal/peer/worker_relay.go
Close ice agent and close relayed conn when we cancel the peer ponnection
=> [relay] Feature/relay integration fix conn close

relay/client/manager.go
=> [relay] Handle the case when all servers are unavailable

relay/client/dialer/ws/ws.go, util/net/dialer_nonios.go
=> Use custom dialer for tls

README.md
=> [misc] Update slack url

client/internal/routemanager/client.go
=> Update route calculation doc

management/server/route_test.go, management/server/scheduler_test.go, management/server/updatechannel.go
=> Reduce test logs

client/internal/engine.go, client/internal/engine_test.go, client/internal/peer/status.go, client/internal/routemanager/manager.go, client/internal/routemanager/manager_test.go, util/net/dialer_nonios.go
=> Set up relay server exclusion routes early

relay/client/client.go
=> Fix nil pointer exception

.github/workflows/test-infrastructure-files.yml, infrastructure_files/getting-started-with-zitadel.sh
=> Update getting started script with relay support

client/internal/engine.go
=> Fix lock on down

client/internal/peer/worker_relay.go
=> Fix deadlock on relay disconnect

iface/iface_test.go
=> [client] Add TestRecreation test

relay/client/manager.go
When try to use the openConnVia function on multiple threads for the same server then the first thread try to open the connection and the second just wait for the result. If the connection failed the second thread just get permission to run but on a failed connection.
=> Fix error handling in openConnVia function

relay/metrics/realy.go, relay/server/peer.go
=> [relay] change log levels

go.mod, go.sum
It updates with the fix from https://github.com/netbirdio/service/pull/3
Closes #2572
=> [client] Update service package version

.github/workflows/golang-test-darwin.yml, .github/workflows/golang-test-linux.yml, .github/workflows/golang-test-windows.yml, .github/workflows/golangci-lint.yml, .github/workflows/install-script-test.yml, .github/workflows/mobile-build-validation.yml, .github/workflows/release.yml, .github/workflows/test-infrastructure-files.yml
=> [misc] Update core github actions

.github/workflows/golang-test-darwin.yml, .github/workflows/golang-test-linux.yml, .github/workflows/golang-test-windows.yml, .github/workflows/golangci-lint.yml, .github/workflows/mobile-build-validation.yml, .github/workflows/release.yml, .github/workflows/test-infrastructure-files.yml, go.mod
=> Update Go version to 1.23

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handler.go, management/server/http/peers_handler.go
Refactored the accessible peers from the` /api/peers/{peerId}` response to a dedicated endpoint `/api/peers/{peerId}/accessible-peers`.
=> [management] Add accessible peers endpoint

client/internal/peer/conn.go, client/internal/peer/worker_relay.go
=> Fix wg handshake checking

util/log.go
=> [misc] Support configurable max log size with var NB_LOG_MAX_SIZE_MB

relay/healthcheck/receiver.go, relay/healthcheck/sender.go
=> Change heartbeat timeout

relay/client/client.go, relay/client/client_test.go
=> Fix blocked net.Conn Close call

relay/client/client.go, relay/server/peer.go
=> [relay] update logs

client/internal/peer/status.go
=> Fix get management and signal state race condition

management/server/activity/sqlite/crypt.go, management/server/activity/sqlite/crypt_test.go
=> [management] fix legacy decrypting of empty values 

client/internal/peer/conn.go, client/internal/wgproxy/proxy_userspace.go, relay/client/client.go
Do not block the msg receiving if the wg proxy does not operate
- Increase queue size and drop the overflowed messages
- Explicit close the net.Conn in user space wgProxy when close the wgProxy
- Add log to conn creation and close events across the wg proxy flow.
-
=> Do not block the msg receiving if the wg proxy does not operate

client/errors/errors.go
=> [client] Fix error count formatting

management/server/sql_store.go
=> [management] Add get DB method to store

client/cmd/testutil_test.go, client/internal/engine_test.go, client/server/server_test.go, go.mod, go.sum, signal/client/client_test.go, signal/cmd/run.go, signal/server/signal.go
Propagates the cmd context down to signal-dispatcher.
=> [signal] add context to signal-dispatcher

go.mod, go.sum, signal/server/signal.go
Propagate opentelemetry meter into signal dispatcher.
=> [signal] Propagate metrics

client/internal/wgproxy/ebpf/proxy.go
=> Fix ebpf close function

.github/workflows/release.yml, .goreleaser.yaml, .goreleaser_ui.yaml, .goreleaser_ui_darwin.yaml, CONTRIBUTING.md
This allows usage of goreleaser 2 version both locally and in CI
=> Specify goreleaser version and update to 2

relay/metrics/realy.go, relay/server/relay.go
Measure the Relay client's authentication time
=> [relay-server] Relay measure auth time

.github/workflows/release.yml
=> Update docker creds

infrastructure_files/getting-started-with-zitadel.sh
This avoids full disk on busy systems
=> Add log setting to Caddy container

.github/workflows/install-script-test.yml, release_files/install.sh
=> Use the pkgs to get the latest version

client/internal/peer/worker_relay.go
=> [client] Adjust relay worker log level and message

management/Dockerfile, management/Dockerfile.debug
=> [management] Update management base docker image

management/server/account.go, management/server/mock_server/account_mock.go, management/server/sql_store.go
=> [management] Add AccountExists to AccountManager

management/server/peer.go
=> [management] Validate peer ownership during login

management/server/sql_store.go, management/server/status/error.go
=> [management] Propagate error in store errors

.github/workflows/golang-test-linux.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml, management/server/sql_store.go
=> [management] Make max open db conns configurable

management/server/user.go
=> Add billing user role

management/server/account.go
=> [management] Fix domain information is up to date check

.github/workflows/release.yml
=> Update sign workflow version

management/server/account.go
=> Release global lock on early error

management/server/account.go
=> [management] Fix context cancellation with JWT group sync enabled

management/server/http/accounts_handler.go
=> [management] Fix session inactivity response

client/firewall/iptables/router_linux.go, client/firewall/nftables/manager_linux.go, client/firewall/nftables/router_linux.go, client/firewall/uspfilter/uspfilter.go
=> [client] Remove legacy forwarding rules in userspace mode

client/internal/peer/conn.go, client/internal/peer/nilcheck.go, client/internal/peer/worker_ice.go
=> [client] Nil check on ICE remote conn

client/iface/wgproxy/bind/proxy.go
=> Allocate new buffer for every package

.github/workflows/golang-test-linux.yml
=> Avoid failing all other matrix tests if one fails

go.mod, go.sum, management/server/account_test.go, management/server/integrated_validator/interface.go, management/server/management_test.go, management/server/peer.go, management/server/peer_test.go
On peer validation, we missed sending the network map update. This PR will fix this.
=> [management] Fix network map update on peer validation

relay/server/listener/ws/listener.go
=> [relay-server] Use X-Real-IP in case of reverse proxy

client/anonymize/anonymize.go
=> [client] Exclude split default route ip addresses from anonymization

management/server/http/routes_handler.go
=> [management] Fix api error message typo peers_group

client/firewall/iptables/manager_linux.go, client/firewall/nftables/manager_linux.go, client/internal/config.go, client/internal/dns/server.go, client/internal/statemanager/manager.go, client/internal/statemanager/path.go, management/server/file_store.go, util/file.go, util/file_test.go
=> [client] Improve state write timeout and abort work early on timeout

client/internal/routemanager/client_test.go
- Add two new test cases for p2p and relay routes with same latency
- Add extra statuses generation
=> Update route calculation tests

client/internal/engine.go
=> [client] Handle panic on nil wg interface

client/internal/routemanager/systemops/systemops_generic.go
=> [client] Move state updates outside the refcounter

client/internal/connect.go
=> [client] Fix error state race on mgmt connection error

client/internal/dns/server_test.go
fixes the dns tests on macos and freebsd
=> [misc] use google domain for tests

.github/workflows/release.yml
=> [misc] Update signing pipeline version

management/server/peer.go, management/server/sql_store.go, management/server/telemetry/store_metrics.go
=> [management] Add transaction metrics and exclude getAccount time from peers update

management/server/peer.go, management/server/telemetry/accountmanager_metrics.go
=> [management] Add metric for peer meta update

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/setupkey.go, management/server/setupkey_test.go
https://github.com/netbirdio/netbird/issues/2923
=> [management] Fix getSetupKey call

README.md
=> [misc] Renew slack link

relay/client/picker_test.go
=> Import time package

client/firewall/uspfilter/uspfilter.go
=> [client]  Don't return error in userspace mode without firewall when setting legacy

management/server/account_test.go
=> [management] Add performance test for login and sync calls

management/server/jwtclaims/jwtValidator.go
Some users face issues with their IdP due to signing key not being refreshed
With this change we advise users to configure key refresh
=> Add guide when signing key is not found

client/cmd/pprof.go
For the easiest future debugging, prepared the pprof listener. This feature depend from the "pprof" build tag.
```
go build -tags pprof
```
=> [client] Add pprof build tag

client/server/debug_test.go
=> [client] Fix debug bundle state anonymization test

client/internal/peer/conn.go
=> [client] Pass IP instead of net to Rosenpass

client/server/debug.go
Adds `netbird.err` and `netbird.out` to the debug bundle
=> [client] Add netbird.err and netbird.out to debug bundle

management/server/peer.go
=> [management] merge update account peers in sync call

management/server/peer.go
Replicate behavior in sync method regarding meta updates.
https://github.com/netbirdio/netbird/issues/1803
=> Update account peers on login on meta change

client/internal/config.go, client/internal/connect.go, client/internal/engine.go, client/internal/mobile_dependency.go, client/internal/routeselector/routeselector_test.go, client/ios/NetBirdSDK/client.go, client/ios/NetBirdSDK/preferences.go, client/ios/NetBirdSDK/preferences_test.go
This PR includes all the necessary changes to support the new state manager on iOS.
=> [client] Add support for state manager on iOS

management/server/peer.go
=> [management] Remove peer needs login log message

management/cmd/management.go, management/server/http/configs/auth.go, management/server/http/handler.go, management/server/http/handlers/accounts/accounts_handler.go, management/server/http/handlers/accounts/accounts_handler_test.go, management/server/http/handlers/dns/dns_settings_handler.go, management/server/http/handlers/dns/dns_settings_handler_test.go, management/server/http/handlers/dns/nameservers_handler.go, management/server/http/handlers/dns/nameservers_handler_test.go, management/server/http/handlers/events/events_handler.go, management/server/http/handlers/events/events_handler_test.go, management/server/http/handlers/groups/groups_handler.go, management/server/http/handlers/groups/groups_handler_test.go, management/server/http/handlers/peers/peers_handler.go, management/server/http/handlers/peers/peers_handler_test.go, management/server/http/handlers/policies/geolocation_handler_test.go, management/server/http/handlers/policies/geolocations_handler.go, management/server/http/handlers/policies/policies_handler.go, management/server/http/handlers/policies/policies_handler_test.go, management/server/http/handlers/policies/posture_checks_handler.go, management/server/http/handlers/policies/posture_checks_handler_test.go, management/server/http/handlers/routes/routes_handler.go, management/server/http/handlers/routes/routes_handler_test.go, management/server/http/handlers/setup_keys/setupkeys_handler.go, management/server/http/handlers/setup_keys/setupkeys_handler_test.go, management/server/http/handlers/users/pat_handler.go, management/server/http/handlers/users/pat_handler_test.go, management/server/http/handlers/users/users_handler.go, management/server/http/handlers/users/users_handler_test.go, management/server/http/util/util.go
This PR adds some structure to our api files.
=> [management] restructure api files

management/server/account.go, management/server/account_test.go, management/server/networks/network.go, management/server/networks/network_resource.go, management/server/networks/network_router.go, management/server/sql_store.go, management/server/sql_store_test.go, management/server/status/error.go, management/server/store.go, management/server/testdata/store.sql
=> [management] Add networks database support

client/internal/dns/mock_server.go, client/internal/dns/server.go, client/internal/peer/conn.go, client/internal/routemanager/dnsinterceptor/handler.go, client/internal/routemanager/manager.go
=> Implement upstream DNS for intercepted domains

.github/workflows/golangci-lint.yml, client/internal/dns/mock_server.go, client/internal/engine.go, client/internal/engine_test.go
=> Fix engine tests

management/server/account.go, management/server/groups/manager.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handler.go, management/server/http/handlers/groups/groups_handler.go, management/server/http/handlers/networks/handler.go, management/server/http/handlers/networks/resources_handler.go, management/server/http/handlers/peers/peers_handler.go, management/server/mock_server/account_mock.go, management/server/networks/resources/types/resource.go, management/server/networks/routers/manager.go, management/server/networks/types/network.go, management/server/permissions/manager.go, management/server/store/sql_store.go, management/server/store/store.go
=> [management] Add routing peer counter

client/internal/engine.go
=> DNS interceptor feature flag on router

client/internal/dns/handler_chain.go, client/internal/dns/handler_chain_test.go, client/internal/dns/mock_server.go, client/internal/dns/server.go, client/internal/dns/server_test.go, client/internal/routemanager/dnsinterceptor/handler.go
=> Don't remove handlers from mux if still in use

release_files/install.sh
Check dnf version to change add repo command according to [this change](https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/#_for_fedora_41_or_later_dnf_5)
https://github.com/netbirdio/netbird/issues/3014
=> Handle dnf version 5 in install script

management/server/http/handlers/networks/handler.go, management/server/networks/manager.go, management/server/networks/resources/manager.go, management/server/types/account.go
=> [management] Remove resource from groups when resource deleted

client/anonymize/anonymize.go, client/anonymize/anonymize_test.go, client/cmd/networks.go, client/internal/dns/handler_chain.go, client/internal/dns/handler_chain_test.go, client/internal/dns/local.go, client/internal/dns/server_test.go, client/internal/dns/upstream.go, client/internal/dnsfwd/forwarder.go, client/internal/peer/status.go, client/internal/routemanager/client.go, client/internal/routemanager/dnsinterceptor/handler.go, client/internal/routemanager/dynamic/route.go, client/ios/NetBirdSDK/client.go, client/server/network.go, client/ui/network.go
=> Improve dns forwarder errors and improve domain anonymization

client/internal/dns/server.go, client/internal/dnsfwd/forwarder.go, client/internal/engine.go, client/internal/routemanager/dnsinterceptor/handler.go
=> Fix dns forwarder update

management/server/networks/manager.go, management/server/networks/resources/manager.go, management/server/networks/routers/manager.go
=> [management] increase network serial on change of networks

management/server/account_test.go, management/server/http/handlers/peers/peers_handler.go, management/server/peer.go, management/server/peer_test.go, management/server/route_test.go, management/server/types/account.go
=> [management] Extract resource routing peers into a map

client/internal/dns/server.go, client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/manager.go
=> Update dns forwarder domains on startup

management/server/route_test.go, management/server/types/account.go
=> [management] Refactor network router source peers collection

management/server/groups/manager.go, management/server/networks/manager.go, management/server/networks/resources/manager.go, management/server/networks/resources/types/resource.go, management/server/networks/routers/manager.go, management/server/networks/routers/types/router.go, management/server/types/group.go
=> [management] Fix event meta

client/internal/engine.go
=> Do not start DNS forwarder on client side

client/internal/dns/handler_chain.go
=> [client] Reduce DNS handler chain lock contention

.github/workflows/golang-test-linux.yml
=> [management] Run test sequential

client/server/debug.go
=> [client] Don't fail debug if log file is console

client/firewall/uspfilter/conntrack/common.go, client/firewall/uspfilter/conntrack/tcp.go, client/firewall/uspfilter/conntrack/tcp_test.go
=> [client] Fix inbound tracking in userspace firewall

management/server/group.go
=> [management] Add missing group usage checks for network resources and routes access control

go.mod, go.sum, management/server/networks/resources/types/resource.go, management/server/store/store.go, management/server/types/account.go, management/server/types/account_test.go, management/server/types/policy.go, route/route.go
This PR removes the sorting and switches back to a map-based approach as the sorting got very costly for worst-case scenarios
=> [management] remove sorting from network map generation

management/server/policy_test.go, management/server/types/firewall_rule.go
- Add firewall rule isEqual method
- Fix tests
=> [management] Fix policy tests

client/internal/connect.go, client/internal/engine.go, client/server/server.go
=> [client] Enable network map persistence by default

.goreleaser.yaml, client/Dockerfile-rootless, client/iface/netstack/env.go, client/internal/routemanager/manager.go, client/internal/routemanager/systemops/systemops_generic.go
=> [client] Add rootless container and fix client routes in netstack mode

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/migration/migration.go, management/server/networks/resources/manager.go, management/server/networks/resources/types/resource.go, management/server/networks/routers/manager_test.go, management/server/networks/routers/types/router.go, management/server/networks/routers/types/router_test.go, management/server/route_test.go, management/server/store/sql_store_test.go, management/server/store/store.go, management/server/types/account.go, management/server/types/account_test.go
=> [management] Add support for disabling resources and routing peers in networks

management/server/peer_test.go, management/server/token_mgr.go, management/server/token_mgr_test.go
linked to the issue fixed in #3162
=> [management] Send relay credentials with turn updates

management/server/peer.go
=> [Management] Send peer network map when SSH status is toggled

management/server/account_test.go, management/server/peer_test.go
=> [management] adjust benchmark

management/server/http/handlers/networks/resources_handler.go, management/server/http/handlers/networks/routers_handler.go
=> [Management] Enable new network resources and routers by default

.github/workflows/golang-test-linux.yml
=> [misc] Skip docker step when fork PR

.github/workflows/golang-test-linux.yml
=> [management] Update benchmark workflow

client/internal/dns/host_darwin.go
=> [client] Flush macOS DNS cache after changes

client/system/info_windows.go
=> [client] Fix windows info out of bounds panic

management/server/migration/migration.go
=> [management] Fix network migration issue in Postgres

management/server/account.go, management/server/grpcserver.go, management/server/peer.go
=> [management] add duration logs to Sync

client/internal/peer/worker_ice.go
=> [client] Close ice agent only if not nil

management/server/integrated_validator.go, management/server/peer.go
=> [management] extract getSettings calls from transactions

management/server/http/testing/benchmarks/peers_handler_benchmark_test.go, management/server/peer.go, management/server/peer_test.go
=> [management] remove peer from group on delete

client/iface/device/device_kernel_unix.go, client/iface/device/device_usp_unix.go, client/iface/freebsd/link.go
=> [client] Fix freebsd default routes

management/server/peer.go, management/server/telemetry/accountmanager_metrics.go, management/server/telemetry/grpc_metrics.go, management/server/telemetry/http_api_metrics.go, management/server/telemetry/idp_metrics.go, management/server/telemetry/store_metrics.go, management/server/telemetry/updatechannel_metrics.go, management/server/types/account.go, relay/metrics/realy.go, signal/metrics/app.go
=> [management/signal/relay] add metrics descriptions

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> [management] add openapi specs and generate types for port forwarding proxy

client/internal/routemanager/client.go
=> [client] Use dynamic dns route resolution on iOS

management/server/types/policyrule.go
=> [management] copy source and destination resource on policyRule copy

.github/workflows/release.yml
=> Update sign pipeline version

client/firewall/nftables/acl_linux.go
=> [client] Add missing peer ACL flush

client/firewall/iptables/acl_linux.go, client/firewall/iptables/manager_linux.go, client/firewall/iptables/router_linux.go, client/firewall/iptables/router_linux_test.go, client/firewall/iptables/rule.go, client/firewall/manager/firewall.go, client/firewall/manager/forward_rule.go, client/firewall/nftables/acl_linux.go, client/firewall/nftables/manager_linux.go, client/firewall/nftables/router_linux.go, client/firewall/nftables/router_linux_test.go, client/firewall/nftables/rule_linux.go, client/firewall/uspfilter/rule.go, client/firewall/uspfilter/uspfilter.go, client/firewall/uspfilter/uspfilter_test.go, client/internal/acl/id/id.go, client/internal/acl/manager.go, client/internal/acl/manager_test.go, client/internal/ingressgw/manager.go, client/internal/ingressgw/manager_test.go
=> Add port forwarding firewall and redirect rules

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> [management] renamed ingress port endpoints

client/internal/peer/conn_status_test.go, client/internal/peer/conn_test.go, go.mod, management/server/http/handlers/groups/groups_handler.go, management/server/http/handlers/groups/groups_handler_test.go, management/server/http/handlers/policies/policies_handler_test.go, management/server/http/handlers/routes/routes_handler_test.go
=> [client, server] Cleanup magiconair usage from repo

management/client/rest/accounts.go, management/client/rest/accounts_test.go, management/client/rest/client.go, management/client/rest/client_test.go, management/client/rest/dns.go, management/client/rest/dns_test.go, management/client/rest/events.go, management/client/rest/events_test.go, management/client/rest/geo.go, management/client/rest/geo_test.go, management/client/rest/groups.go, management/client/rest/groups_test.go, management/client/rest/networks.go, management/client/rest/networks_test.go, management/client/rest/peers.go, management/client/rest/peers_test.go, management/client/rest/policies.go, management/client/rest/policies_test.go, management/client/rest/posturechecks.go, management/client/rest/posturechecks_test.go, management/client/rest/routes.go, management/client/rest/routes_test.go, management/client/rest/setupkeys.go, management/client/rest/setupkeys_test.go, management/client/rest/tokens.go, management/client/rest/tokens_test.go, management/client/rest/users.go, management/client/rest/users_test.go, management/server/testdata/store.sql
=> Management REST Client Code

management/server/account.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handlers/groups/groups_handler.go, management/server/http/handlers/groups/groups_handler_test.go, management/server/http/handlers/peers/peers_handler.go, management/server/http/handlers/peers/peers_handler_test.go, management/server/integrated_validator.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer_test.go, management/server/peers/manager.go, management/server/store/sql_store.go, management/server/store/sql_store_test.go, management/server/store/store.go
=> [management] Add support for filtering peers by name and IP

management/server/policy.go
=> [management] copy port info on firewall rule proto conversion

management/server/types/firewall_rule.go
=> [management] fix duplication detection

client/internal/acl/manager.go
=> [client] Fix grouping of peer ACLs with different port ranges

client/internal/dns/handler_chain_test.go
=> [client] Fix dns handler chain test

management/client/rest/accounts_test.go, management/client/rest/client_test.go, management/client/rest/dns_test.go, management/client/rest/events_test.go, management/client/rest/geo_test.go, management/client/rest/groups_test.go, management/client/rest/networks_test.go, management/client/rest/peers_test.go, management/client/rest/policies_test.go, management/client/rest/posturechecks_test.go, management/client/rest/routes_test.go, management/client/rest/setupkeys_test.go, management/client/rest/tokens_test.go, management/client/rest/users_test.go
=> fix integration tests

management/server/http/api/openapi.yml
=> [management] add cloud tag to get ingress ports api spec

client/internal/dns/local.go, client/internal/dns/server.go
Normalize DNS record names to lowercase in local handler update
=> [client] Normalize DNS record names to lowercase in local handler update

signal/cmd/run.go, signal/metrics/app.go, signal/server/signal.go
=> [signal] add pprof and message size metrics

.github/workflows/golang-test-linux.yml, management/README.md
=> Run management benchmarks on changes test

.github/workflows/golang-test-linux.yml, management/README.md
They will always run on `Main`
test run with management changes: https://github.com/netbirdio/netbird/pull/3344
=> [misc] Run management benchmark jobs on file changes

signal/server/signal.go
=> [signal] Fix registry not found

infrastructure_files/docker-compose.yml.tmpl.traefik
=> improvement(template): add traefik labels to relay

management/server/grpcserver.go
Ensures new accounts created from client do not have a permission error on first login.
=> [management] fix grpc new account

.github/workflows/golang-test-darwin.yml, .github/workflows/golang-test-freebsd.yml, .github/workflows/golang-test-windows.yml, .github/workflows/golangci-lint.yml, .github/workflows/mobile-build-validation.yml
=> [misc] Rename client tests in CI

client/iface/bind/udp_mux.go, client/internal/dns/server_test.go, client/internal/stdnet/filter.go, client/internal/stdnet/stdnet.go
=> [client] Update local interface addresses when gathering candidates

client/internal/config.go, client/server/server.go, client/ui/client_ui.go
=> [client] Disable notifications by default

client/internal/engine_test.go, client/internal/login.go, management/client/client.go, management/client/client_test.go, management/client/grpc.go, management/client/mock.go
=> [client] fix extra DNS labels parameter to Register method in client

README.md
=> Replace webinar link

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> [management] Add support for tcp/udp allocations 

management/server/peer.go
=> [management] Handle transaction error on peer deletion

client/internal/netflow/logger/logger.go, client/internal/netflow/logger/logger_test.go
=> fix logger stop

client/firewall/uspfilter/conntrack/common_test.go, client/firewall/uspfilter/uspfilter_test.go, client/internal/acl/manager_test.go, client/internal/dns/server_test.go, client/internal/engine.go, client/internal/netflow/conntrack/conntrack.go, client/internal/netflow/conntrack/conntrack_nonlinux.go, client/internal/netflow/manager.go, client/internal/netflow/types/types.go, go.mod, go.sum
=> Add conntrack flows

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/icmp_test.go, client/firewall/uspfilter/uspfilter.go
=> Flow icmp types codes

client/firewall/uspfilter/forwarder/endpoint.go, client/firewall/uspfilter/forwarder/icmp.go, client/firewall/uspfilter/forwarder/tcp.go, client/firewall/uspfilter/forwarder/udp.go
=> Fix forwarder log displaying

client/firewall/uspfilter/forwarder/endpoint.go
=> Fix forwarder log dir

client/firewall/uspfilter/forwarder/icmp.go
=> Add icmp type and code to forwarder flow event

client/firewall/uspfilter/conntrack/tcp.go
=> Fix tcp state

client/internal/routemanager/dnsinterceptor/handler.go
=> [client] Handle large DNS packets in dns route resolution

.github/ISSUE_TEMPLATE/bug-issue-report.md
=> Update bug-issue-report.md template

client/internal/netflow/logger/logger.go, client/internal/netflow/manager.go, client/internal/netflow/store/memory.go, flow/client/client.go
=> Handle flow updates

client/firewall/uspfilter/uspfilter.go
Also removes the slice allocation
=> Don't track intercepted packets

client/server/panic_windows.go
=> [client] Enable windows stderr logs by default

infrastructure_files/observability/grafana/dashboards/signal.json
=> [docs] Update typo

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/tcp.go, client/firewall/uspfilter/conntrack/udp.go, client/firewall/uspfilter/conntrack/udp_test.go
=> [client] Prevent panic in case of double close call

client/firewall/uspfilter/forwarder/icmp.go, client/firewall/uspfilter/forwarder/tcp.go, client/firewall/uspfilter/forwarder/udp.go
=> Fix forwarder IP source/destination

client/server/server.go
=> [client] Increase the timeout to 50 sec

management/server/event.go, management/server/http/handlers/events/events_handler.go
=> [management] activity external user info

README.md
=> Update link to kubernetes operator

client/server/network.go
=> [client] Nil check on route manager

client/anonymize/anonymize.go, client/server/debug.go
=> [client] Fix anonymized addresses documentation

client/internal/peer/conn.go, client/internal/peer/handshaker.go, client/internal/peer/state_dump.go, client/internal/peer/wg_watcher.go, client/internal/peer/wg_watcher_test.go, client/internal/peer/worker_relay.go
=> [client] Set info logs

client/internal/acl/manager.go, client/internal/netflow/manager.go
=> Fix squashed policy ID

go.mod, go.sum, management/server/account.go, management/server/account/account_manager_interface.go, management/server/cache/idp.go, management/server/cache/idp_test.go, management/server/cache/marshaler.go, management/server/cache/store.go, management/server/cache/store_test.go, management/server/idp/idp.go, management/server/user_test.go
=> Add redis cache abs

client/internal/peer/conn.go
=> [client] Fix state dump panic

client/firewall/uspfilter/uspfilter.go
=> [client] Refactor uspfilter forwarder calling 

go.mod, go.sum, management/server/account.go, management/server/integrations/extra_settings/manager.go, management/server/settings/manager.go
=> [management] peer update on extra settings change

client/internal/netflow/manager.go
=> [client] Flow keep token data during config update

management/client/rest/client.go
=> [management/rest-client] Add Bearer token support

client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/tcp.go, client/firewall/uspfilter/conntrack/udp.go
=> Add missing counters

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handlers/events/events_handler.go
=> [management] add flow api

client/internal/netflow/manager.go, client/internal/peer/status.go
=> [client] fix netflow resource id parse & loggin

management/server/posture/nb_version.go
Extension of the version check to ignore '-dev' versions, as they cannot be processed correctly (see #3453).
https://github.com/netbirdio/netbird/issues/3453
https://github.com/netbirdio/netbird/issues/3453#issuecomment-2718225910
=> fix Connection issues with -dev -alpha etc version

management/server/http/api/openapi.yml
=> [docs] add examples to events and tag to ingress port

client/internal/netflow/logger/logger.go
=> [client] Use UTC on event generation

management/server/http/api/openapi.yml
=> [docs] rename network traffic logging to traffic events

management/server/account.go, management/server/cache/idp_test.go, management/server/cache/store.go, management/server/cache/store_test.go, management/server/user_test.go
=> [management] add log when using redis cache

flow/client/client.go
=> [client] Don't permanently fail on flow grpc shutdown

go.mod, go.sum, management/cmd/management.go, management/server/http/testing/testing_tools/tools.go, management/server/permissions/manager.go, management/server/settings/manager.go
=> [management] Use store in permissions manager

client/internal/peer/status.go
=> [client] fix route handling for local peer state

go.mod, go.sum, management/server/group_test.go, management/server/user.go
=> [management] account invitor lookup

management/server/account.go, management/server/http/handlers/peers/peers_handler.go, management/server/http/handlers/peers/peers_handler_test.go, management/server/peer.go, management/server/permissions/manager.go, management/server/user.go
=> [management] permissions account settings peer

client/server/server.go, client/server/server_test.go
=> [client] Ensure status recorder is always initialized

client/internal/dns/systemd_linux.go
systemd-resolved sets the default route by default even when not requested. This change sets it to off if we're not handling the root zone.
```diff
Link 9 (wt0)
Current Scopes: DNS
-     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
+     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
DNS Servers: 100.64.107.240
DNS Domain: netbird.cloud 64.100.in-addr.arpa
```
=> [client] Disable systemd-resolved default route explicitly on match domains only

management/server/account.go, management/server/permissions/manager.go
=> [management] Permission manager on account delete

management/server/user.go, management/server/user_test.go
=> [management] fix user on update

client/internal/peer/conn.go, client/internal/peer/wg_watcher.go, client/internal/peer/wg_watcher_test.go
=> [client] Fix close WireGuard watcher

management/server/account/manager.go, management/server/mock_server/account_mock.go, management/server/store/sql_store.go, management/server/store/store.go, management/server/user.go
=> [management] add get account owner method

management/server/http/handlers/routes/routes_handler.go, management/server/permissions/manager.go, management/server/route.go
=> [management] Refactor api permissions

management/server/account.go, management/server/dns.go, management/server/event.go, management/server/group.go, management/server/nameserver.go, management/server/peer.go, management/server/permissions/manager.go, management/server/policy.go, management/server/posture_checks.go, management/server/route.go, management/server/setupkey.go, management/server/user.go
=> [management] permissions account allow owner

management/server/status/error.go
=> [management] fix typo in invalid account error msg

client/firewall/uspfilter/localip.go, client/firewall/uspfilter/localip_test.go
- lower memory footprint in most cases
- increase accuracy
=> [client] Improve local ip lookup

client/firewall/uspfilter/uspfilter.go, client/internal/engine.go, client/internal/routemanager/server_nonandroid.go
- Fixes missing inbound flows
- Fixes NAT in userspace mode with native router (was broken on `up`)
=> [client] Fix missing inbound flows in Linux userspace mode with native router

client/internal/routemanager/server_nonandroid.go
[client] Fix route removal logic to handle dynamic routes correctly
=> [client] Fix route removal logic to handle dynamic routes correctly

client/cmd/login.go, client/cmd/up.go
[client] Add no-browser flag to login and up commands for SSO login control
https://github.com/netbirdio/netbird/issues/3608
=> [client] Add no-browser flag to login and up commands for SSO login control

client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/manager.go, client/internal/engine.go, client/internal/netflow/logger/logger.go, client/internal/peer/route.go, client/internal/peer/status.go
[client] Enhance DNS forwarder to track resolved IPs with resource IDs
=> [client] Enhance DNS forwarder to track resolved IPs with resource IDs

.github/workflows/golang-test-freebsd.yml
Update FreeBSD release to 14.2 and download Go package directly since port wasn't finding the package to install
=> [misc] Update FreeBSD workflow

client/firewall/uspfilter/uspfilter.go
=> [client] Support IP fragmentation in userspace

.git-branches.toml, .github/workflows/git-town.yml
This PR configures the repo with our recommended [Git Town](https://www.git-town.com/) configuration.
=> add git town workflow config

client/internal/dns/server.go
=> [client] Fix race dns cleanup race condition

.github/pull_request_template.md
Include the stack on the PR template, more info about this [here](https://github.com/marketplace/actions/git-town-github-action#modify-the-pull-request-template).
=> [ci] include stash in pr template

management/server/http/handler.go, management/server/http/handlers/policies/geolocation_handler_test.go, management/server/http/handlers/policies/geolocations_handler.go, management/server/http/handlers/policies/policies_handler.go, management/server/http/handlers/policies/posture_checks_handler.go
=> [management] add permissions manager to geolocation handler

client/server/debug.go
=> [client] Add heap profile to debug bundle

client/server/debug.go
=> [client] Add remaining debug profiles

client/iface/bind/udp_mux.go, client/internal/peer/ice/agent.go
[client] Remove logrus writer assignment in pion logging
=> [client] Remove logrus writer assignment in pion logging

client/internal/routeselector/routeselector.go, client/internal/routeselector/routeselector_test.go
=> [client] Keep selecting new networks after first deselection

.github/workflows/golang-test-linux.yml
=> [management] benchmarks use ref_name instead

.github/workflows/golang-test-linux.yml, management/server/http/testing/benchmarks/users_handler_benchmark_test.go, management/server/http/testing/testing_tools/tools.go
=> [management] fix github run id

client/internal/routeselector/routeselector.go, client/internal/routeselector/routeselector_test.go
=> [client] Keep new routes selected unless all are deselected

management/server/account.go, management/server/account/manager.go, management/server/http/api/openapi.yml, management/server/http/api/types.gen.go, management/server/http/handlers/accounts/accounts_handler.go, management/server/http/handlers/accounts/accounts_handler_test.go, management/server/mock_server/account_mock.go, management/server/store/sql_store.go, management/server/store/sql_store_test.go, management/server/store/store.go, management/server/testdata/extended-store.sql, management/server/types/account.go
=> Add account meta

.github/workflows/golang-test-linux.yml
=> [misc] Change github runner for docker test

client/ui/client_ui.go
[client/ui] add connecting state to status handling
=> [client/ui] add connecting state to status handling

client/cmd/login.go, client/cmd/service_controller.go, client/system/info.go, client/system/static_info.go, client/system/static_info_stub.go
Detect platform only when running as root or when not running on Darwin
=> [client] Fix macos privacy warning when checking static info

management/server/http/middleware/auth_middleware.go, management/server/http/middleware/auth_middleware_test.go
=> [management] allow impersonation via pats

.github/workflows/golang-test-linux.yml, client/Dockerfile, client/firewall/uspfilter/tracer_test.go, client/internal/routemanager/systemops/systemops_bsd_test.go, client/internal/routemanager/systemops/systemops_linux_test.go, client/internal/routemanager/systemops/systemops_unix_test.go
=> [client] Run container tests more generically

management/server/types/user.go
Add missing network admin mapping to user type
=> [management] add missing network admin mapping

management/server/account.go, management/server/store/sql_store.go
updated log to display account id
=> [management] Get account id with order

management/server/account.go
=> [management] Optimize load account

release_files/install.sh
[client] Improve NetBird installation script to handle daemon connection timeout
=> [client] Improve NetBird installation script to handle daemon connection timeout

management/server/store/sql_store.go
=> [management] policy delete cleans policy rules

sharedsock/sock_linux.go
=> [client] Return with the correct copied length

client/internal/dns/service_listener.go, client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/manager.go
[client] Add TCP support to DNS service listener
=> [client] Add TCP support to DNS service listener

management/client/rest/client.go, management/client/rest/options.go, management/client/rest/policies.go, management/client/rest/setupkeys.go, management/client/rest/setupkeys_test.go
Add configurable options to the management REST client package
- `feature/extend-rest-client` - :warning: No PR associated with branch 
- \#3816 :point\_left:
=> [management] REST client with configurable options

go.mod, go.sum, signal/server/signal.go
=> [signal] remove stream receive server side

.github/ISSUE_TEMPLATE/bug-issue-report.md
=> [misc] Update issue template

client/internal/debug/debug.go
[client] Add latest gzipped rotated log file to the debug bundle
=> [client] Add latest gzipped rotated log file to the debug bundle

.github/pull_request_template.md
=> [misc] Add CLA note

.github/pull_request_template.md
> By submitting this pull request, you confirm that you have read and agree to the terms of the Contributor License Agreement: https://gist.github.com/netbirddev/37ff3dc89cf853c6df89d1e5ae07030a
=> Fix CLA link in the PR template

management/server/http/api/openapi.yml, management/server/http/api/types.gen.go
=> [management] Update traffic events pagination filters

client/cmd/service.go, client/cmd/service_installer.go
=> [client] Allow the netbird service to log to console

README.md
=> [misc] use generic slack url

.github/workflows/release.yml, .goreleaser.yaml
=> [misc] Push all docker images to ghcr in releases

client/android/client.go, client/android/networks.go, client/android/peer_notifier.go
Propagation networks for the Android client
=> [client] Propagation networks for Android client

management/server/setupkey_test.go, management/server/types/setupkey.go
=> [management] Use xID for setup key IDs to avoid id collisions

client/cmd/trace.go, client/firewall/uspfilter/conntrack/common.go, client/firewall/uspfilter/conntrack/icmp.go, client/firewall/uspfilter/conntrack/icmp_test.go, client/firewall/uspfilter/forwarder/endpoint.go, client/firewall/uspfilter/forwarder/tcp.go, client/firewall/uspfilter/forwarder/udp.go, client/firewall/uspfilter/uspfilter.go, client/internal/netflow/conntrack/conntrack.go
Example log:
```
2025-06-12T12:16:10+00:00 TRAC New ingress ICMP connection 100.125.194.240 → 100.125.248.69 (id 0) - DestinationUnreachable(Port) (original: UDP 100.125.248.69:49481 → 100.125.194.240:80)
```
=> [client] Improve icmp conntrack log

client/internal/peer/status.go
=> [client] Fix status recorder panic

client/internal/dns/handler_chain.go, client/internal/dns/handler_chain_test.go, client/internal/dns/server.go, client/internal/dns/server_test.go
=> [client] Prioritze the local resolver in the dns handler chain

client/internal/dns/upstream.go, client/internal/dnsfwd/forwarder.go, client/internal/dnsfwd/forwarder_test.go, client/internal/routemanager/dnsinterceptor/handler.go
=> [client] Tighten allowed domains for dns forwarder

client/ui/client_ui.go
[client] Fix logic in updateStatus to correctly handle connection state
=> [client] Fix logic in updateStatus to correctly handle connection state

client/android/preferences.go, client/iface/device/device_android.go, client/iface/iface.go, client/iface/iface_new_android.go, client/internal/config.go, client/internal/engine.go
=> [client] Add more Android advanced settings

client/internal/acl/manager.go, client/internal/acl/manager_test.go
=> [client] Fix port range squashing

.github/workflows/release.yml, client/netbird.wxs
=> [client] Don't open cmd.exe during MSI actions

management/server/peer.go, management/server/telemetry/updatechannel_metrics.go
=> [management] add breakdown of network map calculation metrics

management/server/integrated_validator.go
=> [management] remove unused transaction

client/ui/client_ui.go
Fix a blocking case when the popup is displayed and user can't find among different GUIs and our systray is blocked.
=> [client] Run login popup on goroutine

README.md
=> [doc] Add forum link

client/internal/routemanager/systemops/systemops.go, client/internal/routemanager/systemops/systemops_unix.go
=> [client] Use unique sequence numbers for bsd routes

client/internal/lazyconn/manager/manager.go
=> [client] Fix nil pointer exception in lazy connection

management/client/rest/accounts.go, management/client/rest/client.go, management/client/rest/dns.go, management/client/rest/events.go, management/client/rest/geo.go, management/client/rest/groups.go, management/client/rest/networks.go, management/client/rest/peers.go, management/client/rest/peers_test.go, management/client/rest/policies.go, management/client/rest/posturechecks.go, management/client/rest/routes.go, management/client/rest/setupkeys.go, management/client/rest/tokens.go, management/client/rest/users.go
=> [management] Add name/ip filters to peer management rest client

client/iface/iface.go
Fix panic when calling debug bundle on a down peer
This PR addresses an issue where invoking the debug bundle on a peer in the "down" state could cause a panic. The fix ensures the debug bundle handles such scenarios gracefully without crashing.
=> [client] Nil check in iface configurer

client/cmd/root.go
=> [client] Update cli description of lazy connection

.github/workflows/git-town.yml, .github/workflows/release.yml
=> [misc] add forum post and update sign pipeline

.github/workflows/golang-test-linux.yml
=> [client] Temporarily disable race detection in Relay

client/iface/wgproxy/listener/listener.go, client/iface/wgproxy/udp/proxy.go, relay/healthcheck/sender_test.go
=> [client] Fix UDP proxy to notify listener when remote conn closed

client/cmd/login.go, client/cmd/root.go, client/cmd/service_installer.go, client/cmd/up.go, release_files/systemd/netbird@.service
=> [client]: remove config flag

client/iface/configurer/usp.go
=> [client] Fix pre-shared key state in wg show

client/internal/profilemanager/config.go, client/internal/profilemanager/service.go
[client] Fix config directory path handling based on NB_STATE_DIR
=> [client] Fix config directory path handling based on NB_STATE_DIR

client/cmd/up.go, client/server/server.go
[client] Fix error handling for set config request on CLI
=> [client] Fix error handling for set config request on CLI

client/cmd/root.go, client/cmd/service_controller.go, client/cmd/service_installer.go, client/cmd/testutil_test.go, client/cmd/up.go, client/internal/debug/debug.go, client/internal/engine.go, client/internal/profilemanager/service.go, client/server/server.go, client/server/server_test.go
[client]: Add config flag to service to override default profile path
=> [client]: Add config flag to service to override default profile path

client/cmd/debug.go, client/internal/connect.go, client/internal/debug/debug.go, client/internal/engine.go, client/proto/daemon.pb.go, client/proto/daemon.proto, client/proto/daemon_grpc.pb.go, client/server/debug.go, client/server/server.go, client/ui/debug.go
=> [client] Add full sync response to debug bundle

.github/workflows/release.yml, .goreleaser.yaml, .goreleaser_ui.yaml, client/installer.nsis, client/netbird.wxs
=> [client] Add windows arm64 build

management/server/store/sql_store.go
=> [management] Mark SaveAccount deprecated

client/cmd/logout.go, shared/management/client/grpc.go
=> [client] Increase logout timeout

client/installer.nsis, client/netbird.wxs
=> [client] Update Windows installer description

.github/workflows/golang-test-freebsd.yml
=> [client] Fix Go tarball version in FreeBSD build configuration

client/cmd/testutil_test.go, client/internal/engine_test.go, client/server/server_test.go, management/cmd/management.go, management/cmd/root.go, management/internals/server/boot.go, management/internals/server/config/config.go, management/internals/server/container.go, management/internals/server/controllers.go, management/internals/server/modules.go, management/internals/server/server.go, management/server/grpcserver.go, management/server/management_proto_test.go, management/server/management_test.go, management/server/peer_test.go, management/server/token_mgr.go, management/server/token_mgr_test.go, shared/management/client/client_test.go
=> [management] Use DI containers for server bootstrapping

management/server/route.go, route/route.go
=> [management] add nil handling for route domains

management/server/account.go, management/server/group.go, management/server/integrated_validator.go, management/server/nameserver.go, management/server/networks/manager.go, management/server/networks/resources/manager.go, management/server/networks/routers/manager.go, management/server/peer.go, management/server/policy.go, management/server/posture_checks.go, management/server/route.go, management/server/setupkey.go, management/server/user.go
=> [management] Remove Store Locks 2

client/iface/device/device_netstack.go, client/iface/device/device_netstack_android.go, client/iface/device/device_netstack_generic.go, client/iface/iface_new_android.go, client/internal/stdnet/stdnet.go, util/net/protectsocket_android.go
https://github.com/netbirdio/netbird/issues/4318
=> [client] Add netstack support for Android cli

management/server/grpcserver.go, management/server/telemetry/grpc_metrics.go
=> [management] Report sync duration and login duration by accountID

management/server/telemetry/grpc_metrics.go
=> [management] split high latency grpc metrics

management/server/group.go, management/server/user.go
=> [management] remove lock and continue user update on failure

management/server/http/handlers/peers/peers_handler.go
=> [management] fix ephemeral flag on peer batch response

management/server/store/sql_store.go
=> [management] remove withContext from store methods

management/server/grpcserver.go, management/server/peer.go
=> [management] remove duplicated removal of groups on peer delete

management/server/account.go, management/server/account/manager.go, management/server/account_test.go, management/server/activity/codes.go, management/server/http/handlers/accounts/accounts_handler.go, management/server/http/handlers/accounts/accounts_handler_test.go, management/server/http/handlers/users/users_handler.go, management/server/http/handlers/users/users_handler_test.go, management/server/mock_server/account_mock.go, management/server/peer.go, management/server/peer_test.go, management/server/permissions/manager.go, management/server/types/settings.go, management/server/types/user.go, management/server/user.go, management/server/user_test.go, shared/management/http/api/openapi.yml, shared/management/http/api/types.gen.go, shared/management/status/error.go
https://github.com/netbirdio/docs/pull/421
=> [management] Add user approval

relay/server/listener/ws/listener.go
=> [relay] Let relay accept any origin

client/cmd/testutil_test.go, client/internal/engine_test.go, client/server/server_test.go, go.mod, go.sum, management/internals/server/controllers.go, management/server/peers/manager.go, management/server/peers/manager_mock.go, management/server/store/sql_store.go, management/server/store/sql_store_test.go, management/server/store/store.go, shared/management/client/client_test.go
=> [management] Extends integration and peers manager

client/android/client.go, client/android/env_list.go, client/iface/wgproxy/proxy_test.go, client/internal/peer/conn.go, client/internal/peer/env.go
Some features can only be manipulated via environment variables. With this PR, environment variables can be managed from Android.
Example usage from Java:
```
EnvList envList = new EnvList();
envList.put(Android.getEnvKeyNBForceRelay(), "True");
```
=> [client] Implement environment variable handling for Android

client/internal/connect.go, client/internal/debug/upload.go, client/internal/debug/upload_test.go, client/internal/engine.go, client/internal/engine_test.go, client/jobexec/executor.go, client/server/debug.go
- `feature/remote-debug` - :warning: No PR associated with branch 
- \#4428
- \#4469 :point\_left:
Paste the PR link from <https://github.com/netbirdio/docs> here:
<https://github.com/netbirdio/docs/pull/>\_\_
=> Refactor the debug bundle generator to be ready to use from engine

util/grpc/dialer.go
=> [client] Skip grpc tls verfication with ws transport

.goreleaser.yaml
=> [client] Release single wasm binary instead of archive

infrastructure_files/docker-compose.yml.tmpl.traefik, infrastructure_files/getting-started-with-zitadel.sh, infrastructure_files/nginx.tmpl.conf
https://github.com/netbirdio/docs/pull/437
=> [misc] Update infra scripts with ws proxy for browser client

infrastructure_files/docker-compose.yml.tmpl.traefik, infrastructure_files/getting-started-with-zitadel.sh
https://github.com/netbirdio/docs/pull/441
=> Adjust signal port for websocket connections
